### ISSUE TITLE
Files in cache have "random" permissions

### ISSUE THREAD

**Issue by emmenlau** [ccache/ccache#1007]
### How to reproduce ###

I'm not 100% sure how to reproduce this issue. Here is what we do:
1. Build ccache 4.5.1 from source
2. Enable ccache with symbolic links for `clang` and `clang++`
3. Build sources with cmake

### Actual behavior ###

The cache works and is used. However every now and then, the build fails because temporary object files in the build directory have read-only permissions `-r--r--r--`. Through some investigation, I've found that such permissions exist already in the cache! So I *assume* that the permission issue comes originally from `ccache`, not `cmake`, `ninja` or `clang`. I can not prove this, so please bare with me if this is not a great bug report :-(

We use environment variables:
```{bash}
declare -x CCACHE_CPP2="true"
declare -x CCACHE_DIR="/data/user/ccache"
declare -x CCACHE_HARDLINK="true"
declare -x CCACHE_MAXSIZE="64G"
declare -x CCACHE_NOCOMPRESS="true"
declare -x CCACHE_NOUNIFY="true"
```

The mount point `/data` is a physical nvme disk. It holds the cache, all the temporary object files and the build target directories. So hard links should be ok.

My shell sets umask `0007`. Here are the different file permissions that I see in the cache:
1. `-r--r--r--`: read-only, and also world readable? Not really good...
2. `-rw-rw----`: The usual, to be expected
3. `-rw-r--r--`: Ok, but world readable? Not so good...

**Note:** I have tried to work around this problem by setting `export CCACHE_UMASK="007"` but it *did not help*. There are still many files created with permissions `-r--r--r--`. Does that point to a bug in setting the permissions in `ccache`?

### Expected behavior ###

Files in the cache should all have sensible permissions, i.e. all have the umask from the shell?

### Environment ###

ccache version 4.5.1 compiled from source, used with cmake 3.22.1, Ninja 1.10.2, clang 13.0.1 on Ubuntu x86_64.

**Comment by jrosdahl** [comment]
It would help if you could say what kind of files you see with the different file permissions.

When the hard link mode is enabled, ccache intentionally makes hard linked output files (currently only object files) read-only. From [`hard_link` in the ccache manual](https://ccache.dev/manual/4.5.1.html#config_hard_link):

> _If the resulting file is modified, the file in the cache will also be modified since they share content, which corrupts the cache entry. As of version 4.0, ccache makes stored and fetched object files read-only as a safety measure guard._

So if your build fails because files have read-only permissions, it sounds like ccache has saved you from corrupting the cache since something tried to write to a file that is hard-linked to a file in ccache's cache.

That said, it's not intentional to use broader file permissions than umask for those read-only files. Will fix!

> 1. `-r--r--r--`: read-only, and also world readable? Not really good...

This sounds like separately stored (due to using the hard link mode) object files. Those files have a `0W` suffix.

> 2. `-rw-rw----`: The usual, to be expected

Yes.

> 3. `-rw-r--r--`: Ok, but world readable? Not so good...

This is unexpected. Could it be that somebody ran `chmod u+x` on a hard-linked object file with `-r--r--r--` permissions? That will then be reflected in corresponding file in ccache's cache as well.
