### ISSUE TITLE
Add configuration option to disable primary storage and use secondary storage only

### ISSUE THREAD

**Issue by mbamelis** [ccache/ccache#1010]
We are using Ccache to speedup our CI/CD pipelines that build and test our C++ applications. This is working wonderfully with the secondary storage backend (e.g. a Redis server) so the different pipelines get to share cached results.

However, our pipelines actually run an ephemeral container so primary storage is empty at the start and filling it is useless since the storage is not carried over to future builds. Therefore, it would be useful if we could configure Ccache to skip primary storage completely and only use secondary storage.

We've looked into `max-size` and `max-files` but putting those to "0" equals "no limit". Giving them a low value will trigger Ccache's cleanup logic (near) constantly.

**So we are looking for a way to configure Ccache to operate in a kind of "secondary storage only" mode for use in ephemeral environments.**

**Comment by jrosdahl** [comment]
This feature is planned for – see https://github.com/ccache/ccache/issues/856#issuecomment-875839782. The reason why `read_only_primary` can't just be added right away is that the code for secondary storage currently depends on the result landing in primary storage first (since that was faster to implement in order to get basic secondary storage functionality in place). In other words: some refactoring is needed first, and I haven't had time to do that yet.

**Comment by mbamelis** [comment]
I'm happy to see my request is not nonsense and you had actually already planned to implement it!

**Comment by u625030** [comment]
We would also very much be interested in this feature as we have a very similar use case.

**Comment by jrosdahl** [comment]
> When is the release of 4.7 planned?

Ccache releases don't follow any schedule. There is no specific plan for 4.7; it will be released when it's ready.
