### ISSUE TITLE
Util unit tests fail on s390x with ccache 4.6

### ISSUE THREAD

**Issue by nmeum** [ccache/ccache#1014]
### How to reproduce ###

Build ccache on s390x and run the test suite.

I noticed this on Alpine Linux Edge while upgrading our ccache package to 4.6.

### Actual behavior ###

The unit tests fail:

```
===============================================================================
/builds/alpine/aports/main/ccache/src/ccache-4.6/unittest/test_Util.cpp:692:
TEST SUITE: Util
TEST CASE:  Util::read_text_file with UTF-16 little endian encoding
/builds/alpine/aports/main/ccache/src/ccache-4.6/unittest/test_Util.cpp:707: ERROR: CHECK( Util::read_text_file("test") == "abc" ) is NOT correct!
  values: CHECK( 愀戀挀 == abc )
===============================================================================
```

s390x is a big endian architecture, looking at the `read_text_file` code this might be related to the fact that s390x is a big endian architecture.

Full build log: [alpine-linux-edge-s390x-ccache.txt](https://github.com/ccache/ccache/files/8157139/alpine-linux-edge-s390x-ccache.txt)

### Expected behavior ###

I expected all tests to pass.

### Environment ###

ccache version 4.6

**Comment by jrosdahl** [comment]
@vvainola: Perhaps this is something you would like to have a look at?

**Comment by vvainola** [comment]
I can try to take a look but I'm not sure am I able to reproduce the issue if it requires big-endian architecture and it's not possible to test with CI.

**Comment by nmeum** [comment]
> I can try to take a look but I'm not sure am I able to reproduce the issue if it requires big-endian architecture and it's not possible to test with CI.

You should be able to reproduce this using QEMU. You could even use a Docker container with https://github.com/multiarch/qemu-user-static if you don't want to setup a s390x VM.

**Comment by jrosdahl** [comment]
I can reproduce this on a big-endian PPC64 machine.

Since `Util::read_text_file` simply casts the bytes to `char16_t`, it will use the machine's endianness, not little-endian. I don't see a way of fixing this using the standard C++ codecvt machinery. And while learning more about this topic, I notice that `std::codecvt_utf8_utf16` and `std::wstring_convert` are deprecated in C++17, so it would be better to implement the functionality in some other way.

Since this test case blocks the test suite on big-endian Unix machines and the functionality is only needed in Windows in practice, I'm going to add #ifdefs as a workaround.
