### ISSUE TITLE
Absolute path to source is stored in gcno and used for __FILE__ even though CCACHE_BASEDIR is used

### ISSUE THREAD

**Issue by esger-abbink** [ccache/ccache#1032]
Situation:

CMake project with multiple subprojects with the following structure (condensed)

application/
- CMakeLists.txt
- source/
    - staticlibA/
        - CMakeLists.txt
        - source/
            - A.cpp
    - staticlibB/
        - CMakeLists.txt
        - source/
            - B.cpp
    - main.cpp
- test/
    - CMakeLists.txt
    - source/
        - test_main.cpp

We are building, with coverage, from different directories with often only minor code changes between directories, therefore ccache should be able to provide a very significant speedup. However even for identical sources I am not getting anywhere near a 100% cache hit rate.

In the top CMakeLists.txt I have:

```
# enable ccache
set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "CCACHE_BASEDIR=${CMAKE_SOURCE_DIR} ccache")

# Override default and omit <FLAGS> to prevent CMAKE_CXX_FLAGS being passed to the linker
set(CMAKE_CXX_LINK_EXECUTABLE
            "<CMAKE_CXX_COMPILER> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS>  -o <TARGET> <LINK_LIBRARIES>")

# rewrite gcda locations to relative paths
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fprofile-dir=`echo \\\`pwd\\\` | sed \"s|\${CMAKE_SOURCE_DIR}|.|\"`")

# rewrite debug information to relative paths
add_compile_options(-fdebug-prefix-map=${CMAKE_SOURCE_DIR}=.")
```
so if my source is located in `/home/esger/src/application`, it will set `CCACHE_BASEDIR=/home/esger/src/application`, and when compiling for instance `B.cpp` (builddir `/home/esger/src/application/build/source/staticlibB/CMakeFiles/staticlibB.dir/source`) it will set (effectively) compiler flags `-fprofile-dir=./build/source/staticlibB/CMakeFiles/staticlibB.dir/source` and `-fdebug-prefix-map=/home/esger/src/application=.`

This works only partly unfortunately. Suppose I have `/home/esger/src/application` (built first, against empty cache) and `/home/esger/src/application-2` (built second) containing identical source. Then for application-2:
- files with coverage using `__FILE__` (through an assert for instance) will produce no cache hits as `__FILE__` contains an absolute path and the preprocessor input will differ
- other files with coverage will generate cache hits, however the .gcno files taken from the cache contain absolute paths to the corresponding **original** source files(!). When running `./build/bin/test_main` from `/home/esger/src/application-2`, gcda files are indeed created in the correct locations next to the .gcno and .o (no `GCOV_PREFIX_STRIP/GCOV_PREFIX` necessary since the gcda paths match up from the cwd). However when subsequently running gcovr (`gcovr -r . --html -o coverage.html build/`) it will filter out the files with coverage because for those files the `fname`'s in the gcno files point to absolute locations below `/home/esger/src/application` where they were generated, resulting (almost silently!) in an incomplete coverage report. (Note that the coverage report is not completely empty because of the cache misses for files with `__FILE__`, which are compiled anew and for which working gcno files are generated for application-2)

Changing (ccache 4.5.1, argprocessing.cpp line 927)
```
  // The source code file path gets put into the notes.
  if (args_info.generating_coverage) {
    args_info.input_file = args[i];
    return nullopt;
  }
```
into

```
  // The source code file path gets put into the notes.
  if (args_info.generating_coverage) {
    args_info.input_file = Util::make_relative_path(ctx, args[i]);
    return nullopt;
  }
```
will not skip rewriting the path to relative and will generate gcno files containing relative paths. This solves both issues and results in 100% cache hits and a complete coverage report.

For the moment, we can use a patched ccache (if this change is otherwise safe? and the best quickfix?) but it would be nice if this got fixed officially.

**Comment by esger-abbink** [comment]
@jrosdahl can you confirm that the change described above is an appropriate fix and should have no negative effects?

**Comment by jrosdahl** [comment]
Thanks for the bug report. I don't have bandwidth to fully understand the CMake setup you describe, sorry.

That said, I don't understand the purpose of https://github.com/ccache/ccache/blob/0b3c5f17de5af6b5f0520295d96eb21c6ebe5a60/src/argprocessing.cpp#L1018-L1021 either. 02d3f078bd2495b8db2264ae0b2c692b4c5ba1bd says "also make sure to use the source file path, since this is in the notes", but it doesn't motivate why it would be better to keep the absolute path, especially since the hash isn't dependent in the input file path, leading to false positive cache hits like you mention.

I no longer remember details about how coverage and `.gcno` files work, so I've tried to read up a bit and do some experiments. When doing so I noticed that GCC 9+ includes the current working directory in the `.gcno` file (gcc-mirror/gcc@c74bd3fba3572d5825fcc7fabfd136b22c7981ad). This means that we need to hash the CWD to replicate what the compiler would produce. Since this makes it impossible get cache hits when compiling in different directories, I'll add a mechanism of opting out of hashing the CWD.
