### ISSUE TITLE
Permit setting ccache options when in compile mode

### ISSUE THREAD

**Issue by acmorrow** [ccache/ccache#1035]
The following is based on behavior observed with `ccache` 4.5.1.

The `ccache` program supports three different invocation modes. One is what, for lack of a better term, I'll call "control mode", where you are issuing a command to do something like clear the cache: `ccache -C`, etc. The other I'll call "compile mode", where you are asking `ccache` to help compile something, perhaps by retrieving from the cache, perhaps by invoking the compiler. Then there is also the "symlink mode", but I think that can be ignored for my purposes here as it is just a special form of "compile mode".

In "control mode", `ccache` is documented to take various command line options. But in "compile mode", it apparently cannot. I would like, as a new feature, for it to be possible to provide options to `ccache` in compile mode. My specific interest is for `-o key=value` pairs, because I would like a way to set options like `run_second_cpp` or `extra_files_to_hash` on the command line, rather than via an environment variable. Environment variables are harder for build systems to manage, and tend to act globally. I have some uses where I would like the value of the options I've mentioned here to vary contextually with the target being built. This is easier to do when I can simply have the build system generate a different command line flag based on attributes of the target or source.

I'd suggest allowing the syntax `ccache [options] -- compiler [compiler options]`, much like GDB allows separating options to GDB from options for the target.

It is true that there are several `ccache` options that don't make sense in compile mode, like `--clear` or `--show-stats`. I'm not sure what the best way to handle those would be. Maybe it makes sense to tag the various options and configuration settings as being relevant to only one or both of "control mode" and "compile mode", and then either erroring on or ignoring options values that only make sense in "control mode" when in "compile mode", and vice versa.

On a related note, it is not currently specified in the documentation under the `CONFIGURATION` section what priority options specified via `-o` take relative to other sources of configuration like environment variables or configuration files. It appears though that environment variables override the `-o` flags when used in "command mode":

```
$ ccache -o run_second_cpp=false -o extra_files_to_hash=/dev/null -k run_second_cpp -k extra_files_to_hash
false
/dev/null

$ CCACHE_CPP2=1 ccache -o run_second_cpp=false -o extra_files_to_hash=/dev/null -k run_second_cpp -k extra_files_to_hash
true
/dev/null
```

I think it would be a worthwhile improvement to document that the command line values for `-o` are overridden by the environment variables. I did not test how the interact w.r.t. the various configuration files. I also think it would be better if it were the other way, with the command line having the highest priority, but I expect that that would be something of a breaking change.

**Comment by jrosdahl** [comment]
Thanks for submitting the idea.

> I would like, as a new feature, for it to be possible to provide options to `ccache` in compile mode. [...] This is easier to do when I can simply have the build system generate a different command line flag based on attributes of the target or source.

If it's hard to set environment variables in a target-specific way with the build system, I guess the standard solution would be to invoke ccache with something like `env CCACHE_VAR=VALUE ccache ...`. But I understand the wish for a way to do this without relying on `env`, which also isn't portable.

> It is true that there are several `ccache` options that don't make sense in compile mode, like `--clear` or `--show-stats`. I'm not sure what the best way to handle those would be.

I don't think that it makes sense to allow any existing option in compile mode.

> On a related note, it is not currently specified in the documentation under the `CONFIGURATION` section what priority options specified via `-o` take relative to other sources of configuration like environment variables or configuration files. It appears though that environment variables override the `-o` flags when used in "command mode": [...] I think it would be a worthwhile improvement to document that the command line values for -o are overridden by the environment variables.

I would argue that it is documented. `-o`/`--set-config` (along with `-M`/`--max-size` and `-F`/`--max-files`) are control mode options that update the (cache-specific) configuration file. They are just convenience commands that you can use instead of editing the configuration file manually. Environment variables are documented to have higher priority than configuration files.

> I also think it would be better if it were the other way, with the command line having the highest priority, but I expect that that would be something of a breaking change.

Right. Since `-o` is for writing to the configuration file, it would mean that configuration files suddenly would have higher priority than environment variables, which isn't a change that it possible to make now.

> I'd suggest allowing the syntax `ccache [options] -- compiler [compiler options]`, much like GDB allows separating options to GDB from options for the target.

I don't see any specific mentioning of `--` in GDB's documentation, but `--` typically means "the options now end; interpret the next argument as an argument even if it looks like an option". (That seems to be how GDB behaves as well, so you can debug a program called `-h` by running `gdb -- -h`.)

How about this: In compile mode, let ccache consume all arguments that include an equal sign as configuration options until an argument without an equal sign is found, which is the compiler. For example:

```
ccache ignore_options="-fmessage-length*" debug=1 gcc -c test.c
```

That would be equivalent to 

```
env CCACHE_IGNORE_OPTIONS="-fmessage-length*" CCACHE_DEBUG=1 gcc -c test.c
```

so that configuration specified that way will have higher priority than environment variables.

(This assumes that nobody uses ccache with a compiler whose name contains an equal sign...)
