### ISSUE TITLE
limit_multiple for --cleanup

### ISSUE THREAD

**Issue by rdiez** [ccache/ccache#1097]
I am using ccache to speed up interactive builds, and I want to prevent the occasional pause due to automatic clean-ups. More information is here:

Long pauses due to automatic cache clean-up  
https://lists.samba.org/archive/ccache/2021q2/thread.html

I am still using the same disk, and I have verified that just traversing the cache directory with "du" takes 12 minutes, so it is a disk performance problem indeed.

I am now automatically running "ccache --cleanup" on start-up (while I am drinking my first coffee). My script specifies a lower CCACHE_MAXSIZE than in the config file. But it is a pain, because if I change the config file, it is easy to forget updating my start-up script.

I do not really want to implement the proposed solution of disabling automatic cleanup completely, and just rely on my start-up script, in case something goes wild during the day and ccache completely fills up the disk, creating havoc on the system. I am also too lazy to parse ccache's config file. ;-)

I recently learnt that there is an option called 'limit_multiple' which would definitely help, but it is not taken into account for manual cleanup (--cleanup). That sounds silly. Why would an automatic clean-up honour such a useful option, but not a manual clean-up?

It would be nice if that option, or a new one like 'limit_multiple_for_manual_cleanup', worked with --cleanup, so I do not have to parse and calculate anything.

**Comment by jrosdahl** [comment]
> That sounds silly. Why would an automatic clean-up honour such a useful option, but not a manual clean-up?

In fact, [the `limit_multiple` option was added](https://github.com/ccache/ccache/commit/a8ca6ad32c338cf145826e8091c5e3aeeb7f538a) because `ccache -c` **did** take the hardcoded "limit multiple" value into account so that you could run `CCACHE_LIMIT_MULTIPLE=1 ccache -c`. I later [fixed the `ccache -c` behavior](https://github.com/ccache/ccache/commit/7784c4228726a55cca043800ce45266d3301584d) since it was silly that it didn't work as documented (_"Clean up the cache by removing old cached files until the specified file number and cache size limits are not exceeded"_). Note that there are other reasons for calling `ccache -c` than to trim the cache, and then the user most likely doesn't want to discard parts of the cache when the cache size is within the configured limits.

I don't think that adding yet another configuration option for this is the way to go. I would rather spend the time on fixing the underlying problem, which primarily is that several ccache invocations can clean up the same part of the cache at once. See also #417.

>  I am also too lazy to parse ccache's config file. ;-)

Please just use `ccache -k max_size` like I suggested in the mailing list thread. Then calculating the wanted value should be more or less trivial.

**Comment by jrosdahl** [comment]
> The only reason to do a manual clean-up would then be to prevent performance hits due to automatic clean-ups at inconvenient times. Or am I missing something?

Yes, there are a couple of other use cases:

* The user wants to free up space *now* to make room for something else, calculates the wanted cache size X and runs `CCACHE_MAXSIZE=X ccache -c`.
* The user wants to recalculate the size and number of files counters to correspond to reality in case they have diverged. (Admittedly, this was more relevant before [this fix](https://github.com/ccache/ccache/commit/4fc191a554330079621f0c53c6d2023f1babd552).) Or, the user has deleted or added some parts of the cache manually and now wants the counters to be in sync without throwing away more than necessary of the cache.
* The user wants to remove temporary files that lie around in the cache without waiting for automatic cleanup to kick in. (Such files can be left over if ccache is SIGKILLed while copying a file to the cache.)

To me, the use case you describe seemed like an edge case; I would have thought that the absolute majority of users just use ccache's automatic cleanup or turn it off and run `ccache -c` at regular intervals.

It made sense to me to change the behavior with the knowledge I had of the use cases _and_ the fact that I want to improve the cleanup algorithm to keep the cache size much closer to the configured max limit – then letting `ccache -c` still remove one fifth of the cache wouldn't make sense to me. In other words, `limit_multiple` likely won't be relevant in the future and will be removed. 

I hope to be able to improve the automatic cleanup so that initiating manual cleanup won't be needed even for slow disks.

> The word "multiple" tends to be associated with "many", but in this case, you actually want values <= 1.0. I would have chosen "factor", "reduction factor" or something along that line.

The name was chosen by a contributor in a8ca6ad32c338cf145826e8091c5e3aeeb7f538a, based on the original internal constant name chosen by Tridge (the original ccache author). Complaining about what could have been done is not productive.

> [...] If you really want [...] should have been [...] not intuitive either [...] I find it troublesome [...] At the very least [...] should [...] Forcing your users to parse text to get some numeric values is not cool [...] unnecessarily painful

I don't appreciate rude language like this. I definitely don't force any user to do anything: users are free to use the source code I and others have created in our limited spare time for free, or stop using it, or make their own improvements based on the freely available code. Even if you are frustrated about something, please [be nice to open source maintainers](https://snarky.ca/the-social-contract-of-open-source/) anyway, lest they burn out and quit.

**Comment by jrosdahl** [comment]
`limit_multiple` was removed in defb83cc6641b7356c1426c0ba782ac735748917 and is thus no longer relevant.
