### ISSUE TITLE
Let hash_dir default to true

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#117]
Letting hash_dir default to true will result in a better out-of-the-box experience.

See also the discussion in #93.

**Comment by itensionanders** [comment]
Fedora has been running with hash_dir=true for quite some time, due to "problems" with debuginfo:

* http://pkgs.fedoraproject.org/cgit/rpms/ccache.git/commit/ccache.sh.in?id=98ad636d9da10cc3a5bddc84c7f316e7aca3db32
* https://bugzilla.redhat.com/show_bug.cgi?id=759592

Note that if you *are* using base_dir and `-g`, you can get better hits by using `-fdebug-prefix-map`
