### ISSUE TITLE
Support -Wp,-M[M]D with -o without -MMD, -MQ or -MT

### ISSUE THREAD

**Issue by paulorlyk** [ccache/ccache#1203]
### How to reproduce ###

1. Build Linux kernel with `$ make bindeb-pkg`
2. Run `ccache -sv`
3. Observe big number of `Uncacheable calls` due to `Unsupported compiler option`

ccache log file: [common.o.20221030_020921_786982.ccache-log](https://github.com/ccache/ccache/files/9894759/common.o.20221030_020921_786982.ccache-log.log)

### Actual behavior ###

After setting `CCACHE_DEBUG` environment variable it appears that ccache refuses to cache most of compiler calls due to:
```
[2022-10-30T02:09:21.787348 187264] -Wp,-M[M]D with -o without -MMD, -MQ or -MT is not supported
[2022-10-30T02:09:21.787357 187264] Failed; falling back to running the real compiler
```
This significantly lowers ccache effectiveness in current use case.

### Expected behavior ###

It would be nice if ccache could handle this situation similar to how it was in version 4.6.2

### Environment ###

ccache version 4.7.2

**Comment by jrosdahl** [comment]
Thanks for the bug report. Since ccache works as intended, I'll convert the issue to a feature request to support this case.

For those who are interested, the background why ccache 4.7 made the change to not support "`-Wp,-M[M]D` with `-o` without `-MMD`, `-MQ` or `-MT`" is that ccache now can share cache entries when using different `-MT`/`-MQ` options (#359). It does this by generating the dependency target in the dependency file instead of just caching the full dependency file as is. The thing is that GCC and Clang behave differently for this case: GCC uses a dependency target based on the source filename but Clang bases it on the output filename. Therefore it was easiest to just [not support the case for now](https://github.com/ccache/ccache/blob/98a04d7c881859910080619ba926eb74988c8c74/src/argprocessing.cpp#L1156-L1165).

**Comment by c0d3z3r0** [comment]
any chance this could be made optional? e.g. a config option for disabling would be great. (I tried to simply revert that change, but turns out that's not easy)

**Comment by jrosdahl** [comment]
> any chance this could be made optional? e.g. a config option for disabling would be great. (I tried to simply revert that change, but turns out that's not easy)

Why would you like to be able to disable support for something?

**Comment by c0d3z3r0** [comment]
> > any chance this could be made optional? e.g. a config option for disabling would be great. (I tried to simply revert that change, but turns out that's not easy)
> 
> Why would you like to be able to disable support for something?

To be able to use ccache for kernel compilation again

**Comment by jrosdahl** [comment]
I don't understand. The issue you're commenting on is about adding support for "`-Wp,-M[M]D` with `-o` without `-MMD`, `-MQ` or `-MT`", which was done in 84c58a57e020174d0d4098a620cba03c3c0284c6. If it were possible to disable that support then ccache would support _less_ things, not more.

So it sounds like you're talking about something else, but I'm not sure what. I think it would be better if you open a new bug report if you're seeing some problem.

**Comment by c0d3z3r0** [comment]
Oh, nevermind. When I first read this issue yesterday (it was late ;) I misread this as 'the new feature lead  to less hits'. I just verified that ccache does actually work as expected on a clean Debian live system, so I need to debug what's wrong on my main system. Sorry for the noise!
