### ISSUE TITLE
Inode cache race condition

### ISSUE THREAD

**Issue by lancethepants** [ccache/ccache#1215]
### How to reproduce ###

1.  Compile perl/python native for system (Debian)
2. Cross-compile perl/python for aarch64/musl
3. Get some weird errors

### Actual behavior ###

I use ccache to speed up compilation for a [project](https://github.com/lancethepants/tomatoware) of mine. When I upgraded to 4.7.x I started getting some anomalous errors, like cross-compiling perl I would get
`fatal error: <sys/security.h> no such file or directory.`

Also some issues when cross-compiling python. As part of cross-compiling these languages in particular I first build a native version that aids in bootstrapping the cross-compilation.
So I think that somehow ccache, probably when running `./configure` in particular  when cross-compiling is getting cache hits from the native compilation cache.  It doesn't happen every time either, though it is most of the time it seems.

I've tried clearing the cache and starting fresh but the issue persists.  
If I downgrade to ccache 4.6.3, or if I just don't use ccache then the error doesn't happen.

My project compiles for several architectures, but this occurs when cross-compiling for aarch64/musl.

### Expected behavior ###

No errors that result from using ccache 4.7.x

### Environment ###

ccache version 4.7.1-4.7.3 I have tested

**Comment by jrosdahl** [comment]
Thanks for the bug report.

> 1. Compile perl/python native for system (Debian)
> 2. Cross-compile perl/python for aarch64/musl
> 3. Get some weird errors

Can you give me more detailed reproduction instructions? Which actual commands should I run to reproduce the problem?

**Comment by lancethepants** [comment]
So I've created a sort-of minimal way to reproduce this based off my project. I tested this in a new Debian 10 VM.

1. Create Debian 10 test VM.
2. Install packages found in README. https://github.com/lancethepants/tomatoware
3. Give user account sudo access. (All sudo does is to create the /opt/tomatoware directory), or optionally just create it with 777 permission using root user.
4. git clone https://github.com/lancethepants/tomatoware
5. cd tomatoware && git checkout ccache
6. make (not as root!)

This will compile the cross-toolchain, ninja, cmake, ccache, host perl, then cross perl.
debian 10 cmake is now too old to compile ccache 4.7.x

The first time you run make you'll probably see.
`fatal error: sys/mode.h: No such file or directory`
This doesn't happen with 4.6.3.
At this point it compiled the host perl and should be cross-compiling perl,

you can then run `rm src/perl/.extracted` to rebuild host perl, try running `make` and you then might see. (Not always super predictable)
`fatal error: sys/security.h: No such file or directory` 
Now compiling the host perl, it seems like the cross-perl cache is interfering with the native perl.

Sorry the repo is really big right now. I rebase it from time to time to shrink the size. And also building the toolchain will take a good minute.
ccache saves me tons of build time!

**Comment by jrosdahl** [comment]
Thanks.

I followed your steps in a fresh `debian:10` Docker container. At first I thought I had reproduced the problem since the build failed, but then I noticed that there's an `exit 1` in `scripts/base.sh` that makes it fail...

I get no `fatal error` in the build log, neither from the first step nor from the rebuild after removing `src/perl/.extracted`. Tried twice.

What is it, more exactly, that says `fatal error: sys/something.h: No such file or directory`? Does the error show up if you do a serial build?

Any way you can minimize the reproduction recipe would be valuable.

> debian 10 cmake is now too old to compile ccache 4.7.x

There's a new enough version in [buster-backports](https://backports.debian.org) if you like to use that package source.

**Comment by jrosdahl** [comment]
One thing that would be of interest is if you could try to build with `CCACHE_NOINODECACHE=1` and see if that changes anything.

**Comment by lancethepants** [comment]
So I'm not able replicate my problem on bare-metal or in a docker container.  I was actually surprised to see my nightly builds which utilize docker were successful. The issue right now seems to be with 4.7.x series while running in a vm (virtualbox), which is where I do development.  I've reran many times with 4.6.3 in a vm but could not get the error to manifest.
So really weird. I'd almost point fingers at the vm, but it works without issue with version 4.6.3. 

I did create this little script which is much quicker and lighter. I just downloads and extracts the pre-compiled toolchain, and downloads and compiles perl. It also builds with using a single thread, no parallel.
https://gist.github.com/lancethepants/608b26c1e3718ed80d36a8d5b228123b

Saw you just posted so I will take a look into that as well.

**Comment by lancethepants** [comment]
So I tried with setting `CCACHE_NOINODECACHE=1` and the issue no longer occurs in virtualbox. I see this that `CCACHE_INODECACHE` was enabled by default in ccache 4.7.0. Definitely some interaction with this setting and virtualbox. I'm now beginning to think this is an issue with the virtualbox filesystem handling. I remember back in the day virtualbox had an issue with not respecting fsyncs to disk.
https://www.phoronix.com/review/ubuntu-1510-virt/2
While I think this issue was fixed I wonder if there's some non-conformance on the part of virtualbox. Anyway you can check/test this, or should I just report this to them do you think?

**Comment by jrosdahl** [comment]
Thanks for the simplified script! I'm now able to reproduce the problem in a VirtualBox environment after enabling ccache for host compilers as well.

I'll look into it more deeply when time permits.

**Comment by jrosdahl** [comment]
I've found the problem. It's an inode cache race condition related to file system timestamp granularity, or rather how often the system clock that the timestamps are based on is updated. I don't know why the issue shows up more often in a VirtualBox environment, but it's easy to reproduce it on a regular Linux system as well like this:

```bash
#!/bin/bash

while true; do
    echo '#include <sys/resource.h>' >try.c
    if ! ccache gcc -c try.c 2>/dev/null; then
        echo "Unexpected failure for #include <sys/resource.h>" >&2
        exit 1
    fi
    echo '#include <sys/security.h>' >try.c
    if ccache gcc -c try.c 2>/dev/null; then
        echo "Unexpected success for #include <sys/security.h>" >&2
        exit 1
    fi
done
```

To trigger the problem, one has to (1) make ccache read a recently written file (try.c above), (2) quickly enough write to the file in-place with new content that has the same size as before, and (3) make ccache read the file again. If the two writes to the file happen fast enough so that the file system timestamp granularity makes the timestamps identical, then the inode cache will be fooled.
