### ISSUE TITLE
Remote cache: throw error if remote cannot be written to

### ISSUE THREAD

**Issue by z-aki** [ccache/ccache#1282]
### How to reproduce ###

I saw this on remote file sharing setup over LAN but probably can be done locally too

1. Setup a folder with no write access and set it as remote_cache
2. remote_only = true
3. run ccache and see it not complain about it

### Actual behavior ###

ccache doesn't report error

if remote_only = false, then it writes to primary cache

### Expected behavior ###

at least throw warning

### Environment ###

ccache version 4.8

**Comment by jrosdahl** [comment]
Hi,

Thanks for the bug report.

This is not a bug but intended behavior. Ccache can't print warnings and still exit with error code 0 since that would produce something different than executing the compiler without ccache. Ccache _could_ print an error and exit with a non-zero error code, but that would be too annoying in the general case. For instance, if the remote file directory intermittently is unreachable (e.g. due to flaky network or configuration changes), then we don't want to fail the build.

However, ccache does keep track of remote storage errors in a statistics counter, and it also prints errors to the [log file](https://ccache.dev/manual/4.8.html#config_log_file) (if enabled). To check the statistics counters, run `ccache -s` and you'll see something like this at the end:

```
Remote storage:
  Hits:              8 / 10 (80.00%)
  Misses:            2 / 10 (20.00%)
  Errors:           42
```
