### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by cctv130** [ccache/ccache#1316]
Thank you very much for this project, I have done front-end development for a period of time, there is an open source project is webpack front-end packaging tool, some algorithms in this tool may be helpful to this project, If the function-level cache can be implemented using windows PE structure or linux ELF structure to update the generated objects indirectly at compile time, the c++ compilation speed can be accelerated faster

**Comment by jrosdahl** [comment]
Thanks for your interest in ccache.

I don't understand your idea. Please describe your proposal in more details and how it would work.

**Comment by akrieger** [comment]
If I'm understanding correctly, the request is to cache individual COMDATs / function sections instead of entire object files. I don't think that's feasible for ccache whose role is to operate outside of the compiler without semantic understanding of the source code.

There are other projects that use function section trickery to make updates faster, but it operates on a fixed set of sources and not arbitrary data. Eg. checking out different llvm binaries quickly by indexing objects and function sections for every llvm commit, and storing them individually, then 'diffing' the binary by inserting or removing code based on that.
