### ISSUE TITLE
ccache corruption when source is changed during compilation

### ISSUE THREAD

**Issue by oded-ist** [ccache/ccache#1378]
### How to reproduce ###

1. Use the following compiler wrapper script (CCACHE_PREFIX):
```
#!/bin/bash
sleep 3
( exec "$@" )
```
2. Use CCACHE_DEPEND=1 (this bug also exists in preprocess mode, but differently)
3. Compile a file.c with contents `A`
4. During "compilation", meaning, during the `sleep 3`, modify the source file to contents `B`

### Actual behavior ###
If the source started out as A, and was changed to B during the `sleep` - then the result object will be B, but will be stored in cache as the result for A.

When recompiling A (the original source), you will get B as a result.

### Expected behavior ###
ccache actually has a fix exactly for this - but only for the include files!

Here's a patch which does the same for the source file:
[0001-fix-prevent-caching-object-if-source-file-is-modifie.txt](https://github.com/ccache/ccache/files/13853933/0001-fix-prevent-caching-object-if-source-file-is-modifie.txt)

### Environment ###

ccache version 4.9.0

**Comment by jrosdahl** [comment]
Thanks for the bug report.

Yes, this is an inherent race condition when reading the source code to form the input hash, then executing the compiler on the source code, and then storing the result in an entry associated with the input hash. Checking the source code file timestamp like you suggest will improve things, but the same issue still remains for changes to any of the include files. I'll see if I can make some reasonable fix.

For background, the `include_file_too_new` check and the `include_file_[cm]time` "sloppiness" values originate from when ccache had `run_second_cpp = false` as the default (that is: before ccache 3.3) since the compiler then is given the preprocessed output to compile instead of the actual source code files and there is no race condition for the preprocessor mode.
