### ISSUE TITLE
Build with system libraries

### ISSUE THREAD

**Issue by opoplawski** [ccache/ccache#1396]
Somehow I'm just discovering the ccache bundles a lot of libraries.  Fedora packaging guidelines discourage this and strongly suggest that packages build with the system versions of libraries if possible.  At the moment ccache does not allow for this.  Would you be receptive to patches that would make this easier?

**Comment by jrosdahl** [comment]
Sure, that would be welcome.

**Comment by jrosdahl** [comment]
Current state of dependencies:

- hiredis and zstd (two of the more recently added dependencies) are already not bundled but are possible to download if they aren't available in the system.
- Other dependencies are bundled, sometimes just a subset.

Taking a step back, I think that there are three scenarios to consider:

1. An end-user who just want to build ccache with minimal fuss, using whatever is installed in the system and downloading the rest. This is currently the default.
2. An end-user who wants to build statically with recommended dependency versions, i.e. typically downloading everything. Potentially in combination with `-D STATIC_LINK=ON`.
3. A distributor who wants to never download anything and also use as many dependencies as possible from system packages. The most interesting consideration here is perhaps which dependencies are reasonable to take from the system instead of bundling.

Given this I'm considering a generic CMake option that indicates what is wanted, very similar to the existing `{HIREDIS,ZSTD}_FROM_INTERNET` variables. Maybe something like this?

1. `DEPS=AUTO`: Similar to the current defaults: Take what's available on the system (or bundled) and download the rest. Obsoletes the `{HIREDIS,ZSTD}_FROM_INTERNET` variables.
2. `DEPS=DOWNLOAD`: Download all non-bundled dependencies and set up static linking to downloaded parts.
3. `DEPS=SYSTEM`: Never download anything. Obsoletes the `OFFLINE=ON` option (#1341). Typically used by distributors. Open question: What to do about dependencies that still will be bundled?

@opoplawski: Does this sound reasonable to you?

Here's my current thoughts about what to do for each dependency:

| *Dependency* | *Bundle?*                                       |
|--------------|----------------------------------------------------|
| blake3       | Keep bundled for now?[^1]                          |
| doctest      | Don't bundle[^2] (ubiquitous enough)               |
| fmt          | Remove after bumping compiler requirement to C++20 |
| getopt_long  | Remove (hopefully not needed)                      |
| hiredis      | Already not bundled                                |
| httplib      | Not sure[^3]                                       |
| minitrace    | Remove (including ccache functionality using it)   |
| nonstd/span  | Remove after bumping compiler requirement to C++20 |
| tl/expected  | Not sure[^3]                                       |
| url          | Keep bundled (typically not packaged)              |
| win32/getopt | Keep bundled                                       |
| xxhash       | Don't bundle[^2] (ubiquitous enough)               |
| zstd         | Already not bundled                                |

[^1]: Not packaged by many. There is also a complication: we would need to figure out what to do with our own modification, see `src/third_party/blake3/blake3_dispatch_ccache.c`.
[^2]: But add support for downloading and building, similar to how it's done for hiredis and zstd.
[^3]: Packaged by e.g. Debian and Fedora, but is it ubiquitous enough? In any case, add support for using it from system (if `DEPS=SYSTEM`).

Before going forward on this I would also like to restructure the source code tree a bit in preparation. I'll write a note here when I'm ready.

**Comment by opoplawski** [comment]
I'm not going to speak to the other use cases, but as a distribution packager - yes we want to build as much as possible with system provided libraries.  Your DEPS=SYSTEM option seems reasonable for that.

I think I agree with all of your individual dep assessments as well.  Thank you!

**Comment by jrosdahl** [comment]
After looking a bit more at compiler compatibility, bumping to C++20 is unfortunately out of the question for now since that would require GCC 13 for `std::format`.

New bid:


| *Dependency* | *Bundle?*                                          |
|--------------|----------------------------------------------------|
| blake3       | Keep bundled for now?[^1]                          |
| doctest      | Don't bundle[^2] (ubiquitous enough)               |
| fmt          | Don't bundle[^2] (ubiquitous enough)               |
| getopt_long  | Remove (hopefully not needed)                      |
| hiredis      | Already not bundled                                |
| httplib      | Not sure[^3]                                       |
| minitrace    | Remove (including ccache functionality using it)   |
| nonstd/span  | Keep bundled (typically not packaged) |
| tl/expected  | Not sure[^3]                                       |
| url          | Keep bundled (typically not packaged)              |
| win32/getopt | Keep bundled                                       |
| xxhash       | Don't bundle[^2] (ubiquitous enough)               |
| zstd         | Already not bundled                                |

[^1]: Not packaged by many. There is also a complication: we would need to figure out what to do with our own modification, see `src/third_party/blake3/blake3_dispatch_ccache.c`.
[^2]: But add support for downloading and building, similar to how it's done for hiredis and zstd.
[^3]: Packaged by e.g. Debian and Fedora, but is it ubiquitous enough? In any case, add support for using it from system (if `DEPS=SYSTEM`).

**Comment by jrosdahl** [comment]
I'm working on this now. I plan to address all dependencies if that's OK with you, @opoplawski.

**Comment by opoplawski** [comment]
That sounds great - thanks!

**Comment by jrosdahl** [comment]
Done now: #1429. I chose `DEPS=LOCAL` instead of `DEPS=SYSTEM`. Also, I also made it possible to use blake3 from the system. 

@opoplawski: Are you happy with my suggestion in #1429?
