### ISSUE TITLE
Windows 11: filesystem error: Cannot convert character sequence: Illegal byte sequence

### ISSUE THREAD

**Issue by zbrkic** [ccache/ccache#1409]
### How to reproduce ###

1. ccache.exe -h
2. ccache.exe --version

### Actual behavior ###
```
C:\Util>ccache.exe --version
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence

C:\Util>ccache.exe -h
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence

```

### Expected behavior ###
Display version, display help.

### Environment ###
ccache-4.9.1-windows-x86_64

ccache version 4.9.1

Windows 11, x64 Native Tools Command Prompt for VS 2022, powershell

**Comment by jrosdahl** [comment]
@rkitover: Any ideas?

**Comment by zbrkic** [comment]
From EventLog:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2024-03-01T20:29:54.8104382Z" /> 
  <EventRecordID>19594</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="9900" ThreadID="10012" /> 
  <Channel>Application</Channel> 
  <Computer>ZeljkoPC</Computer> 
  <Security UserID="S-1-5-21-2941797710-3171089060-2177592001-1001" /> 
  </System>
<EventData>
  <Data Name="AppName">ccache.exe</Data> 
  <Data Name="AppVersion">0.0.0.0</Data> 
  <Data Name="AppTimeStamp">65c1378c</Data> 
  <Data Name="ModuleName">ccache.exe</Data> 
  <Data Name="ModuleVersion">0.0.0.0</Data> 
  <Data Name="ModuleTimeStamp">65c1378c</Data> 
  <Data Name="ExceptionCode">40000015</Data> 
  <Data Name="FaultingOffset">000000000022eba6</Data> 
  <Data Name="ProcessId">0x1700</Data> 
  <Data Name="ProcessCreationTime">0x1da6c17386a3e75</Data> 
  <Data Name="AppPath">D:\Projects\ccache-4.9.1-windows-x86_64\ccache.exe</Data> 
  <Data Name="ModulePath">D:\Projects\ccache-4.9.1-windows-x86_64\ccache.exe</Data> 
  <Data Name="IntegratorReportId">4ce71272-0ae3-4fce-945c-36321174c88e</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>

**Comment by rkitover** [comment]
My guess is it's trying to read something in the profile directory and not liking it. I have to see which initialization code paths are active in these invocations.

**Comment by zbrkic** [comment]
I have a letter _Ž_ in profile path. Could that be a problem?

**Comment by rkitover** [comment]
Is your `$env:USERPROFILE` in UTF8 or UTF16? If you put `%USERPROFILE%` in explorer does it work correctly?

**Comment by zbrkic** [comment]
How can I check if $env:USERPROFILE in UTF8 or UTF16? %USERPROFILE% in explorer works. I can start ccache, usage if printed. But if I start it with any argument then I get an error.

**Comment by rkitover** [comment]
Can you run:

```powershell
$env:USERPROFILE | format-hex
```
, in powershell and post the output here please?

**Comment by cristianadam** [comment]
What happens if you enable `utf-8` to your locale?
<img width="872" alt="Screenshot 2024-03-06 at 17 51 36" src="https://github.com/ccache/ccache/assets/1257414/f828df27-dde1-477f-89f9-49290a222e8e">

**Comment by zbrkic** [comment]
```
PS D:\Projects\ccache-4.9.1-windows-x86_64> $env:USERPROFILE | format-hex


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   43 3A 5C 55 73 65 72 73 5C 3F 65 6C 6A 6B 6F     C:\Users\?eljko
```

**Comment by zbrkic** [comment]
After changing Regional Settings to use UTF 8 **it works**:
```
PS D:\Projects\ccache-4.9.1-windows-x86_64> $env:USERPROFILE | format-hex


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   43 3A 5C 55 73 65 72 73 5C 3F 65 6C 6A 6B 6F     C:\Users\?eljko


PS D:\Projects\ccache-4.9.1-windows-x86_64> .\ccache.exe -V
ccache version 4.9.1
Features: file-storage http-storage redis+unix-storage redis-storage

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2024 Joel Rosdahl and other contributors

See <https://ccache.dev/credits.html> for a complete list of contributors.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.
PS D:\Projects\ccache-4.9.1-windows-x86_64>
```

**Comment by rkitover** [comment]
So if I'm understanding this correctly, your `$env:USERPROFILE` was encoded as UTF-8 both before and after you set your regional settings to UTF-8?

From this we can deduce that Windows always encodes the environment variables as UTF-8 and we should decode them **from** UTF-8 when we are reading them from the environment.

Does that sound right?

**Comment by zbrkic** [comment]
Yes, there was no difference in `$env:USERPROFILE` before and after changing regional settings.

**Comment by zbrkic** [comment]
UFT-8 should use 2 bytes for Ž, but it seems that Windows or PS just uses ? instead:
```
PS C:\Users\Željko> 'C:\Users\Željko' | format-hex


           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   43 3A 5C 55 73 65 72 73 5C 3F 65 6C 6A 6B 6F     C:\Users\?eljko


PS C:\Users\Željko> [System.Text.Encoding]::UTF8.GetBytes('C:\Users\Željko') | format-hex


           Path:

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   43 3A 5C 55 73 65 72 73 5C C5 BD 65 6C 6A 6B 6F  C:\Users\Å½eljko
```

**Comment by rkitover** [comment]
@Alcaro I actually made a wrapper function using `std::filesystem` last time I was working on a Windows issue. I suspect those classes will have no problems with `std::wstring` and similar. I will make a local user on my Windows installation with a character from some European charset and play with this, adding whatever wrapper functions and C++ magic is necessary to get all this to work. Does that sound like the way to go?

**Comment by Alcaro** [comment]
There are many reasonable approaches.

That is one of them, yes.

Make sure to test using some character that is not in your chosen charset, those are the ones most likely to cause trouble. あ or ☃, for example.

**Comment by josesimoes** [comment]
Hey! Any idea if this issue is being worked out? This is a serious blocker for using ccache... 😞

**Comment by rkitover** [comment]
Sorry, I was meaning to take care of this, I'll try to do that over the next couple of weeks.

**Comment by jrosdahl** [comment]
Would using something like `SHGetFolderPath` instead of reading an environment variable improve things?

**Comment by rkitover** [comment]
Maybe, I'll make a Windows user named Mr. John Poo Emoji with some unicode code points and spaces and see what will work, might just need some C++ type magic.

**Comment by rkitover** [comment]
Unfortunately I can't fix this right now, the US government authorities are preventing me from even compiling my changes, or testing anything. I started working on this in the `windows-env-paths` branch in my fork.

**Comment by jrosdahl** [comment]
@rkitover: OK, thanks for working on this. Hoping that you can find some way to continue eventually.

Here's my current understanding of what happens:

1. `Config::read` calls `home_directory()` which calls `getenv("USERPROFILE")` and converts the `char*` to a `std:string`.
2. `Config::read` converts the `std::string` to a `std::filesystem::path` (this is new in ccache 4.9+). `std::filesystem::path`'s constructor is then unhappy with the argument and throws.

Does that  sound right?

Before ccache 4.9 the string from `getenv` would be passed as is to functions like `CreateFileA` on Windows. What I don't quite understand is if this worked before 4.9 or if it was just silently broken? If it was not silently broken, how is the UTF-16 string encoded in `getenv`'s return value and how can `CreateFileA` make sense of it?

**Comment by rkitover** [comment]
So I was working on what I believe is the correct solution for this, but I'm being prevented from even using the compiler to fix the compile errors so I can't finish it right now, it's here:

https://github.com/rkitover/ccache/tree/windows-env-paths

. What I am doing there is using `char16_t` for any paths coming from environment variables on Windows. This requires changing some of the string functions and classes to templates on `CharT` with aliases to `char` for normal usage. I believe I could finish it if I could compile it.

But anyway, since I can't finish the correct solution I will give you the incorrect solution, which may in fact work in all cases. There may be cases where it does not work, that I don't know. But it worked with uncle Mr. John Poo Emoji, a valued member of my Microsoft 365 Family, and emojis are an excellent test of Unicode, since they are outside the 16 bit character sets and require a full 32 bit code point.

The problem here is that `std::filesystem::path` has to do character/string operations on the string it is constructed with, especially if you call methods like `lexically_normal()` which we are doing.

I don't know what the non-wide Windows stdlib function `getenv()` returns here, because I can't test it, but apparently `std::filesystem::path` cannot do character/string operations on it and throws.

So what we are going to do for now, and I will need you to finish this because I'm being prevented from doing that right now, is use the wide character version of `getenv()` `_wgetenv()` and convert it to UTF-8 using a Win32 API.

. In `environment.hpp` put this signature and override:

```cpp
const std::string win32_getenv(const char*);

#ifdef _WIN32
#define getenv win32_getenv
#endif
```

Unfortunately the signature cannot be `const char*` without leaking memory, so you will need to make some changes downstream like using `auto`. Sorry about that.

In `environment.cpp` put this in the header block:

```cpp
#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stringapiset.h>
#endif
```

, and add the function implementation:

```cpp
const std::string
win32_getenv(const char* env_var)
{
  size_t env_var_len = std::strlen(env_var) + 1;

  wchar_t* env_var_wide = new wchar_t[env_var_len];

  std::mbstowcs(env_var_wide, env_var, env_var_len);

  wchar_t* utf16_val = _wgetenv(env_var_wide);

  delete[] env_var_wide;

  size_t size = WideCharToMultiByte(CP_UTF8, 0, utf16_val, -1, NULL, 0, NULL, NULL) + 1;

  char* utf8_val = new char[size];

  WideCharToMultiByte(CP_UTF8, 0, utf16_val, -1, utf8_val, size, NULL, NULL);

  std::string val(utf8_val);

  delete[] utf8_val;

  return val;
}
```

. Make sure `environment.hpp` is included everywhere `getenv()` is used for values with paths, including `PATH`. This is important because the user may have directories under their profile directory in their `PATH`.

Now, as to the reason why this solution is incorrect.

C++17 does not support UTF-8, at all. That this works is accidental. I can't even be sure it will always work, but it may.

C++20 does support UTF-8, and has the `std::u8string` type, which its version of `std::filesystem::path` is guaranteed to parse correctly.

To do this for C++20 would still require some changes similar to what I was working on. It may be OK to increase our standard level since it has already been like 5 years.

We might even consider changing all of our `std::string` usage to `std::u8string`. If we do that we have to make sure there is no code that iterates over `char*`, but I don't think there is.

**Comment by rkitover** [comment]
Please add these references to the comments for the function:

https://stackoverflow.com/a/57134966/262458

https://stackoverflow.com/a/2573845/262458

**Comment by rkitover** [comment]
I should mention, and you are probably aware, that `std::filesystem::path` can construct from `char*` or any std string.

**Comment by jrosdahl** [comment]
Thanks again, @rkitover.

Instead of converting `wchar_t[]` to `char[]` and pass that into `std::filesystem::path(std::string)` it seems better to go directly from `wchar_t[]` to `std::filesystem::path(std::wstring)`. I added some helpers for this in b1ef9e1e601091f883e8bfde0804cf8e7d4681f4 and will push a commit shortly that hopefully fixes this issue.

Requiring C++20 is unfortunately not yet possible for some platforms that I still want to support.

**Comment by hayschan** [comment]
> What happens if you enable `utf-8` to your locale? <img alt="Screenshot 2024-03-06 at 17 51 36" width="872" src="https://private-user-images.githubusercontent.com/1257414/310584950-f828df27-dde1-477f-89f9-49290a222e8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM2NjczNTcsIm5iZiI6MTc0MzY2NzA1NywicGF0aCI6Ii8xMjU3NDE0LzMxMDU4NDk1MC1mODI4ZGYyNy1kZGUxLTQ3N2YtODlmOS00OTI5MGEyMjJlOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MDNUMDc1NzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZkOGRjYTQyMTNmODRiNTJiMzJlZjQ3MTBmZDM4ODJlN2QwOWYwNjlmOTRlYjE4OGY2ZWIwMGEwZGE3ZmYyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FIND4iMAThUCSv98rYtGgI1yNMSpPjSdBqpMwIZcuVo">

Thanks so much. It works.
