### ISSUE TITLE
Offline build with fmt is complicated in 4.10

### ISSUE THREAD

**Issue by xkszltl** [ccache/ccache#1470]
Recent change dropped the bundled fmt and download during cmake config:
- https://github.com/ccache/ccache/commit/29c2e07993132585813b5fb5fab849f39e8b6863#diff-12e8125164bbfc7556b1781a8ed516e333cc0bf058acb7197f7415be44606c72

This won't work in offline build, with unreliable internet access, or when snapshot is needed for packaging.
We'd like to have a way to get all files ready before the build, not during the build.

How about:
- Simply use a submodule.
- If someone hate submodule for whatever reason, have dedicated place in repo for user to download fmt into, i.e. a manual version of submodule.

**Comment by xkszltl** [comment]
For other libs, I would be OK with pre-install them in system.
But fmt is special.
At this point different libs have different version requirement on that and it can also be somewhat conflicting with new STL.
So not a good idea to build and install system-wide.

**Comment by jrosdahl** [comment]
I think that this is neither broken nor a bug (it's an intentional change after all), but I do understand that not bundling dependencies can make things more complicated. Relabeling as such.

**Comment by jrosdahl** [comment]
The main reason for not using submodules is not because "someone hates them" but because it's the source code release archive that is the primary deliverable, not the Git repository. There is also no such thing as "simply use a submodule" since we still need to support using dependencies from other sources when Git is not involved, so support for prefetched source code (via Git or manually) would be an _additional_ method, not a replacement. Also note that you don't have to install fmt system-wide to compile against it – you can install it in any other location and set CMake variables `FMT_INCLUDE_DIR` and `FMT_LIBRARY` to that location.

That being said, I'll re-add the bundled fmt subset in ccache 4.10.1 for convenience.

**Comment by xkszltl** [comment]
@jrosdahl 
Thanks.
The "someone hates them" part is just because I've seen that happened in other project as reason of similar change.

> since we still need to support using dependencies from other sources when Git is not involved

I agree with that, and in that case non-git ref (e.g. url) can be used, but I would still suggest to keep a clear separation between download and build, so that things can still be built offline or in isolation.

> would be an additional method, not a replacement

That would be great.
My suggestion is more like "for git part, 2 methods can be unified for simplicity".

> Also note that you don't have to install fmt system-wide to compile against it – you can install it in any other location and set CMake variables FMT_INCLUDE_DIR and FMT_LIBRARY to that location.

This can be tricky because:
- it may accidentally pick up the wrong version from system.
- if the lib part contains .so, need to install together with ccache to the system or hardcode some rpath.
Neither would be ideal, especially when packaging.

**Comment by xkszltl** [comment]
> it's the source code release archive that is the primary deliverable, not the Git repository

Depends.
Yes, some project does use that workflow, but most projects I've seen on GitHub uses tagging, and the release is just a tarball of that tag.

In the case of fmt, the only difference seems to be the manually released zip has pre-built doc.

**Comment by xkszltl** [comment]
And a little bit more context regarding offline build:
- Some company have network isolation policy for automated builds as a security requirement.
- When build in China, https access to github is partially blocked.
- GitHub http server may not be accessible when staging through other git hosting system.
So downloading during build is not just insecure, but actually an immediate blocking issue.

**Comment by jrosdahl** [comment]
@xkszltl wrote:
>> Also note that you don't have to install fmt system-wide to compile against it – you can install it in any other location and set CMake variables FMT_INCLUDE_DIR and FMT_LIBRARY to that location.
>
> * it may accidentally pick up the wrong version from system.

No.

> * if the lib part contains .so, need to install together with ccache to the system or hardcode some rpath.

Fmt defaults to build a static library, so that's not something to be concerned about.

> Depends. Yes, some project does use that workflow, but most projects I've seen on GitHub uses tagging, and the release is just a tarball of that tag.

Perhaps I was unclear. I was talking about ccache and its deliverables, so it does not depend. It's the source code release archive that is the primary deliverable _for ccache_, so it can't depend on using Git submodules to fetch dependencies. Therefore another mechanism is needed (if we want to provide such a convenience at all), and I don't want to maintain two different ways to download dependencies, which is why I choose not to add Git submodules.

> So downloading during build is not just insecure, but actually an immediate blocking issue.

The fallback to trying to download is just a convenience for users who have not configured dependencies correctly according to the installation instructions. There is no need to download anything during build. I suggest enabling [FETCHCONTENT_FULLY_DISCONNECTED](https://cmake.org/cmake/help/latest/module/FetchContent.html#variable:FETCHCONTENT_FULLY_DISCONNECTED) or build with [`-D DEPS=LOCAL`](https://github.com/ccache/ccache/blob/master/doc/INSTALL.md#how-to-locate-or-retrieve). Then the build will never try to download missing dependencies and you'll then be aware which dependencies are missing.
