### ISSUE TITLE
TrackFileAccess=false no longer needed for Visual Studio

### ISSUE THREAD

**Issue by wheybags** [ccache/ccache#1484]
### Summary ###
The docs page on [using ccache with MSVC](https://github.com/ccache/ccache/wiki/MS-Visual-Studio) recommends using TrackFileAccess=false. This comes with significant downsides, and I believe it is no longer necessary, so the docs should be updated to reflect that.

### Details ###
The docs page shows that you must disable [TrackFileAccess](https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.generateresource.trackfileaccess?view=msbuild-17-netcore). This is done because MSBuild would delete files created by ccache (some explanation in the contect of clcache [here](https://github.com/frerich/clcache/wiki/Caveats)).

The problem is TrackFileAccess disables incremental builds, which is annoying. I tried out a simple project with VS2022 today, and it seems like this issue is no longer a problem - my files don't get deleted, even when I remove TrackFileAccess=false. I cleared my cache, then repeatedly built and cleaned the solution, and I could see cache hits coming in every time after the first build. Here's a link to [exactly what I tested with](https://gist.github.com/wheybags/de4daa28d5b663e110cd5e6999c1b3e6). I also dumped a file list from my ccache folder before and after cleaning the solution and there were no files deleted. I have no custom configuration, and my ccache directory is the default of %LOCALAPPDATA%\\ccache.

This behaviour might depend on the versions of msbuild/vs/ccache used, in which case the documentation should make that clear.

**Comment by jrosdahl** [comment]
Thanks for the notice!

How to optimally use ccache with Visual Studio indeed seems to change over time. That's why the information is on a wiki page and not tracked along with the ccache source code. The wiki page is intended to be collaboratively improved by Windows users, so it would be great if you'd like to update it with your suggestions.

As for `TrackFileAccess=false`, that was originally added by @cristianadam [here](https://github.com/ccache/ccache/wiki/MS-Visual-Studio/_compare/cfd66a501f39ab7db907d8dc303d117a0e7f7870...edfa390b17134f4ec84a175221357355c7f20efd) and later expanded by @congzhangzh [here](https://github.com/ccache/ccache/wiki/MS-Visual-Studio/_compare/1807ee8b403c2543a57e12e475dddd684defd1ac...140f8ec811f2cd7dbcff858097f7c8d9f9309d18). @cristianadam & @congzhangzh: Any comments or insights here?

**Comment by jbrownsw** [comment]
I mentioned the same thing here:
https://github.com/ccache/ccache/discussions/1355

**Comment by jrosdahl** [comment]
Since @cristianadam and @congzhangzh didn't reply to my ping above, I'd say that we should go ahead and update the wiki page. @jbrownsw or @wheybags: Would you like to do that?

**Comment by jrosdahl** [comment]
Since I haven't received any feedback I've now removed the recommendation to set `TrackFileAccess=false`.
