### ISSUE TITLE
Allow inode cache on FreeBSD's nullfs

### ISSUE THREAD

**Issue by dsh2dsh** [ccache/ccache#1485]
### Description ###

I found inode cache doesn't support cache dir, mounted with nullfs. I added `nullfs` into `known_to_work_filesystems` here

https://github.com/ccache/ccache/blob/2031c581a648e14d3f3eaa475df0ae3d29780180/src/ccache/inodecache.cpp#L135C43-L135C68

and tried how it works. Well, it just works.

**Comment by jrosdahl** [comment]
Hi,

After some searching I assume that you're talking about FreeBSD's nullfs (hadn't heard about it before)? It's not explicitly disabled, it's just not enabled yet.

However, after reading up on what nullfs is I'm not sure it would be a good idea to add it to `known_to_work_filesystems` since it can be used to mount an NFS filesystem (or another filesystem with unknown semantics). The inode cache is therefore not guaranteed to work on nullfs.

If you want to use the inode cache when the cache directory is on nullfs you can set [temporary_dir (CCACHE_TEMPDIR)](https://ccache.dev/manual/4.10.1.html#config_temporary_dir) to another directory with a supported filesystem instead.

**Comment by dsh2dsh** [comment]
> I assume that you're talking about FreeBSD's nullfs

Correct.

> it can be used to mount an NFS filesystem (or another filesystem with unknown semantics)

You I right, I see now. Thank you, I'm closing this issue.
