### ISSUE TITLE
Option absolute_paths_in_stderr actually also rewrites stdout

### ISSUE THREAD

**Issue by huangqinjin** [ccache/ccache#1505]
Maybe it should be renamed to `absolute_paths_in_output`.

**Comment by jrosdahl** [comment]
Right. The option changed behavior as a side-effect when support for caching stdout was added. At the very least it would be good to update documentation.

I'm not sure about naming it "absolute_paths_in_output" since one could argue that a compilation's "output" also includes the object file and other files created in addition to stderr and stdout.

**Comment by huangqinjin** [comment]
> "output" also includes the object file and other files created in addition to stderr and stdout.

Good point. A document update would be good then,
