### ISSUE TITLE
Tests fail after 2038

### ISSUE THREAD

**Issue by bmwiedemann** [ccache/ccache#1524]
While working on reproducible builds for openSUSE, I found that
our ccache-4.10.2 fails to build in 2038.

### How to reproduce ###

1. run tests with the system clock set to 2038 , e.g. with `qemu -rtc base=2038-02-02T00:00:00`

### Actual behavior ###

```
 21/45 Test #21: test.nocpp2 ......................***Failed    1.41 sec
 Compiler:         gcc (/usr/bin/gcc)
 Compiler version: gcc (SUSE Linux) 14.2.1 20241007 [revision 4af44f2cf7d281f3e4f3957efce10e8b2ccb2ad3]
 CUDA compiler:    not available

 Running test suite nocpp2.......................
 FAILED

 Test suite:     nocpp2 (line 291)
 Test case:      Too new source file
 Failure reason: Expected modified_input_file to be 1, actual 0

 Actual statistics counters
 ==========================
...
 The following tests FAILED: 
          1 - test.base (Failed)
         21 - test.nocpp2 (Failed)
 Errors while running CTest
```

### Expected behavior ###

tests should keep working at least 15y in the future.

### Environment ###

ccache version 4.10.2

OS openSUSE Tumblweed 20241013 x86_64

I tried this patch, but it still failed in the same way:
```diff
--- a/test/suites/base.bash
+++ b/test/suites/base.bash
@@ -285,7 +285,7 @@ fi
     TEST "Too new source file"

     touch new.c
-    touch -t 203801010000 new.c
+    touch -t 303801010000 new.c

     $CCACHE_COMPILE -c new.c
     expect_stat modified_input_file 1
```

**Comment by jrosdahl** [comment]
> I tried this patch, but it still failed in the same way: [...]

This is because ccache internally stores timestamps with nanosecond resolution in an `int64_t`. ccache thus only supports timestamps up to year 2262, so we should remember to change the implementation around 2250 or so at the latest. Until then I think we can keep the current implementation (which was deliberately made with this in mind).

The test suite could indeed be improved to work after 2038. However, since tests most likely still are executed in a 32-bit context somewhere, I don't think we can just change the future timestamp to something between year 2038 and 2262. Instead, somehow compute a timestamp say a day ahead and use that one?

**Comment by bmwiedemann** [comment]
> Instead, somehow compute a timestamp say a day ahead and use that one

Indeed, that works. I force-pushed such a version. It works with `touch` from GNU coreutils.
