### ISSUE TITLE
always treating (set) boolean environment variables as true can be surprising

### ISSUE THREAD

**Issue by mostynb** [ccache/ccache#182]
Common mistakes that can be made:
export CCACHE_DISABLE=false
export CCACHE_CPP2=false

I wonder if it would be worthwhile giving warnings if boolean environment variables have "negative" sounding values ("NO","no","false","FALSE","0" or some subset)?

Or perhaps we should just change the processing of these variables to be more strict and simultaneously more obvious?  eg only accept "true", "false" or "" and take the empty value to mean "use the default for this setting"?

**Comment by ilor** [comment]
I have independently made the same mistake of assuming CCACHE_CPP2=0 would disable the feature

**Comment by afbjorklund** [comment]
Well, changing to an error would break legacy and ccache doesn't really have a good place to output warnings...

But "0" or "false" should be OK

Must only use 1 or "" for true...

**Comment by afbjorklund** [comment]
Patches ?

**Comment by mostynb** [comment]
Patches coming soon, I wanted to discuss the proposed behaviour first.

Can we simply print warnings to stderr, but not cache them?  And if we want this to be an error, exit with an error code without doing any work?  IMO this is better than silently using an "invalid" configuration (assuming there's a useful error/warning message).

**Comment by jrosdahl** [comment]
Here is a previous discussion on the same topic: https://bugzilla.samba.org/show_bug.cgi?id=11826

> Can we simply print warnings to stderr, but not cache them?

We can, but that would be problematic since ccache then no longer works transparently. For instance, autoconf configure scripts have been known to fail tests if the compiler emits anything to stderr even if the produced result actually works. (And printing to stdout is also a no-no.)

> [...] IMO this is better than silently using an "invalid" configuration

I would say that it's valid configuration, but unexpected if you haven't read and understood the documentation, which many of course haven't. I agree that it's unfortunate design choice (made fifteen years ago), but as indicated in the discussion I linked to above, I'm also hesitant to break backward compatibility.

> And if we want this to be an error, exit with an error code without doing any work?

Yes, that's the only reasonable option if we decide to break compatibility. If so, I think your suggestion or some variation sounds fine, in other words:

* Treat `CCACHE_FOO` set to `0`, `false`, `disable` or `no` (case insensitive) as an error and treat any other value as "enable foo".
* Treat `CCACHE_NOFOO` set to `0`, `false`, `disable` or `no` (case insensitive) as an error and treat any other value as "disable foo".

This way we don't break `CCACHE_DISABLE=damnit` or similar creative values.

**Comment by afbjorklund** [comment]
@jrosdahl, your suggestion sounds like a reasonable compromise to me

**Comment by mostynb** [comment]
This is possibly a stupid question, but would it necessarily be bad for autoconf to fail with a strange/arguably "invalid" configuration setting such as this?  I suppose it might be more difficult for the user to find and fix the actual problem.

Anyway, if we're going to turn the weird configurations mentioned above into errors, we may as well print an error message, right?  I will test some patches and try to submit them tomorrow.

**Comment by jrosdahl** [comment]
> [...] would it necessarily be bad for autoconf to fail with a strange/arguably "invalid" configuration setting such as this? I suppose it might be more difficult for the user to find and fix the actual problem.

I would say so, yes. The reason that it's difficult for the user to understand the real problem is that ccache's warnings won't be shown to the user if the configure script fails a test.

**Comment by afbjorklund** [comment]
What does autoconf (compile-time config) have to do with this (run-time config) ?

**Comment by mostynb** [comment]
I think the issue is that autoconf will call the compiler (based on something like CC="ccache gcc" in this case) and if ccache fails because we make CCACHE_DISABLE=0 a warning, then the user probably gets a generic "compiler cannot create executables" error from autoconf, and the actual ccache warning is hidden.

So we may as well make this an error instead of a warning, if we consider autoconf important.
