### ISSUE TITLE
Add capability to cache dwz output

### ISSUE THREAD

**Issue by eklitzke** [ccache/ccache#204]
dwz is a dwarf compressor: https://sourceware.org/git/?p=dwz.git;a=summary . It's a sourceware.org project, so it's semi-officially related to GCC and binutils.

This program is invoked as part of the build process when building RPMs nowadays, while the debuginfo packages are being generated from the binary. For big C++ projects especially, this can be expensive. It would be nice to have ccache provide the ability to cache dwz output, since the dwarf section should already be built in a reproducible way.

cc/ @jakubjelinek

**Comment by afbjorklund** [comment]
Since this is a stand-alone tool, it probably needs rather special treatment (so it is not like the .dwo)

Then again, there are other new tools that could use this kind of caching. Not only DWZ, but also LTO.

https://gcc.gnu.org/ml/gcc/2012-04/msg00686.html

https://gcc.gnu.org/wiki/LinkTimeOptimization

**Comment by jrosdahl** [comment]
If I understand correctly, dwz is not at all like gcc in its commandline interface or behavior, so it's clearly not a good fit for ccache in my opinion. How about writing a `dwzcache` program instead?

**Comment by jrosdahl** [comment]
I'll close this issue for now based on my comment above. Make some noise if you disagree!
