### ISSUE TITLE
CoW: copy-on-write (btrfs/xfs clone) support

### ISSUE THREAD

**Issue by PaulBone** [ccache/ccache#213]
Hi,

I'm working on some patches for adding direct support to clone a file (like a hardlink) on btrfs.  Btrfs supports copy-on-write, you can copy a file without duplicating its data blocks.

I want to ask, is the best way to expose this as an option to the hard_link configuration option?  For example hard_link = true, hard_link = false and hard_link = reflink (or btrfs_clone or some other value).  Or should this be done if supported and fallback to a regular copy (since they have the same semantics anyway).

Thanks.

**Comment by PaulBone** [comment]
Oh, I don't seem to be able to assign myself this bug. Nevertheless I have started work on it.

**Comment by afbjorklund** [comment]
Hardlink support isn't very popular, because it is hard to use (avoid strip) and messes with compression.

Maybe btrfs clone with copy-on-write is better (more userfriendly), but then again nobody is using btrfs...

**Comment by afbjorklund** [comment]
> Oh, I don't seem to be able to assign myself this bug. 
Only project maintainers can do that (same with labels)

**Comment by tdihp** [comment]
My two cents here: since BTRFS and the like already have compression builtin, a custom command for copying the object file, which would enforce whatever copying behavior of the underlying filesystem as the user want, would be great.

BTW @afbjorklund  while I'm not convinced this hard link trick would benefit build time a lot, but I do think using BTRFS might be useful for snapshot to manage and transfer cache state, when having a lot of machines, or to reproduce issues.

**Comment by jrosdahl** [comment]
I plan to introduce "fat result files" in some future ccache version, where all produced data (object file, dependency file and standard error output, etc.) is stored in a single file. This has performance benefits. If `hard_link = true`, my plan is to store the object file next to the "fat result file", but that won't be the default. This means that a BTRFS_IOC_CLONE ioctl can't be made by default. Therefore I think that we need a new configuration option for activating BTRFS_IOC_CLONE (and in the future to trigger storing the object file separately). We can't reuse the `hard_link` option since it in its environment variable form has [boolean semantics only](https://ccache.samba.org/manual/latest.html#_boolean_values).

**Comment by afbjorklund** [comment]
We did some of this, for the memcached branch. It got tedious, to pile on new file formats all the time...

https://github.com/ccache/ccache/pull/58#issuecomment-255547818

Not sure how it would work in the context of #98, though ? Harder to share object files, done this way.

Adding support for [.pack](https://git-scm.com/book/en/v2/Git-Internals-Packfiles) files would be great, too. Then you wouldn't have all those pesky small files.

**Comment by PaulBone** [comment]
My motivation for adding this is to save some disk space _and_ avoid hardlink semantics.  It may be slightly faster also, and that's nice-to-have.

@jrosdahl Ah, thanks for pointing that out.  I'll add a new configuration option.

**Comment by avikivity** [comment]
This is now available generically as the `FICLONE` and `FICLONERANGE` ioctls. It would greatly reduce I/O for large builds.

**Comment by afbjorklund** [comment]
Apparently it (file cloning) is also available for XFS: https://lwn.net/Articles/747633/

**Comment by avikivity** [comment]
I have large builds with large files, so it works out.

At the very least, it saves a large amount of space.

**Comment by afbjorklund** [comment]
I'm thinking that there could be a threshold value involved, for optimum performance.
But we need better tools and tests (#269), to figure out what such a value would be ?

People tell me that "hard disks are cheap", as a reason for not even doing compression...
And then put their builds on `/dev/shm`, just to prove that RAM is also cheap or something.

**Comment by afbjorklund** [comment]
@jrosdahl : note that the FICLONERANGE call could be used, even if multiple files are concatenated...

See [ioctl_ficlonerange(2)](http://man7.org/linux/man-pages/man2/ioctl_ficlonerange.2.html)

**Comment by avikivity** [comment]
Just copying those files around on a SATA link is slow.

**Comment by PaulBone** [comment]
FWIW with large builds (small but especialy large files) you will probably save disk space.

**Comment by afbjorklund** [comment]
I would appreciate it if you could test the code, tried it out on a local btrfs image - but only the basics.

**Comment by PaulBone** [comment]
Hi @afbjorklund, I commented on #296

**Comment by ivan-volnov** [comment]
How about CoW in Apple File System (APFS) support?

**Comment by afbjorklund** [comment]
Support for both hardlink and reflink has now been removed from ccache, with the new result files.

The implementation was linux only, which meant that it fell back on regular copying for e.g. APFS.

**Comment by ivan-volnov** [comment]
Yes, It's a pity to hear that. I have a fork ccache to support file cloning and I already add support for APFS filesystem there. May be anybody wants it too.

**Comment by jrosdahl** [comment]
> How about CoW in Apple File System (APFS) support?

Don't know anything about it, but it sounds like a good thing to support if it behaves like Linux reflinks.

> Yes, It's a pity to hear that [support for both hardlink and reflink has now been removed from ccache].

Well, reflink support was never there, so it hasn't been removed. :wink: 

Regarding hard link support, I removed it for two major reasons:

1. The hard link support blocked what I wanted to accomplish with [aggregated result files](#411) and [compression by default](#413) since I didn't quite know how the new solution would look like and whether keeping hard link support was feasible. And dropping it could also be motivated by:
2. The hard link support is prone to errors.

I have worked quite a lot on ccache last week and the pieces are now coming together so that I think I know what will be feasible. My plan at the moment is actually to *bring back* hard link support before next ccache release. Here's why:

1. The primary problem I see with the hard link mode is the risk of corrupting the cache by the user running e.g. `strip file.o`. But that problem is now easy to fix since we can store the expected file size(s) in the result file and verify the object files before hardlinking them back. Changes that *don't* affect file size won't be detected, but the propability of such user errors is likely very small compared to changes that affect the file size.
2. I've begun sketching a [storage backend API](#414), and optionally supporting what I tentatively call "raw files" will be quite straightforward.
3. Storing "raw files" also opens up for implementing reflinks...

> I have a fork of ccache to support file cloning and I've already added support for APFS filesystem there. May be anybody wants it too.

Cool! If my plan described above holds, maybe you would be interested in contributing APFS CoW support back to ccache?

**Comment by ivan-volnov** [comment]
Thank you @jrosdahl for the explanation.
I agree with you about hard links. They are quite dangerous. But if I were you, instead of removing them I would have replaced them to clone feature. There are more and more filesystems that supports it. And I'm positive that if anybody wants to use the clone feature he will find a suitable filesystem to configure ccache in that way even if it's quite rare and quirky.
My idea is using filesystem clone feature with filesystem compression. That compressed file can be easily clone to application build directory.
Of course if this feature had a chance to take place in ccache, I would be glad to do some contributing back.

**Comment by jrosdahl** [comment]
As of a46fd5b8fa49, the hard link mode is now back in a new and better form. I'll work on reflink support next.

**Comment by ivan-volnov** [comment]
Great news!
@jrosdahl please look at this commit. This is the only thing that needs to be done to enable clone feature on APFS.
https://github.com/ivan-volnov/ccache_link/commit/1f84260f6283bccf681be130b1218e75f21a1af4
They have pretty nice API:
http://www.manpagez.com/man/2/clonefile/
I could help with testing.

**Comment by jrosdahl** [comment]
> @jrosdahl please look at this commit. This is the only thing that needs to be done to enable clone feature on APFS.

OK, done in 0ee563d6b3c2. 

> I could help with testing.

That would be great since I'm not able to do it myself.

**Comment by ivan-volnov** [comment]
@jrosdahl it seems to be working. I've tested current master branch fb0864defec386971c83db9372ad863063c5a322 with hard_links and file_clone. Everything works as expected.

hardlinked file:
```
$ stat -x event.cpp.o
  File: "event.cpp.o"
  Size: 22236488     FileType: Regular File
  Mode: (0644/-rw-r--r--)         Uid: (  501/    user)  Gid: (   20/   staff)
Device: 1,4   Inode: 4316895721    Links: 2
Access: Sat Jul 20 13:54:03 2019
Modify: Sat Jul 20 13:53:56 2019
Change: Sat Jul 20 13:53:56 2019
```
cloned file:
```
$ stat -x event.cpp.o
  File: "event.cpp.o"
  Size: 22236488     FileType: Regular File
  Mode: (0644/-rw-r--r--)         Uid: (  501/    user)  Gid: (   20/   staff)
Device: 1,4   Inode: 4316902473    Links: 1
Access: Sat Jul 20 13:54:38 2019
Modify: Sat Jul 20 13:53:56 2019
Change: Sat Jul 20 13:54:36 2019
```

The only way I can judge that the file is actually clonned is the count of links (Links = 1).
And of course clone works as fast as hardlinks mode.

**Comment by annulen** [comment]
Any idea when it will be available in ccache release?

**Comment by jrosdahl** [comment]
> Any idea when it will be available in ccache release?

See #653.

**Comment by annulen** [comment]
It seems like it was implemented before c++ migration so it could be released in 3.7.x, couldn't it?

**Comment by jrosdahl** [comment]
> It seems like it was implemented before c++ migration so it could be released in 3.7.x, couldn't it?

3.7.x is for bug fixes only (with minor exceptions).

It would of course be possible to port the feature to a 3.7.x context and release a 3.8 with only that feature, but it's not straight-forward since the changes were done based on the code state after the [introduction of aggregate result files](https://github.com/ccache/ccache/issues/408) (and many follow up changes, including rewritten hard link mode). Doing so would risk introducing bugs. I would like to focus on getting 4.0 released instead, sorry.

**Comment by Hi-Angel** [comment]
Any reason, this feature default to off? As the docs note it is completely safe, and it should be useful in like 95% of workloads. People rarely modify object files created.

**Comment by jrosdahl** [comment]
> Any reason, this feature defaults to off?

Yes, because enabling the feature disables compression which makes the cache size significantly larger.

**Comment by afbjorklund** [comment]
> it should be useful in like 95% of workloads

That was actually **not** the case, last time around.

**Comment by Hi-Angel** [comment]
> > it should be useful in like 95% of workloads
> 
> That was actually **not** the case, last time around.

Why? You have maintainers and developers which simply run `ninja -C build` or similar to make libs/executables of object files. Rarely people modify object files, unless of course I am missing something…?

**Comment by afbjorklund** [comment]
> > > it should be useful in like 95% of workloads
> > 
> > 
> > That was actually **not** the case, last time around.
> 
> Why? You have maintainers and developers which simply run `ninja -C build` or similar to make libs/executables of object files. Rarely people modify object files, unless of course I am missing something…?

I mean it wasn't the great speed-up that we were hoping for. It did help with disk usage in some special case, but not really for performance. Your mileage might vary. When it comes to touching object files, it was usually`strip` that was the big culprit...

The other let-down was that there were not many people using a CoW filesystem anyway (since most people are on ext4). But during the right circumstances, it _looked_ like a great idea. Just saying that reflinks were a bit disappointing, just like "splice" was.

**Comment by Hi-Angel** [comment]
> > Why? You have maintainers and developers which simply run `ninja -C build` or similar to make libs/executables of object files. Rarely people modify object files, unless of course I am missing something…?
>
> I mean it wasn't the great speed-up that we were hoping for. It did help with disk usage in some special case, but not really for performance. Your mileage might vary. When it comes to touching object files, it was usually`strip` that was the big culprit...

Does someone strip object files rather than libs/executables? Sounds odd to me. I imagine that might have something to do with static libs, but `strip` works fine on them, so… Idk.

> But during the right circumstances, it _looked_ like a great idea. Just saying that reflinks were a bit disappointing, just like "sendfile" was.

Hmm… You know, this is interesting. You made me curious, so I ran some tests. I have `libinput` cloned *(which, as every meson-based project, uses `ccache` if available)*, so inside its directory I ran `touch src/*` and `time ninja -C build` with `file_clone` enabled and disabled. Exact content of `~/.ccache/ccache.conf`:

```ini
max_size = 5.0G
file_clone = true
```

My results:

with `file_clone = true`:

    ninja -C build  4.05s user 1.39s system 167% cpu 3.239 total
    ninja -C build  4.16s user 1.41s system 170% cpu 3.265 total
    ninja -C build  4.14s user 1.39s system 170% cpu 3.251 total

with `file_clone = false`:

    ninja -C build  4.31s user 1.38s system 248% cpu 2.292 total
    ninja -C build  4.30s user 1.33s system 244% cpu 2.307 total
    ninja -C build  4.30s user 1.39s system 245% cpu 2.316 total

Soo… Oddly enough, no-reflinks build is consistently ≈30% faster. Although, on the other hand, reflinks used 30% less CPU.

My system: `Linux kernel 5.10.4`, BTRFS with ZSTD compression enabled, and an HDD disk.

So, what is weird here is that, I got like a perfect situation for where reflinks could shine. HDDs have slow IO in general *(and mine seems to be bad in particular)*, and one would expect reflinking a file to be much faster than writing a new one. But situation is quite the opposite o.O

**Comment by Hi-Angel** [comment]
FTR: yesterday, after I posted results, I asked a question about them on #btrfs IRC channel, but nobody replied.

**Comment by Hi-Angel** [comment]
**upd**: I upgraded to Linux 5.10.9, and now when I re-run benchmark, I see no difference. Like, at all: both time and CPU usage is the same with and without `file_clone` enabled.

**Comment by degasus** [comment]
> So, what is weird here is that, I got like a perfect situation for where reflinks could shine. HDDs have slow IO in general (and mine seems to be bad in particular), and one would expect reflinking a file to be much faster than writing a new one.

In case there is still a question about this: In case the output file was read afterwards, this "slowdown" in kind of expected in IO limited applications:  The reflink can be created in zero time. But reading the compressed file is faster than reading the larger uncompressed file - even including the zstd decompression time. Writing the new file create more IO load - but the latency is hidden. However the immediate readback of this file is an almost garantueed cache hit.
