### ISSUE TITLE
Add a CCACHE_CXX option

### ISSUE THREAD

**Issue by Timmmm** [ccache/ccache#221]
I am trying to set up CCache and Icecream like this:

    export CC="$(brew --prefix ccache)/libexec/clang"
    export CXX="$(brew --prefix ccache)/libexec/clang++"
    export CCACHE_CC="$(brew --prefix icecream)/libexec/icecc/bin/clang"
    export CCACHE_CXX="$(brew --prefix icecream)/libexec/icecc/bin/clang++"
    export ICECC_CC="$(brew --prefix llvm)/bin/clang"
    export ICECC_CXX="$(brew --prefix llvm)/bin/clang++"

    cmake ..

Unfortunately there is no `CCACHE_CXX` option so this doesn't work. If I just set `CCACHE_CC` to `clang++` then CMake complains that I set my C compiler to be a C++ compiler.

Things you're probably thinking:

> Why don't you just use `-DCMAKE_COMPILER_LAUNCHER`

The project I am using has a lot of `ExternalProject_Add()`'s which mean that I would need a way to pass that flag through to every external project. I *can* do that but this way would require no modifications (if it worked).

> Why don't you just use `CCACHE_PREFIX=icecc` instead of `CCACHE_CC` and `CCACHE_CXX`?

Actually this does work (realised while writing this), but there is a nice symmetry about the above code and it would be good if it worked.

> Why don't you just put <icecc/ccache/clang> in your `PATH`?

I already have Xcode's AppleClang in my path, and having two copies of Clang in my `PATH` sounds like a really really bad idea. Adding 2 more fake `clang`'s to the `PATH` sounds even worse. `PATH` is such an ugly hack anyway.

**Comment by jrosdahl** [comment]
> > Why don't you just use CCACHE_PREFIX=icecc instead of CCACHE_CC and CCACHE_CXX?

> Actually this does work (realised while writing this)

Yes, that's my recommendation as well since then there will be no superfluous icecc invocation for the preprocessing step.

> but there is a nice symmetry about the above code and it would be good if it worked.

`CCACHE_CC` is actually kind of a misnomer – a better name would be `CCACHE_COMPILER` since it's the compiler to run regardless of what source language to compile. If we introduce a `CCACHE_CXX` to compile the `c++` and `c++-header` languages, then I guess that we for symmetry reasons also should introduce `CCACHE_*` variables for the other ≈13 source languages that ccache supports (see the [extensions table in language.c](https://github.com/ccache/ccache/blob/b81df8bfa5fb55a495333e146272dc4053b2a30d/language.c#L19))? :slightly_smiling_face:

**Comment by afbjorklund** [comment]
I think `CCACHE_CXX` _could_ be important enough to warrant an exception to such a "rule", though...
The other languages are normally fine with something like CCACHE_COMPILER, they look at the suffix.

Otherwise I agree with `CCACHE_PREFIX`, it is what we recommend for distcc for instance. You would also want to make sure to catch $CPP and eventually maybe even $LD too - so the prefix is more "safe".

**Comment by jrosdahl** [comment]
> I think CCACHE_CXX could be important enough to warrant an exception to such a "rule", though...

I wouldn't be against that if there is a compelling use case, I'm primarily noting that it from a ccache point of view would introduce *less* symmetry and more special cases...

> The other languages are normally fine with something like CCACHE_COMPILER, they look at the suffix.

I'm thinking that if you set `CCACHE_CC=clang` and `CCACHE_CXX=clang++`, you probably will be surprised when your Fortran compilations stops working.

> You would also want to make sure to catch $CPP and eventually maybe even $LD too - so the prefix is more "safe".

Sorry, I don't understand what you mean here.

**Comment by afbjorklund** [comment]
The `CPP` variable (normally /lib/cpp) is an old way to invoke `cc -E`, so that should also be overridden. This so that systems like distcc can take the preprocessing overhead into account, when scheduling...

Currently we don't do anything special for linking, but if/when we do then other variables come into play.
So it's the same story here, overriding each and every one of those speaks for doing it the "prefix" way

**Comment by jrosdahl** [comment]
> So it's the same story here, overriding each and every one of those speaks for doing it the "prefix" way

Yes, so I'm leaning towards not adding a `CCACHE_CXX`.

It would probably be a good idea to introduce a `CCACHE_COMPILER` variable (mapping to the already  existing `compiler` option in the configuration file) and keep `CCACHE_CC` as a deprecated alias.

**Comment by jrosdahl** [comment]
> It would probably be a good idea to introduce a CCACHE_COMPILER variable (mapping to the already existing compiler option in the configuration file) and keep CCACHE_CC as a deprecated alias.

Done in d653cfae233a79cd29b9f231cced0d95f5692fab.
