### ISSUE TITLE
Redirecting stderr causes cache miss

### ISSUE THREAD

**Issue by torokati44** [ccache/ccache#222]
**Actual behavior:** Redirecting stderr to a file causes a cache miss.
**Expected behavior:** Redirecting stderr does not affect ccache operation in general.
**Steps to reproduce:**
- Clean and clear the ccache cache, and zero out its statistics: `ccache -cCz`
- Take a small, valid C or C++ file: `main.c`
- Compile it twice using ccache, once redirecting stderr into a file, and once without, in any order:
  - `clang -c main.c -o main.o` *(where clang is ccache in disguise)*
  - `clang -c main.c -o main.o 2> /dev/null` *(or vice versa)*
- Check the ccache statistics: `ccache -s`
- There are two cache misses, opposed to the expected one miss and one hit.

**Additional notes:**
- Redirecting stdout does not seem to matter.
- It occurs even if there isn't any output to stderr nor stdout in either compilation.
- Redirecting to a regular file or `/dev/null` does not make a difference.
- If stderr is redirected to `/dev/null` in both cases (or in neither of them), there is no problem.

**ccache version:** 3.3.4
**compiler:** clang 5.0.1 *(although I feel like this is indifferent)*
**OS:** Fedora 27 x64

**Rationale:**
I'm trying to run two-stage builds on Travis CI, where the first stage builds a sizable C++ project using ccache, and the second stage uses the cache to build much faster, then runs a series of tests on the built project. The compilation and the tests together would often exceed the 50 minute per-job limit of Travis CI. In the first stage I'm interested in the compiler output during compilation, in the second I'm not, hence the redirection.

Two example builds, the first works fine and the second demonstrates the issue:
https://travis-ci.org/torokati44/inet/builds/336512738
https://travis-ci.org/torokati44/inet/builds/336548982

**Comment by jrosdahl** [comment]
This is actually intentional, see caveat number 1 in d875edef19d0ab157b2f6408330bb1392fd38f60. If we would treat the redirected case and TTY case the same, then you either would get color escape codes in the redirected output or you wouldn't get colors in TTY output.

At the very least, it would be good to add something to the documentation about this behavior.

Any ideas on how to do things even smarter are of course welcome. :slightly_smiling_face:

**Comment by torokati44** [comment]
I think adding an option to ccache to control this behavior would be nice. Something like `CCACHE_COLOR`, with these possible values:

- `on` and `off`: these would override tty detection and the present compiler options, forcing the compiler to enable/disable coloring, possibly using methods specific to the detected/guessed compiler - any of these would solve my issue, `on` being preferred

- `auto`/`detect`/(`default`): the current behavior, as the default

- `noop`/`passthrough`/`ignore`: disables all logic related to color in ccache, letting the compiler do what it wants, even if it means that coloring is disabled when stderr is ultimately going to a tty, through ccache

What do you think?

**Comment by jrosdahl** [comment]
If possible, I would like to avoid a new ccache option for this. Perhaps you could just pass `-fcolor-diagnostics` explicitly in your builds? Then it should just work.

Another idea: If ccache sees that `-f(no-)color-diagnostics` is not passed explicitly to clang (so that we are in auto detection mode), always force color diagnostics, thus storing stderr with color codes in the cache. Then when printing to stderr on a cache hit, strip the color codes if stderr doesn't refer to a TTY.

(On a side note, this idea unfortunately won't work for GCC since GCC 4.8 and older will fail if passed a `-fdiagnostics-color`... Coming to think of it, GCC coloring is actually broken for GCC 5 and newer when run via ccache since auto detection seems to be the default now. When d875edef19d0ab157b2f6408330bb1392fd38f60 was written, GCC 4.9 required GCC_COLORS to be set... Sigh.)

**Comment by torokati44** [comment]
Alright, I understand.

I ended up doing as you suggested: added `-fcolorize-diagnostics` to the compiler flags in both stages. This indeed solved my problem. And for now it is enough if it works with clang only.

Still, somehow it feels wrong to me that this is the solution: force-enabling coloring of suppressed error messages to ensure cache hits and avoid timeouts resulting in broken tests. But oh well, if this is what needs to be done, so be it.

And considering how troublesome it was for me to find out what was going on, I think adding some information about this behavior to the documentation would definitely be useful for others in the future.

**Comment by torokati44** [comment]
I liked your idea though, about always requesting colored diagnostics from the compiler, and stripping the formatting in ccache, only if it is deemed necessary (detected non-tty stderr, or flag which disables it). If it really can't be done with current gcc, as you said... Well, too bad. :/

**Comment by jrosdahl** [comment]
> And considering how troublesome it was for me to find out what was going on, I think adding some information about this behavior to the documentation would definitely be useful for others in the future.

Documented in 67fdd3b53c19476d33a9f74acdf02046293437ab.

**Comment by torokati44** [comment]
Thank you so much!
