### ISSUE TITLE
Make colored warnings work for GCC out of the box

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#224]
### Background

GCC ≥4.9 can emit colored diagnostics messages such as warnings. ccache handles this (see d875edef19d0ab157b2f6408330bb1392fd38f60) according to [GCC 4.9's documentation](https://gcc.gnu.org/onlinedocs/gcc-4.9.0/gcc/Language-Independent-Options.html): "The default is never if GCC_COLORS environment variable isn't present in the environment, and auto otherwise." However, GCC ≥5.1 [documents](https://gcc.gnu.org/onlinedocs/gcc-5.1.0/gcc/Language-Independent-Options.html) that "the default depends on how the compiler has been configured", which for at least Ubuntu-based and RedHat-based distributions seems to be `auto` without the requirement of `GCC_COLORS` being set. This means that ccache doesn't replicate the defacto behavior for GCC ≥5.1.

Here's an idea of how to improve things.

### What to do

If the compiler is GCC:

* Don't include any explicit `-f(no-)diagnostics-color` options in the hash.
* Strip any explicit `-fno-diagnostics-color` and `-fdiagnostics-color` options from the compiler arguments and add a `-fdiagnostics-color` option (if not already present) to force colors.
* If `run_second_cpp` is true, run the preprocessor without `-fdiagnostics-color` (since those error messages won't be used anyway).
* If the compiler (in the `run_second_cpp` case) or preprocessor (in the `!run_second_cpp` case) fails with the added `-fdiagnostics-color` option, check if the error message includes `unrecognized command line option` and `-fdiagnostics-color`. If yes, execute again but without `-fdiagnostics-color`.
* If `run_second_cpp` is false, remember if it worked to pass `-fdiagnostics-color` to the preprocessor. If yes, add `-fdiagnostics-color` when executing the compiler as well.
* On a cache hit: Strip color codes from the stored stderr if `-fno-diagnostics-color` has been passed **OR** `-fdiagnostics-color=never` has been passed **OR** (stderr does not refer to a TTY **AND** `-fdiagnostics-color` has not been passed **AND** `-fdiagnostics-color=always` has not been passed).
* Prove that it works by adding a test case that checks that color codes are stored in the cache and that color codes are not produced when stderr is redirected.
* Remove the corresponding caveat from the documentation.

The above method will make cache misses (and preprocessed hits when `run_second_cpp` is false) slightly slower for GCC ≤4.8. On my system, the extra probe call takes ≈1 ms. I think that this is an OK price to pay to make colored warnings work transparently for modern GCC versions.

See also #223 which is somewhat similar but for clang.

**Comment by torarnv** [comment]
The plan outlined by @jrosdahl above would also help clang, where I'm seeing the same symptom, `ccache` not respecting the clang defaults of emitting color diagnostics if there's a tty attached.

**Comment by jrosdahl** [comment]
(Sorry for the massively delayed answer, your question slipped through the cracks.)

> Or I guess #223 is the clang equivalent of this issue?

No, #223 is another feature. Clang's color diagnostics are already supposed to be supported. They work for me at least. Which Clang version do you use?

**Comment by Artoria2e5** [comment]
The current HEAD is working with gcc out-of-the-box too.

**Comment by edgar-bonet** [comment]
I am new to ccache, and this may just be a dumb idea, but... since the compiler seems to care whether `stderr` is a terminal or not, why not give it a terminal? A [pseudo-terminal pair][pty] could be used instead of a pipe. The algorithm would be as follows:

```c
if (isatty(STDERR_FILENO)) {

    // ccache's stderr is a terminal. Make sure the compiler's own
    // stderr is also a terminal in order to get the expected behavior
    // relative to color in diagnostics.
    open a master pseudo-terminal
    run the compiler with its stderr redirected to the slave pseudo-terminal
    get the compiler’s output from the master pseudo-terminal
} else {

    // Our stderr has been redirected. Let the compiler see it's own
    // stderr has been redirected.
    create a pipe
    run the compiler with its stderr redirected to one end of the pipe
    get the compiler’s output from the other end
}
```

[pty]: http://man7.org/linux/man-pages/man7/pty.7.html

**Comment by jrosdahl** [comment]
> since the compiler seems to care whether stderr is a terminal or not, why not give it a terminal?

I don't have experience with the PTY interfaces, but it sounds like an interesting idea. A downside of that solution, though, is that the TTY and non-TTY cases won't (can't) share cache entries.

**Comment by edgar-bonet** [comment]
This is a followup on my idea of using a pseudo-terminal pair. It turns out there is a standard Unix utility that leverages this technique in order to run either a single command or a full terminal session inside a pseudo-terminal, while capturing its output. It's called [script][], and seems to be available on every Unixish platform (e.g. [Linux][], [FreeBSD][], [MacOS][]).

I tried some experiments. First, let's get a compilation that generates a warning:

```sh
echo 'main(){}' > test.c
/usr/bin/gcc test.c
```

With gcc 9.2.1, I get this message, nicely colored:

```text
test.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
    1 | main(){}
      | ^~~~
```

Now, try again, redirecting the compiler's standard error stream to a file:

```sh
/usr/bin/gcc test.c 2> output.txt
```

The file `output.txt` contains the same warning as before, but with _no color_.

Finally, let's use `script` to run the compiler in a pseudo-terminal:

```sh
script -c '/usr/bin/gcc test.c' output.txt > /dev/null
```

Now the file contains the warning _in color_.

One may notice that `script` adds a couple of lines to the file (“Script started on ...” / “Script done on ...”). This could be avoided like this:

```sh
script -q -c '/usr/bin/gcc test.c' /dev/null > output.txt
```

Could ccache either use `script` or take inspiration from scrip's implementation? The behavior could be as follows:

* if ccache's stderr is a terminal (as reported by `isatty()`), run the compiler in a pseudo-terminal, otherwise redirect its output to a file
* add the tty/no-tty info to the hash

Pros:

* would work with both gcc and clang, or any compiler for that matter
* would not require ccache to guess what compiler is being used
* would not require ccache to know or care about the color-controlling compiler options, which would otherwise be messy (they depend on compiler and compiler version)
* would not require ccache to know or care about environment variables such as `GCC_COLORS`, or compiler configuration, which could depend on distro version
* would always emulate the behavior of the compiler running out of ccache

Con:

* the tty and no-tty cases would not share cache entries

I don't think the use case of #222 (compiling once with stderr redirected and then again without the redirection) is common. But then the issue could be mitigated by providing a configuration option:

```text
run_in_terminal = always / auto / never
```

Alternatively, ccache could _always_ run the compiler in a pseudo-terminal and, on a cache hit, strip the color codes if it's own stderr is not a terminal.

[script]: https://en.wikipedia.org/wiki/Script_(Unix)
[Linux]: http://man7.org/linux/man-pages/man1/script.1.html
[FreeBSD]: https://www.freebsd.org/cgi/man.cgi?query=script
[MacOS]: http://www.manpagez.com/man/1/script/

**Comment by sdettmer** [comment]
What would be having some gcc_color=false or CCACHE_NO_GCC_COLOR=x environment support?

**Comment by sdettmer** [comment]
I found a difference, clion sets GCC_COLORS in environment (I created https://youtrack.jetbrains.com/issue/CPP-19692), even overwriting inherited users values, if any.

This now seems to be the case: used gcc does not have GCC_COLORS, but in environment it is present. I think it is used for a heuristic and the fallback does not work correctly, could that be?

**Comment by jrosdahl** [comment]
> What would be having some gcc_color=false or CCACHE_NO_GCC_COLOR=x environment support? I think currently ccache has trouble with older GCC?

@sdettmer: This issue is about how to (and whether to) make colored warnings work for GCC out of the box. Please don't hijack it for bug reports or support requests – instead please consider opening a new issue.

**Comment by sdettmer** [comment]
@jrosdahl I'm sorry for being off-topic. I did not delete my first message in case it could help others when found by google, but this of course is the wrong place, sorry.
In issue #297 it was mentioned "please subscribe to #224 instead.".

I think the idea describe in first section of this issue could be considered because of that, so maybe on topic could be:

1. If guessing in invocation, the log file will contain many preprocessor errors and harder to read. So maybe ccache could need to "cache" whether a specific compiler (by full path?) supports it or not.
1. I think (at least) if this would be implemented, GCC_COLORS handling should be removed from ccache
1. If user passes -fno-diagnostics-color, I think compiler shall fail, even with ccache
1. Whatever heuristics are implemented, it could be great if they could be disabled (actually my first point). It might be just my personal experience, but I'm afraid more magic can mean more (harder) issues. This was also mentioned in #222 (but probably also off-topic)
1. Regarding to the comment from @edgar-bonet 
> I don't think the use case of #222 (compiling once with stderr redirected and then again without the redirection) is common.

I'd like to add that in my team it is common: Jenkins never has a terminal, half of interactively working developers build in a shell. Others use IDEs and at least CLion explicitely sets GCC_COLORS. (I did not understand why they wouldn't share results depending of pty).

6. I think I like the alternative idea of using openpty() if isatty(). It seems straight-forward and "transparent".

7. Could the compiler invoked with`--version`  or such and the result (maybe for full path or even compiler hash) cached? gcc/clang old/new could be detected and arbitrary quirks for special versions enabled (not limited to coloring).

@jrosdahl Should I create a new issue for one of the items? For me most important actually is #297. Should I open a new issue for some intermediate version, such as a new config option (but you already commented on that in #222, so certainly not).

**Comment by jrosdahl** [comment]
> 1. If guessing in invocation, the log file will contain many preprocessor errors and harder to read. [...]

If you're talking the probing call (from the issue description: _"check if the error message includes unrecognized command line option and -fdiagnostics-color. If yes, execute again but without -fdiagnostics-color."_), then I see no reason why it should add preprocessor error messages to the log.

> 2. I think (at least) if this would be implemented, GCC_COLORS handling should be removed from ccache

ccache still needs to include the content of GCC_COLORS since it affects the output, but there would no longer be a need to take decisions based on the variable being present, correct.

> 3. If user passes -fno-diagnostics-color, I think compiler shall fail, even with ccache

That's a good point. So if `-fno-diagnostics-color` or `-fdiagnostics-color` is used explicitly we could skip any heuristics and probing calls.

> 4. Whatever heuristics are implemented, it could be great if they could be disabled (actually my first point). It might be just my personal experience, but I'm afraid more magic can mean more (harder) issues. This was also mentioned in #222 (but probably also off-topic)

The context then was whether to add an option for the TTY detection and GCC_COLORS heuristics, but you're talking about an option for the probing heuristics, right? Just like in #222 I would like to avoid adding an option for this. Not everything needs to be configurable.

> 6. I think I like the alternative idea of using openpty() if isatty(). It seems straight-forward and "transparent".

I agree that it seems robust on paper, which of course is nice, but it has the downside of not sharing cache entries for the TTY and non-TTY cases. I haven't decided what I think about that yet.

> 7. Could the compiler invoked with`--version`  or such and the result (maybe for full path or even compiler hash) cached? gcc/clang old/new could be detected and arbitrary quirks for special versions enabled (not limited to coloring).

It could, but then ccache would need to have very detailed knowledge of compilers and which versions support what options. Not saying that it's out of the question, but it's not very straight-forward.

> Should I create a new issue for one of the items?

Sorry, I don't understand which items you refer to.

> For me most important actually is #297. Should I open a new issue for some intermediate solution, such as a new config option (but you already commented on that in #222, so certainly not).

No, I think that we should fix real the problem instead of investing effort into an intermediate solution.

**Comment by Artoria2e5** [comment]
Since around 1998, a much easier to use interface for PTYs called [posix_openpt](https://pubs.opengroup.org/onlinepubs/9699919799/functions/posix_openpt.html) has been around. Just a heads up if someone finds openpty hard to work with.

**Comment by sdettmer** [comment]
Thank you for your detailed reply and helpful informations.

1)
> I see no reason why it should add preprocessor error messages to the log.

Ahh that probably would be good. Currently there are error messages in the log when the tried `-fdiagnostics-color` creates a failure (so for each file).

By the way, in the new scheme, is the idea to make one probing call for each new compiler and store the result somehow, or for each invocation?
(I think currently there is no such concept as checking compiler properties?)

2)
> ccache still needs to include the content of GCC_COLORS since it affects the output

I already read this but didn't understand. Of course its not needed that I understand :) but could you give me a hint / link why colored compiler (stderr?) messages affect the output?

I think same applies for:

> the downside of not sharing cache entries for the TTY and non-TTY cases

which I also didn't understand.

4)
[disabling heuristics by configuration]

OK, sure. It's just a pitty if a heuristic guesses wrong and breaks things. But I understand that these cases are exotic (here: ccache and CLion). However, on a system with several compilers user may set 
GCC_COLORS and use old compilers at the same time. But most probably use new compilers and want colors without setting the option (although I wonder if they call them directly, not via cmake/IDE/....).




> > 1. Could the compiler invoked with`--version`
[and the result possibly saved]

> It could, but then ccache would need to have very detailed knowledge of compilers and which versions support what options. Not saying that it's out of the question, but it's not very straight-forward.

I'm not sure if I can follow... The output of `$CC --version` should directly tell whether it is GCC, Clang or something else, and which version. For example if ccache differentiates on what compilers to try coloring output (only gcc > 4.8 and clang > ?), wouldn't it be straight-forward to detect exactly this from `--version` output?
I think this is like autoconf checks if there is gcc or other cc.


I implemented workarounds in wrapper scripts for ccache (was not so easy to get shell, vim, QtCreator, Clion and the others working at the same time), so all fine for me.

Have a nice weekend and thanks again for your patient explanations!

**Comment by jrosdahl** [comment]
> By the way, in the new scheme, is the idea to make one probing call for each new compiler and store the result somehow, or for each invocation?

As detailed in the issue description, the idea is to always add the `-fdiagnostics-color` option for each invocation. In the common case (i.e., GCC ≥4.9) this will work right away so there will be no extra compiler invocation. But if the call fails the idea is to rerun the compilation without `-fdiagnostics-color`, so the first call can then be seen as a probing call, which is what I meant in https://github.com/ccache/ccache/issues/224#issuecomment-607996232.

> (I think currently there is no such concept as checking compiler properties?)

That's correct.

> could you give me a hint / link why colored compiler (stderr?) messages affect the output?

By "output" I mean all observable compiler output, which includes the data written to stderr.

> > the downside of not sharing cache entries for the TTY and non-TTY cases
> 
> which I also didn't understand.

See #222. A user would like `ccache $compiler ...` (with stderr connected to a TTY) to be a cache hit when `ccache $compiler ... 2>stderr.txt` has been executed previously. But the output is different in the two cases: color codes should be emitted in the former case but not in the latter.

> It's just a pitty if a heuristic guesses wrong and breaks things.

Essentially _everything_ ccache is about is to apply a number of heuristics – it's about performing a balancing act of taking neither too little nor too much information into account.

**Comment by liljenzin** [comment]
Here is another test case:
static_assert(false, "\033[1;31mbold red text\033[0m\n");

Obviously not enough to filter the output for color codes since the output from above will be colored regardless of compiler swithes.

**Comment by liljenzin** [comment]
If diagnostics color is enabled it seems necessary to also include GCC_COLORS from environment in the hash. On the other hand, if output from the compiler is empty the result is valid regardless of the color settings. Perhaps we could reuse the result in that case?

**Comment by whitslack** [comment]
> If diagnostics color is enabled it seems necessary to also include GCC_COLORS from environment in the hash.

I personally think the trade-off of not necessarily seeing the color scheme you requested is worth the increase in cache hits, but we could add another "sloppiness" flag to control this. If (and only if) the new sloppiness flag is enabled, then `GCC_COLORS` is omitted from the hash.

I'd also be fine with ccache's *always unsetting* `GCC_COLORS` when invoking the compiler.

Another possibility would be for ccache to *always set* `GCC_COLORS` to a specification that gives each category an arbitrary but unique SGR code, and then ccache could remap the codes in the cached compiler output to those requested by the user on each particular invocation of ccache. That really seems like overkill to me, though.

> On the other hand, if output from the compiler is empty the result is valid regardless of the color settings. Perhaps we could reuse the result in that case?

One better: if the compiler output *contains no SGR codes*, then the result is valid regardless.

**Comment by whitslack** [comment]
> ```
> static_assert(false, "\033[1;31mbold red text\033[0m\n");
> ```
> 
> Obviously not enough to filter the output for color codes since the output from above will be colored regardless of compiler switches.

If you want that edge case to work, then I see no way to share cached output between the TTY and non-TTY cases. Do you?

**Comment by liljenzin** [comment]
> > If diagnostics color is enabled it seems necessary to also include GCC_COLORS from environment in the hash.
> 
> I personally think the trade-off of not necessarily seeing the color scheme you requested is worth the increase in cache hits, but we could add another "sloppiness" flag to control this. If (and only if) the new sloppiness flag is enabled, then `GCC_COLORS` is omitted from the hash.
> 
> I'd also be fine with ccache's _always unsetting_ `GCC_COLORS` when invoking the compiler.
> 
> Another possibility would be for ccache to _always set_ `GCC_COLORS` to a specification that gives each category an arbitrary but unique SGR code, and then ccache could remap the codes in the cached compiler output to those requested by the user on each particular invocation of ccache. That really seems like overkill to me, though.
> 

Personally I don't care about colored output and usually turns it off. But I wouldn't be surprised if changed compiler output caused regressions for some people. Not that I know of any build system that depends on it though. I just think it should be a goal by itself to make ccache reproducing the original compiler behavior as far as possible, since you don't know what would break otherwise.

If low hit rate is an issue you can improve the situation by adjusting your compiler switches. I prefer that before having to adjust the compiler switches to get correct output.

> One better: if the compiler output _contains no SGR codes_, then the result is valid regardless.

Possibly true if the cached result was with colors enabled, but what about the other way around?

**Comment by liljenzin** [comment]
> > ```
> > static_assert(false, "\033[1;31mbold red text\033[0m\n");
> > ```
> > 
> > 
> > Obviously not enough to filter the output for color codes since the output from above will be colored regardless of compiler switches.
> 
> If you want that edge case to work, then I see no way to share cached output between the TTY and non-TTY cases. Do you?

I could always add "-fdiagnostics-color=never" to improve the hit rate.

**Comment by jrosdahl** [comment]
> Here is another test case:
> 
> ```
> static_assert(false, "\033[1;31mbold red text\033[0m\n");
> ```
> 
> Obviously not enough to filter the output for color codes since the output from above will be colored regardless of compiler switches.

Please note that ccache doesn't cache failures (compiler exit code != 0), so a custom `static_assert` message with color codes won't be a problem.

**Comment by whitslack** [comment]
> Please note that ccache doesn't cache failures (compiler exit code != 0), so a custom `static_assert` message with color codes won't be a problem.

Okay, that's fine, but a `#warning` message containing color codes would be cached (assuming the compilation succeeded).

**Comment by jrosdahl** [comment]
> Okay, that's fine, but a #warning message containing color codes would be cached (assuming the compilation succeeded).

OK, GCC (but not Clang) seems to emit the #warning message verbatim so if it contains literal color codes (with ESC (0x1b) bytes) then it will happen.

**Comment by Artoria2e5** [comment]
Putting escape codes in `#warning` doesn't sound like a good idea to start with, so maybe we can shrug at the user for doing that? From the perspective of supporting many types of output it's almost reckless.

**Comment by jrosdahl** [comment]
I wrote:
> Please note that ccache doesn't cache failures (compiler exit code != 0), so a custom `static_assert` message with color codes won't be a problem.

Thinking more about this, a custom `static_assert` message with color codes will indeed be affected not because stderr is cached but because ccache doesn't rerun the compiler on failure and instead emits the saved stderr output from the initial run. When doing that, ccache needs to apply the same color code stripping logic as it does when taking a result from the cache.

That said, I don't think this is a particularly important problem. Making the common case work seems like an acceptable trade-off.

**Comment by liljenzin** [comment]
> Putting escape codes in `#warning` doesn't sound like a good idea to start with, so maybe we can shrug at the user for doing that? From the perspective of supporting many types of output it's almost reckless.

You could possibly blame users compiling their own code, but most users will build something other people wrote. It might takes hour to build a project and perhaps the entire thing fails because one of a hundred thousand unit tests emits different output than expected.

I'm a bit concerned about the way Fedora package ccache with wrappers that run ccache by default by putting the wrappers before the compilers in path. Which means users that never asked for ccache will run it just because the package is installed. If ccache then behaves slightly different than the requested system compiler it could be a surprise for unaware users. At least for me, checking if someone has tampered with the system compiler would be the last thing to look for. The Fedora packaging is a different issue though.

Having that said I have no real example where the suggested change would break something and it might not be an issue at all.

**Comment by jrosdahl** [comment]
> It might takes hour to build a project and perhaps the entire thing fails because one of a hundred thousand unit tests emits different output than expected.

That would of course be annoying, but it would be a deterministic error that would be reasonably easy to fix or work around once understood. I think that it's overshadowed by known limitations like [the direct mode caveat](https://ccache.dev/manual/3.7.9.html#_caveats) or still unknown bugs similar to #582.

> I'm a bit concerned about the way Fedora package ccache with wrappers that run ccache by default by putting the wrappers before the compilers in path. Which means users that never asked for ccache will run it just because the package is installed. If ccache then behaves slightly different than the requested system compiler it could be a surprise for unaware users.

I fully agree. Unfortunately the [Fedora ccache maintainer didn't](https://bugzilla.redhat.com/show_bug.cgi?id=759592#c12).

**Comment by whitslack** [comment]
My [pull request](https://github.com/ccache/ccache/pull/596) to resolve this is now ready for review.

**Comment by whitslack** [comment]
Note that I implemented the **What to do** outlined at the top of this issue report, but I did not address the matter of the `GCC_COLORS` environment variable. As presently implemented, ccache will include the value of `GCC_COLORS` in the compilation hash, meaning that compilations with `GCC_COLORS` set to differing values will not share cache objects, even if those compilations specify `-fno-diagnostics-color`. I cannot come up with any way to improve the situation unless ccache is able to map multiple hash values to the same cache objects in an efficient manner. (I could see hardlinking cache objects under multiple hashes, but I would not consider that to be particularly efficient.)

**Comment by whitslack** [comment]
> My personal experience from building different projects is that the vast majority of individual compilations don't emit warnings

My personal experience is the opposite. I run Gentoo, and thus I compile everything from source, and almost every build emits a warning of some kind.

> many projects build with -Werror to intentionally fail such compilations.

Because most packages *do* emit warnings (usually because the compiler has learned new diagnostics since the source being compiled was authored), Gentoo has to *strip* `-Werror` out of the flags of many packages it builds.

**Comment by liljenzin** [comment]
> My personal experience is the opposite. I run Gentoo, and thus I compile everything from source, and almost every build emits a warning of some kind.

For my understanding, does "almost every build" refer to "almost every compilation unit" or "almost every package/module"?

What matters is if >50% of the individual compilation units emit warnings or if <50% emit warnings.

**Comment by whitslack** [comment]
@liljenzin: Hmm, I wouldn't go so far as to say "almost every compilation unit" (across all packages) emits warnings, although for some large (and especially older) packages it is certainly true that almost every compilation unit (in those packages) emits warnings.

**Comment by liljenzin** [comment]
The question is if one should take the slow path (+1ms) for the compilations units that emit warnings or for those that don't. The only way to figure out is to count them one by one. :-)

**Comment by whitslack** [comment]
@liljenzin: Correct me if I'm wrong: the point of this whole discussion is to enable sharing of no-warning compilation results across different values of `GCC_COLORS`. I think if that can't be achieved with zero penalty in all cases, then it's not worth pursuing, as the likelihood that a single ccache user will compile the same package with multiple different values of `GCC_COLORS` is vanishingly small, I would guess.

**Comment by liljenzin** [comment]
@whitslack: I tried your PR and it worked excellent for me.

**Comment by jrosdahl** [comment]
@whitslack wrote:

> My pull request to resolve this is now ready for review.

Thanks.

> Just a caution: there could potentially be other implications of giving the compiler a pseudoterminal besides just whether GCC will default to colored diagnostic messages. [...] My preference and recommendation would be for ccache NOT to attach compiler invocations to a pseudoterminal just for the sake of activating the compiler's colored diagnostics heuristic.

For the record, I agree. But thanks @edgar-bonet for the discussion regarding PTYs, it's appreciated.

> As presently implemented, ccache will include the value of GCC_COLORS in the compilation hash, meaning that compilations with GCC_COLORS set to differing values will not share cache objects, even if those compilations specify -fno-diagnostics-color.

That's good. If somebody wants ccache to ignore GCC_COLORS we can add a sloppiness setting for it.

> [...] enable sharing of no-warning compilation results across different values of GCC_COLORS. I think if that can't be achieved with zero penalty in all cases, then it's not worth pursuing [...]

Agree.
