### ISSUE TITLE
__DATE__ & __TIME__ causes indirect mode in string literals and comments.

### ISSUE THREAD

**Issue by jorgenpt** [ccache/ccache#27]
The manual specifies `ccache turns off direct mode if “__TIME__” is present in the source code outside comments and string literals.` -- but even though the occurrence of **TIME** is in a trivial comment like this:

```
// This is a thing. __TIME__ all day long!
```

ccache logs the following:

```
[2013-06-07T15:07:04.049076 72838] Found __TIME__ in /path/to/header.h
[2013-06-07T15:07:04.049085 72838] Disabling direct mode
```

**Comment by Trass3r** [comment]
@jrosdahl seems like this is still a problem? False positives in
https://github.com/Trass3r/llvm-project/blob/main/clang/include/clang/Lex/Preprocessor.h#L155-L159

**Comment by jrosdahl** [comment]
That sounds OK if, as you say, the code complexity doesn't increase too much. Patches welcome.

Note though that it is not trivial to parse out comments. Ccache used to [try to do that](https://github.com/ccache/ccache/blob/149d4912dcda693cade96f7da7bf41af92f3884d/hashutil.c#L53-L190), but it was [removed due to bugs](https://github.com/ccache/ccache/commit/2f8422af65c44526e3d54d961be1134a5c225aac) (and slowness). C++ raw string literals don't make things easier either.
