### ISSUE TITLE
Unused arguments in pre-processor step

### ISSUE THREAD

**Issue by biasmv** [ccache/ccache#312]
We are currently running into an issue with arguments that get passed to the preprocessor but are unused. Normally, this is not a big issue, but when `-Werror` is passed to the compiler unused arguments get reported while running the preprocessor and fail the preprocessing step.

We use `direct_mode=true` and `run_second_cpp=true`.

I've modified ccache locally to not pass the offending argument to the pre-processor (and still pass it to the compilation step). This is more of a work-around rather than a real solution, so I wanted to check with you what you think the best approach is before I submit a PR and check if you agree that this is worth fixing.

Possible approaches I could think of:

- Filter out arguments that are clearly not for pre-processor use, such as -Xlinker, -Xassembler, -Wa,$foo, -Wl,$foo and only pass them to the compiler. The drawback is that ccache has to maintain a potentially growing list of arguments that could result in an unused command-line argument error.
- Another approach is to not pass `-Werror` to to the pre-processor step. While the pre-processor would still complain about unused arguments, it would no longer fail. Errors from `-Werror` would still get reported during the actual compilation step, not failing during the preprocessor step should be fine.
- Another approach is to pass `-Wunused-command-line-argument` to the pre-processor. I'm not sure how portable this one is.

To me it seems that not passing `-Werror` to the pre-processor is the most stable approach to work around this issue. What do you think?

Version information:

- CCACHE 3.4.3+45_g181298b_dirty
- Compiler: NDK clang++

**Comment by afbjorklund** [comment]
It would be nice if ccache would give the same warnings/errors as when not using ccache, but this is increasingly **not** the case (since the cpp output is getting sidestepped more and more, as per cpp2)
A good first step would be to make it easier to extend/modify the params, but like you say the list might be growing and needs to be maintained. Not sure how "risky" option 2 is, hiding errors from the cpp...

Maybe we could pass it for cpp1 (run_second_cpp=false) and skip it for cpp2 (run_second_cpp=true) ?

And if you had any more examples of commonly used -X flags that are mis-categorized at the moment

**Comment by jrosdahl** [comment]
ccache already has a growing [list of option classifications](https://github.com/ccache/ccache/blob/a0bb3133f51d1cb6a6fe03a2948aebac185554e6/src/compopt.c#L32). I don't think that it would be unreasonable to add a "never send to the preprocessor" classifier as well.

Not passing `-Werror` to the preprocessor sounds like an incomplete solution since users then may want to fix the warnings emitted by the preprocessor step, only to find out that it's not possible.

Passing `-Wunused-command-line-argument` sounds better, but as you say will probably not be portable enough.

**Comment by jrosdahl** [comment]
@biasmv: Any news here? Would you be interested in working on a pull request?

If not, a list of options that you have found to be candidates for not passing to the preprocessor would be welcome.

**Comment by jrosdahl** [comment]
@biasmv: Any news?

**Comment by biasmv** [comment]
Apologies for the late reply. It looks like I won't have time to submit a patch for this myself. I've compiled a list of options that cause an unused argument warning when using clang. It's not an exhaustive list, there are probably more. 

-  `-Xlinker,*`
- `-Xassembler,*`
- `-Wl,*`
- `-prebind`
- `-preload`
- `-rdynamic`
- `-all_load`
- `-bind_at_load`
- `-bundle`
- `-pie`
- `-nolibc`

On latest clang `-Wa,*` does not cause a warning, even though the behaviour of that option should be identical to `-Xassembler,*`.It causes a warning on an older clang from the Android NDK. It's probably save to also remove that one.

**Comment by jrosdahl** [comment]
Thanks!

**Comment by jrosdahl** [comment]
Here's my plan: Don't pass the options you listed to the preprocessor **and also don't pass `-Werror`**. Then if there are options missing in the list, you'll only get build warnings. @biasmv: Sounds good?

**Comment by biasmv** [comment]
Sounds good to me!
