### ISSUE TITLE
Document ccache setup with distcc-pump

### ISSUE THREAD

**Issue by hkrpavan** [ccache/ccache#320]
Hello,

   As per ccache release 3.4 news it was stated that

ccache should now work with distcc’s “pump” wrapper. 

I don't see any special instructions to set it up. Adding pump to CCACHE_PREFIX is not helping and always missing ccache hits.

**Comment by hkrpavan** [comment]
Thanks. These instructions helped. I have an observation here. Using cache with pump is not using all the CPU cores available on my build host.

pump gmake -j target

is the command I am using.

top command always shows only one instance of ccache

**Comment by hkrpavan** [comment]
Thanks these instructions helped. It would be good to have this information in ccache documentation.

**Comment by jrosdahl** [comment]
> Thanks these instructions helped. It would be good to have this information in ccache documentation.

Yes please. (It would also be good to have them in the distcc documentation.)

**Comment by afbjorklund** [comment]
This also needs to document how to run ccache on the distcc **server**, when using distcc pump mode.

**Comment by rmatev** [comment]
@afbjorklund I can run ccache on the distcc server, following something similar to [this](https://wilsonhongblog.wordpress.com/2016/05/24/using-ccache-on-distcc-server/).

However, ccache does not make any hits because `.deps` are requested by distccd and the random `.o` filename ends up in them (and ccache correctly finds no match).
```
(dcc_spawn_child) forking to execute: /path/to/ccache/wrapped/g++ -c fast.cpp -o /tmp/distccd_e0cb3bc9.o -MMD -MF /tmp/distcc_9ef83bc9.deps
```
Have you found a way to get ccache on the distcc server __and__ get reasonable hits?

**Comment by afbjorklund** [comment]
For this to work, the distcc server needs to use a temporary _directory_ instead of filenames...
Then we can use the basedir and relative deps support, in order to make the output the same ?

**Comment by afbjorklund** [comment]
Currently distcc cleans this up _after_ compilation, by editing the `.o` and `.d` files:
https://github.com/distcc/distcc/blob/master/src/serve.c#L798:L826

But like you discovered, that also means that it will set ccache up for a cache miss...
What was the original command sent to distcc ? It needs to preserve relative paths.

**Comment by rmatev** [comment]
On the client I just do `pump distcc g++ -c fast.cpp -o fast.o` to test.

You are right, we should make distccd use a temp directory and use basedir. Since I wrote the comment I saw a discussion about the same issue at https://github.com/ccache/ccache/issues/339#issuecomment-447590550 solved the way you suggest, hopefully they share the patch.

Ultimately, I wonder if this approach, e.g. `(client) pump distcc ==> (server) distccd --> ccache --> g++` is better compared to your approach with memcached, which I just found about. Obviously, in the former the cache is just shared per server (unless a shared filesystem is used or some high-latency sync mechanism), but given some big servers with tens of cores it's probably acceptable. The disadvantage of memcached is that is stuck on ccache 3.4 as far as I understand.

**Comment by jrosdahl** [comment]
@afbjorklund: Would you be interested in compiling some documentation for this? Or do you think that we should close the issue?

**Comment by afbjorklund** [comment]
I'm rather poor at writing documentation, and it seems like this one sits right inbetween the two projects...

And https://distcc.github.io/ is also rather old, so maybe better to leave it as a "third party opportunity" ?

Haven't had the opportunity to use ccache/distcc in some time, so not using it actively myself any more.

So you can go ahead and close it (if @hkrpavan agrees), I suppose it can always re-open or just do a PR

**Comment by jrosdahl** [comment]
OK, thanks. Since I have no experience with distcc myself it would take me a long time to write something accurate, so I'll close the issue for now.

A pull request or a comment to this issue with a documentation proposal will of course still be appreciated.
