### ISSUE TITLE
Suggestion: Empty/disabled ccache.conf

### ISSUE THREAD

**Issue by BarbzYHOOL** [ccache/ccache#348]
version 3.3.2

Do not add anything in user config file (or comment it out for a template) during installation (I used the debian package though, maybe it's not related to you)
Same in /etc/ccache.conf

Because I edited the /etc one and didn't realize the user was overriding it but it was the default setting of 5.0GB

Ccache should use 5.0GB by default without the need to specify any config file.

**EDIT: or maybe it's set to 5.0GB the first time you use any ccache command?
**EDIT2: hmm yes it is the case, but I still think it shouldn't create the file in the home dir, because it forces me to edit two files**

**Comment by jrosdahl** [comment]
Thanks for your interest in ccache.

Sorry, I don't quite understand what you think is problematic.

Here's roughly how it works:

* If `max_size` is set in `~/.ccache/ccache.conf`, that value is used.
* Otherwise if `max_size` is set in `/etc/ccache.conf`, that value is used.
* Otherwise the default value is used, which is 5 GB. (Just like you suggested with "Ccache should use 5.0GB by default without the need to specify any config file".)
* If `~/.ccache/ccache.conf` does not exist, ccache creates it as an empty file (i.e., `max_size` is not written to the file).
* If `ccache -M X` is called, ccache writes `max_size = X` to `~/.ccache/ccache.conf`.
* You should never need to edit two files.

What, if anything, of the above do you think should be changed?

**Comment by BarbzYHOOL** [comment]
if max_size is set in /etc/ccache.conf, then it creates ~/.ccache/ccache.conf with the max_size from /etc/

**Comment by jrosdahl** [comment]
> if max_size is set in /etc/ccache.conf, then it creates ~/.ccache/ccache.conf with the max_size from /etc/

OK, now I see what you mean.

Ccache does not do that by default, with one exception: If `~/.ccache` exists and was created by a Ccache version older than 3.2 and `~/.ccache/ccache.conf` does _not_ exist, then a newer Ccache version will **migrate** the max cache size configuration (which was stored in a different way by older Ccache versions) to `~/.ccache/ccache.conf`. So if you want to use `/etc/ccache.conf` instead, the fix is to remove `max_size` from `~/.ccache/ccache.conf` but don't remove the file. Or simply remove the whole `~/.ccache` directory if losing the cache is OK.

**Comment by jrosdahl** [comment]
I think that it would be possible to not perform this migration and instead just read max_size from the legacy config location if max_size isn't set by the usual means. I'll check if it works out.

**Comment by BarbzYHOOL** [comment]
>If ~/.ccache exists and was created by a Ccache version older than 3.2

But I'm on deb 9:

```
ccache/testing,unstable 3.5-1 amd64
ccache/stable,now 3.3.4-1 amd64 [installed]
```

So i never had a 3.2 on this machine

**Comment by jrosdahl** [comment]
It doesn't really work out. The reason is a bit complicated to explain, but here's an attempt:

Currently:

* If Ccache sees that `~/.ccache/ccache.conf` is missing, it reads the legacy configuration (stored in the statistics files, by the way) once and creates `~/.ccache/ccache.conf` with `max_files` and/or `max_size` **if set in the legacy configuration** (falling back to default for values that are unset). `max_files` is normally not set (meaning "unlimited files") in the legacy configuration.
* The legacy configuation is never read again.

If Ccache would not perform the migration it would have to work like this:

* If Ccache sees that `~/.ccache/ccache.conf` is missing, is will instead read the values from the legacy configuration if they are set there. This is fine.
* If Ccache sees that `~/.ccache/ccache.conf` exists but `max_size` and/or `max_files` are not set there or in `/etc/ccache.conf`, it would have to both read the configuration file **and** the legacy configuration. Since `max_files` normally isn't set in the legacy configuration, Ccache would in practice have to read both `~/.ccache/ccache.conf` and the legacy configuration on every invocation. I can't justify this just to make the edge case you describe less surprising.

So as mentioned earlier, the solution is to simply remove `max_size` from `~/.ccache/ccache.conf` but keep the file.

**Comment by BarbzYHOOL** [comment]
"So as mentioned earlier, the solution is to simply remove max_size from ~/.ccache/ccache.conf but keep the file."

very unpractical when deploying with ansible on many machines (need to add more actions to remove it) but if it's only a rare case it's prob because the first time I had an error in my /etc/ccache.conf, at least I hope
