### ISSUE TITLE
Large command lines in the debug log get interrupted in the middle

### ISSUE THREAD

**Issue by DrASK** [ccache/ccache#350]
ccache version: 3.4.1; compiler is gcc; os is lunux/ubuntu

I'm writing a Python script to run through a 3.9GB logfile and it's encountering the following two lines (yes, they are long):

Line the first:
`[2019-01-22T15:31:14.120970 20924] Command line: /usr/bin/ccache /usr/local/accelerated/arm-linux-gnueabi-tools-20180525/bin/arm-linux-gnueabi-gcc -Werror -D__KERNEL__ -mlittle-endian -DANI_LITTLE_BYTE_ENDIAN -DANI_LITTLE_BIT_ENDIAN -DQC_WLAN_CHIPSET_QCA_CLD -DDOT11F_LITTLE_ENDIAN_HOST -DANI_COMPILER_TYPE_GCC -DANI_OS_TYPE_ANDROID=6 -DANI_LOGDUMP -DWLAN_PERF -DPTT_SOCK_SVC_ENABLE -Wall -D__linux__ -DHAL_SELF_STA_PER_BSS=1 -DWLAN_FEATURE_VOWIFI_11R -DWLAN_FEATURE_NEIGHBOR_ROAMING -DWLAN_FEATURE_NEIGHBOR_ROAMING_DEBUG -DWLAN_FEATURE_VOWIFI_11R_DEBUG -DFEATURE_WLAN_WAPI -DFEATURE_OEM_DATA_SUPPORT -DSOFTAP_CHANNEL_RANGE -DWLAN_AP_STA_CONCURRENCY -DFEATURE_WLAN_SCAN_PNO -DWLAN_FEATURE_PACKET_FILTERING -DWLAN_FEATURE_VOWIFI -DWLAN_FEATURE_11AC -DWLAN_ENABLE_AGEIE_ON_SCAN_RESULTS -DWLAN_NS_OFFLOAD -DWLAN_ACTIVEMODE_OFFLOAD_FEATURE -DWLAN_FEATURE_HOLD_RX_WAKELOCK -DWLAN_SOFTAP_VSTA_FEATURE -DWLAN_FEATURE_ROAM_SCAN_OFFLOAD -DWLAN_FEATURE_GTK_OFFLOAD -DWLAN_WAKEUP_EVENTS -DFEATURE_WLAN_RA_FILTERING -DWLAN_KD_READY_NOTIFIER -DFEATURE_WLAN_BATCH_SCAN -DFEATURE_WLAN_LPHB -DFEATURE_WLAN_PAL_TIMER_DISABLE -DFEATURE_WLAN_PAL_MEM_DISABLE -DQCA_SUPPORT_TX_THROTTLE -DWMI_INTERFACE_EVENT_LOGGING -DATH_SUPPORT_WAPI -DWLAN_FEATURE_LINK_LAYER_STATS -DFEATURE_WLAN_EXTSCAN -DQCA_LL_TX_FLOW_CT -DFEATURE_WLAN_LFR -DFEATURE_WLAN_CH144 -DCONFIG_WEXT_PRIV -DQCA_PKT_PROTO_TRACE -DCONFIG_HL_SUPPORT -DCONFIG_AR6320_SUPPORT -DSDIO_3_0 -DHIF_SDIO -DCONFIG_ATH_PROCFS_DIAG_SUPPORT -DFEATURE_HL_GROUP_CREDIT_FLOW_CONTROL -DFEATURE_WLAN_FORCE_SAP_SCC -DDFS_MASTER_OFFLOAD_IND_SUPPORT -DOSIF_NEED_RX_PEER_ID -DQCA_SUPPORT_TXRX_LOCAL_PEER_ID -DTRACE_RECORD -DLIM_TRACE_RECORD -DSME_TRACE_RECORD -DFEATURE_WLAN_ESE -DQCA_COMPUTE_TX_DELAY -DQCA_COMPUTE_TX_DELAY_[2019-01-22T15:31:14.120995 20921] Looking for object file hash in /media/ramdisk/ccache/8/0/a5aeb4aa31d7fb647e1541b2e36a00-7290.manifest`

Line the second:

`PER_TID -DFEATURE_WLAN_ESE_UPLOAD -DFEATURE_WLAN_DIAG_SUPPORT -DFEATURE_WLAN_DIAG_SUPPORT_CSR -DFEATURE_WLAN_DIAG_SUPPORT_LIM -DWLAN_AUTOGEN_MACADDR_FEATURE -DPANIC_ON_BUG -DWLAN_OPEN_SOURCE -DWLAN_FEATURE_STATS_EXT -DQCA_IBSS_SUPPORT -DADF_SUPPORT -DATH_PERF_PWR_OFFLOAD -DCONFIG_TX_DESC_HI_PRIO_RESERVE -DATH_SUPPORT_SHARED_IRQ -DATH_BUS_PM -DWDI_EVENT_ENABLE -DAH_BYTE_ORDER=1234 -DQCA_WIFI_FTM -DCHECKSUM_OFFLOAD -DWLAN_FEATURE_GTK_OFFLOAD -DIGTK_OFFLOAD -DWLAN_OPEN_P2P_INTERFACE -DWLAN_ENABLE_SOCIAL_CHANNELS_5G_ONLY -DTARGET_RAMDUMP_AFTER_KERNEL_PANIC -DFEATURE_AP_MCC_CH_AVOIDANCE -DFEATURE_WLAN_CH_AVOID -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -fno-dwarf2-cfi-asm -fno-ipa-sra -mabi=aapcs-linux -mfpu=vfp -funwind-tables -marm -Wa,-mno-warn-deprecated -D__LINUX_ARM_ARCH__=5 -march=armv5te -mtune=xscale -msoft-float -Uarm -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized -Wno-maybe-uninitialized --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Wmaybe-uninitialized -c -x c /dev/null -o .20923.tmp`

Now if you look at the last part of the first line, you'll see that a new log message got inserted at the end.

`DSME_TRACE_RECORD -DFEATURE_WLAN_ESE -DQCA_COMPUTE_TX_DELAY -DQCA_COMPUTE_TX_DELAY_[2019-01-22T15:31:14.120995 20921] Looking for object file hash in /media/ramdisk/ccache/8/0/a5aeb4aa31d7fb647e1541b2e36a00-7290.manifest`

Not sure why this is happening. Maximum line size of some sort?

I suppose my ask is that long lines be kept long, with no intervening newline. If that is not possible, perhaps an indicator of some sort (say, '+') at the beginning to show that this is a continuation of the previous message. But for sure in any case, it really shouldn't be dropping new log messages at the end of a previous message, right?

Happy to submit a PR if I can get some pointers on where the problem may lie. 

Aaron

**Comment by DrASK** [comment]
I see now the the interloper message is from another pid. I'm pretty sure I ran my build as a single CPU, but maybe not. ¯\_(ツ)_/¯

Anyway, I can see that multiple processes can intersperse messages in the debug log, but I think a single log message should be atomic. With one timestamp/pid per line.

**Comment by jrosdahl** [comment]
> Maximum line size of some sort?

Nope.

> I think a single log message should be atomic.

That would indeed be preferable.

Ccache uses the standard stdio stream functions (`fprintf` and friends) to write parts of each log message to the log file. `fflush` is then called when the log line is finished. I assume that what's happening is that libc decided to flush the data to the OS before the long line was finished.

> Happy to submit a PR if I can get some pointers on where the problem may lie.

Nice! You should begin looking in [src/util.c](https://github.com/ccache/ccache/blob/master/src/util.c). Search for the `fflush` calls which are run in two different flavors of log functions. If you buffer data yourself instead of using stdio and then write the message to the log file descriptor via a single `write(2)`, things should improve.

Oh, and you should also check out the "debug mode" introduced in [ccache 3.5](https://ccache.samba.org/releasenotes.html#_ccache_3_5) ([documentation](https://ccache.samba.org/manual/latest.html#_cache_debugging)). When enabled, ccache will write one log file for each object file, thus eliminating any race between processes.

**Comment by afbjorklund** [comment]
It's possible that long lines might get interleaved. Would need to lock the log file, to avoid that...

https://www.notthewizard.com/2014/06/17/are-files-appends-really-atomic/

**Comment by jrosdahl** [comment]
> It's possible that long lines might get interleaved. Would need to lock the log file, to avoid that...

Yup. I'm aware that large writes aren't atomic, but as said in the blog post you linked to I expect writes up to 4096 bytes to be atomic in practice on a Linux system. Since @DrASK's long line was broken after 1744 bytes my hypothesis is that performing writes without stdio buffering would improve things.

We could of course also split long lines with some continuation character like @DrASK suggested.

My gut feeling is that locking could be out of the question for performance reasons, but it would be interesting to benchmark it.

**Comment by afbjorklund** [comment]
Not sure that flock is out if the question, it is a debugging log after all ? Alternatively, we could perhaps look at supporting some kind of logging server ? Not sure what exists...

**Comment by jrosdahl** [comment]
OK, let's try out locking around each log call.
