### ISSUE TITLE
Feature request: Rust support

### ISSUE THREAD

**Issue by n1ywb** [ccache/ccache#364]
I know rust is all fast and stuff but it would be even faster with compiler caching :)

**Comment by jrosdahl** [comment]
Thanks for the suggestion.

I think that it's extremely unlikely that ccache will ever support Rust since the compilation model is totally different from that of GCC. I suggest looking at [sccache's experimental Rust support](https://github.com/mozilla/sccache/blob/master/docs/Rust.md) instead.

Closing this, sorry.
