### ISSUE TITLE
Introduce aggregated result files

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#411]
### Background

See #218.

### What to do

* Use a file format as discussed/prototyped in #218.
* Keep result files uncompressed by default and allow for compression using zlib if compression is enabled explicitly.
* Remove support for hard links.
  * Rationale: The hard links feature has proven to be prone to errors: a) changes to files outside the cache will corrupt the cache; b) the mtime field in the file's i-node is used for different purposes by ccache and build tools like make.

**Comment by jrosdahl** [comment]
@afbjorklund is working on this in #408.

**Comment by afbjorklund** [comment]
This work is based on the original memcached code (#30) and the manifest format (ccache 3.0).

Basically we write out the length, and then we write out the contents. Nothing fancier than that...

**Comment by jrosdahl** [comment]
From https://github.com/ccache/ccache/pull/384#issuecomment-490587506:

> I guess the --dump-result will just create files with the contents, rather than writing them on console ?

I haven't thought about it earlier, but spontaneously I would suggest a `--dump-result` which only describes headers and some other option (`--unpack-result`?) which writes the contained files to the file system.

**Comment by afbjorklund** [comment]
Initial implementation is ready, seems to be passing the tests at least.

**Comment by afbjorklund** [comment]
This implementation is still very file-centric, since it takes a cache path rather than a cache key.

e.g. `~/.ccache/1/0/066a3f1308f635a823b92939c8a3de-17195.result`
instead of something like `10066a3f1308f635a823b92939c8a3de-17195`

Also the implementation uses the gzFile functions, when working with the manifest and result files.

----
It's not a problem for _this_ feature, means there are more things left to do for other features.
For instance it won't work with database backends, and won't work with LZ4 compression.

**Comment by jrosdahl** [comment]
Status: #408 and some additional work is now on master.

There are still some minor things to do, so I'm keeping this issue open for now. Thanks again @afbjorklund for the initial implementation!

**Comment by jrosdahl** [comment]
I consider this done now. I still have some related refactoring on my to do list, but that'll be done sometime later.
