### ISSUE TITLE
Ccache tries to cache PCH but fails because of -gsplit-dwarf

### ISSUE THREAD

**Issue by llunak** [ccache/ccache#419]
When LibreOffice build creates a precompiled header, it creates it similarly to how sources are compiled, using (more or less) the same CXX and CXXFLAGS, just with -x c++-header and some adjustments. If ccache is used, it tries to handle such PCH creation as a normal compile, and in normal cases, that works. But if -gsplit-dwarf if used, ccache assumes a .dwo file will be created, which it won't be during PCH creation. See the log file attached.
[ccache.txt](https://github.com/ccache/ccache/files/3161742/ccache.txt)

There are several problems:
- As can be seen in the log, the internal ccache error causes each PCH to be generated twice.
- Ccache doesn't clean up properly and leaves those files in its cache (I'm not sure if they count as being in the cache or they're simply forgotten).
- And finally, should ccache even cache PCHs? Especially without compression and with GCC they can be huge. Even with Clang, which produces noticeably smaller PCHs, all PCHs for my LibreOffice build total at 1.6GiB uncompressed (with ~10GiB object files).

**Comment by jrosdahl** [comment]
> But if -gsplit-dwarf if used, ccache assumes a .dwo file will be created, which it won't be during PCH creation.

This sounds a bit related to #393. The fix for both that issue and this issue could be to just detect whether the compiler created a .dwo instead of trying to calculate if a .dwo should be created.

> And finally, should ccache even cache PCHs? Especially without compression and with GCC they can be huge. Even with Clang, which produces noticeably smaller PCHs, all PCHs for my LibreOffice build total at 1.6GiB uncompressed (with ~10GiB object files).

I've never used precompiled headers myself so I don't have a good intuition about them (if people actually use ccache for PCHs since you have to read the ccache manual and set sloppiness etc for it to work), but some people apparently were interested in caching preprocessed headers for GCC, as can be read in [this mail thread](https://www.mail-archive.com/ccache@lists.samba.org/msg00467.html). And then somebody called [Luboš Luňák wanted to cache precompiled headers for Clang as well](https://www.mail-archive.com/ccache@lists.samba.org/msg00809.html).

**Comment by llunak** [comment]
> This sounds a bit related to #393. The fix for both that issue and this issue could be to just detect whether the compiler created a .dwo instead of trying to calculate if a .dwo should be created.

That sounds acceptable.
 
> I've never used precompiled headers myself so I don't have a good intuition about them (if people actually use ccache for PCHs since you have to read the ccache manual and set sloppiness etc for it to work), but some people apparently were interested in caching preprocessed headers for GCC, as can be read in [this mail thread](https://www.mail-archive.com/ccache@lists.samba.org/msg00467.html). 
That's something slightly different. Those two links are about caching compilations that use a PCH. This case is about ccache caching the actual creation of the .pch from a .h, which is very similar to compiling .o from .cpp . I didn't expect ccache would cache that. That said, if that .dwo case gets fixed, then I guess I have no strong preference one way or another, so I'll close this one until somebody has a strong preference.

> And then somebody called [Luboš Luňák wanted to cache precompiled headers for Clang as well](https://www.mail-archive.com/ccache@lists.samba.org/msg00809.html).

Ah yes, that guy, I've heard of him too.
