### ISSUE TITLE
When CCACHE_BASEDIR is a subset of the CWD, the CWD is used instead

### ISSUE THREAD

**Issue by ctsa** [ccache/ccache#429]
### How to reproduce ###

1. Set CWD to /foo
2. Set CCACHE_BASEDIR to a child of the CWD, eg. /foo/bar
3. ccache compile a command line with absolute paths below CCACHE_BASEDIR, eg. /foo/bar/baz.o

### Actual behavior ###
Absolute paths are trimmed to relative paths based on CWD and not CCACHE_BASEDIR

### Expected behavior ###
Absolute paths are trimmed to relative paths based on CCACHE_BASEDIR

### Environment ###
ccache version 3.7.1 / Centos7

**Comment by jrosdahl** [comment]
Hi, thanks for the bug report!

The behavior you describe is by design – CCACHE_BASEDIR selects which files to apply the "rewrite absolute paths to relative paths" algorithm to; it does not tell which directory the paths should be relative to.

So let's say we have this situation:

```
mkdir -p /tmp/foo/bar
cd /tmp/foo
touch bar/baz.c
CCACHE_LOGFILE=/dev/stdout CCACHE_BASEDIR=$PWD/bar ccache gcc -c $PWD/bar/baz.c -o $PWD/bar/baz.o | grep Source
```
The output is `[...] Source file: bar/baz.c`. Without CCACHE_BASEDIR, it's 
`[...] Source file: /tmp/foo/bar/baz.c`.

If ccache would behave like you expected, what should the source path be rewritten to (nothing?)?

Do you have an actual problem with the current behavior, and if so, what's the problem?

**Comment by ctsa** [comment]
Thanks for the explanation.

The actual problem I'm trying to solve is figuring out how to increase the cache hit rate when building in different directories.

In this particular case I'm working with a software package with a mandatory out of source build process. I've modified the build system to change the working directory to the root of the source tree and use all relative source paths for the code and include directories, now the only thing preventing a cache hit between builds in different locations is that I still have the object file output as an absolute path. I was trying to use the CCACHE_BASEDIR to erase the path of the object file, and in the process, encountered the behavior described above.

**Comment by jrosdahl** [comment]
Just to clarify: CCACHE_BASEDIR is not used to erase parts of paths – it's used to make ccache rewrite paths into *equivalent relative paths*.

You didn't answer my question about what you expected the source path to be rewritten to, so I'm still not sure what you would like to accomplish. Since the object file path is the only one that is absolute in your scenario, maybe you would have expected `baz.o` for the object file? If so, ccache would pass `-o baz.o` to the compiler and then the object file would end up in the wrong place, right?

> the only thing preventing a cache hit between builds in different locations is that I still have the object file output as an absolute path

The object file path is not part of the hash that identifies a cached result, so it sounds like it's something else that is the problem. Have you followed the instructions in the [_Compiling in different directories_](https://ccache.dev/manual/latest.html#_compiling_in_different_directories) section in the manual? In particular, pay attention to the _"If you build with -g [...]"_ part.

**Comment by jrosdahl** [comment]
@ctsa: Are you happy with the answers or do you want some more information?

**Comment by ctsa** [comment]
Hi, Sorry for the delay. Yes I think I have a more clear understanding of how this feature is supposed to work now. Thank you for the helpful explanations.
