### ISSUE TITLE
CMake build support

### ISSUE THREAD

**Issue by cristianadam** [ccache/ccache#430]
I have a CMake build port of ccache at [ccache-cmake](https://github.com/cristianadam/ccache-cmake).

Would you welcome a pull request? 

I mostly did this port because I wanted to use ccache on Windows using pure MinGW, and building ccache with just the MinGW GCC Compiler is not easy.

It mostly works, changing configuration options causes it to crash, which is unfortunate:

```
ccache -o compression=true
ccache -o max_size=50GB
```

Seems to work. I can see the  settings into `c:\Users\Cristian\AppData\Roaming\.ccache\ccache.conf `, but `ccache -p`, or `ccache -k max_size` do not display anything.

But then when I try to use ccache it fails with:
```
ccache: error: C:\Users\Cristian\AppData\Roaming/.ccache/ccache.conf:2: (null)
```

By deleting the `ccache.conf `, ccache will create an empty file and will work as expected.

Since Visual Studio, Qt Creator, CLion have support for CMake, it would help Windows users test and adopt ccache.

Ideally I would like to have Visual C++ support in ccache. I'll open a feature request with more information.

**Comment by afbjorklund** [comment]
Hi @cristianadam !

There are a lot of Windows-related changes (mostly related to Cygwin and MSYS2) suggested already:
https://github.com/ccache/ccache/pulls?q=is%3Apr+is%3Aopen+label%3Awindows

We looked at Visual C++ support, but it was so invasive to the rest of the code base so it was rejected:
https://github.com/ccache/ccache/pull/162#issuecomment-289215585

----

The problem with adding CMake is that duplicates a lot of the autoconf functionality.
This means that one would end up having to maintain two files for the same thing...
For the "normal" (unix) platforms, running a `./configure` script is easier than `cmake`
And I personally don't think that it is more maintainable, than the shell scripts/autoconf.

BTW, why did you decide to bundle `gperf` ? I thought it was just a command-line tool ?

At one point I was trying to support Cygwin, but I guess it has never worked OK in MinGW.

**Comment by cristianadam** [comment]
I bundled gperf because on Windows it doesn't exist.  At the moment I'm missing the tests, which I will add, in order to see if I can catch the bugs with configuration. Maybe #162 has some fixes.

**Comment by jrosdahl** [comment]
Hi!

> Would you welcome a pull request?

I'm not interested in having CMake as *an alternative* to autotools, since, as @afbjorklund said, we would have to maintain two different ways to describe the build which I think would be a waste of developer time.

It's not totally out of the question to *switch* to CMake, but then it has to handle all aspects that the current autoconf setup handles, including the stuff in dev.mk.in. However, I'm not sure if it's worth the effort given that Windows currently isn't really a supported platform (except maybe Cygwin, although I'm not sure about its status), as mentioned in #431 and https://github.com/ccache/ccache/pull/162#issuecomment-289215585.

**Comment by jrosdahl** [comment]
Thinking more about this.

I've never really written any CMake configuration to speak of, only read and tweaked it at different occasions. It felt... well, not at all great, but I find it hard to say that it felt *worse* than autotools which I never have liked. Also, I now remember that I ended up being positive [the last time the suggestion came up](https://www.mail-archive.com/ccache@lists.samba.org/msg01338.html), although nothing came out from it then.

I personally think that Meson looks more sane, but I don't have any experience with it either and it doesn't appear to be as prevalent as CMake.

@afbjorklund wrote:
> And I personally don't think that it is more maintainable, than the shell scripts/autoconf.

Do you have any specific paint points to share regarding maintaining CMake stuff?

**Comment by afbjorklund** [comment]
> > And I personally don't think that it is more maintainable, than the shell scripts/autoconf.
> 
> Do you have any specific paint points to share regarding maintaining CMake stuff?

Mostly in-house, but keeping things portable and simple requires some pre-thought and planning...
The autotools scripts are not particularly maintainable either, but they're all _done_ since a long time.

So it's usually just a way of rediscovering/reimplementing old things, that wasn't so fun to start with ?
But I just know that the default "Unix Makefiles" generator is really poor and you want to use "Ninja".

**Comment by cristianadam** [comment]
I have updated my branch. I've added unittest support, and figured out the last piece of the confitems_lookup.c puzzle, which was causing my build to crash!

@afbjorklund I wouldn't say CMake's "Unix Makesfiles" generator is poor. I should handle a project like ccache without any problems.

Regarding the Meson build,  #162  upstream project got a PR https://github.com/jd-gascuel/ccache/pull/7

From what I have seen Meson has a cleaner scripting language than CMake, but nothing that one can't do in CMake.  CMake has a broader ecosistem, and better tooling support.

**Comment by afbjorklund** [comment]
> @afbjorklund I wouldn't say CMake's "Unix Makesfiles" generator is poor. I should handle a project like ccache without any problems.

It's more like it is generating complex recursive Makefiles, but it will probably handle ccache just fine. Note that there is a similar problem with autotools, so ccache only uses `autoconf` - and not `automake`.

It would have been possible to "fix" the make generator, with non-recursive files and better dependency handling... But since the ninja generator already existed, CMake just suggests to use that one instead.

**Comment by jrosdahl** [comment]
> Regarding the Meson build, #162 upstream project got a PR jd-gascuel#7

Looks like #259 was submitted before jd-gascuel#7.

> I have updated my branch.

With branch I guess you mean your (non-fork) ccache-cmake project, right?

**Comment by cristianadam** [comment]
> With branch I guess you mean your (non-fork) ccache-cmake project, right?

In the meantime I've created a proper fork: https://github.com/cristianadam/ccache

**Comment by ivan-volnov** [comment]
Currently ccache has a lot of veery old stuff support. For instance MSDOS support. I'm not sure if we have to support so old and weird operating systems. And autotools is the best way to deal with this old stuff. But what for?

I believe that using CMake is much more preferable because it's modern and widely used among developers around the world.

By the way I have a fork based on CMake too https://github.com/ivan-volnov/ccache_link

We can combine together all that solved problems that appeared while changing build system and can easily move to CMake.

Of course if the project leader will decide that CMake is good enough for him because he use it in this project much more frequent than we do.

@jrosdahl please have a look at CMake and maybe try it, if you have some time.

**Comment by ivan-volnov** [comment]
I also believe that we can replace all autotools checks to simple #ifdef checks. And most of them will be:
```
#ifdef _WIN32
// the code
#endif
```
Roughly speaking we have just 3 type of OSes today: Linux, Unix (Mac, *BSD) and Windows.
First two is 99% compatible because they are POSIX like OSes. And the last one is the worst because it has a lot of differences.
In my fork I changed all autotools defines to #ifdef _WIN32. Yes, it still have to be tested, I just googled if every type of OSes have the function I needed.

So, if the project leader wants it, it will be quite feasible.

**Comment by afbjorklund** [comment]
> Roughly speaking we have just 3 type of OSes today: Linux, Unix (Mac, *BSD) and Windows.
> First two is 99% compatible because they are POSIX like OSes. And the last one is the worst because it has a lot of differences.

Agree. I made some attempts to support [MinGW](http://www.mingw.org/) ("Minimalist GNU for Windows"), but in the end it wasn't worth it... Using [MSYS2](https://www.msys2.org/) (POSIX) is now a **much** better option, and the "native" windows support in the alternative still lacked features like Visual Studio or PowerShell or any other similar component that requires a total rewrite (just not a compatibility layer). But `_WIN32` is a _different_ discussion, you can still use CMake.

Windows issues: https://github.com/ccache/ccache/issues?q=is%3Aissue+is%3Aopen+label%3Awindows

Windows support: https://github.com/ccache/ccache/pull/162#issuecomment-289215585

**Comment by ivan-volnov** [comment]
Cool, I didn't know about [cclash](https://github.com/inorton/cclash) project . So, we can get rid of Windows support at all?)

**Comment by afbjorklund** [comment]
I support removing Win32 in favor of POSIX.

Feel free to do an issue (and a PR ?) for it, then we can discuss that topic separately from this one.

But the Windows support in ccache today probably isn't working anyway, without a proper shell etc.

**Comment by jrosdahl** [comment]
@ivan-volnov wrote:
> Roughly speaking we have just 3 type of OSes today: Linux, Unix (Mac, *BSD) and Windows.

Right, those are of course the most popular ones. There are however enthusiasts and probably even corporations that use ccache on older Unix-derivatives, see for instance #214. I'm sure there are many more. It would be nice to continue supporting them of possible with reasonable effort.

That said, I'm also in favor of dropping support for old legacy stuff. My current plan for the next version (currently called 3.8 but it could end up being called 4.0) is to require a C++11 compiler. That will naturally raise the bar for which systems are supported, so switching to CMake or Meson (or maybe both with one being the officially supported) then makes sense.

Note that switching to e.g. CMake is not only about creating the needed CMakeLists.txt file but also to make the CI work and to update documentation on how to build ccache.

@afbjorklund wrote:
> But the Windows support in ccache today probably isn't working anyway, without a proper shell etc.

My impression is that a MinGW build of ccache *currently* works reasonably well since it seems to actually be used by some people. See https://github.com/nagayasu-shinya/ccache-win64, https://github.com/nagayasu-shinya/ccache-win64/issues/3 and https://github.com/nagayasu-shinya/ccache-win64/issues/4.

**Comment by afbjorklund** [comment]
I know that MinGW _was_ working reasonably well at some point in time, after a lot of hacks (years ago)
The tests _definitely_ do not work, so I guess it would be more trial-and-error to verify if it works OK or not

**Comment by cristianadam** [comment]
There was another CMake port mentioned in the mailing list in [July 2016](https://lists.samba.org/archive/ccache/2016q3/001451.html). 

I will get the parts that my port is missing from there :) 

I like the fact that next iteration of ccache will require C++11. One can then easily hide all the implementation details behind an abstraction layer and then we can have non ifdefed code easily.

**Comment by jrosdahl** [comment]
See also #447.

**Comment by cristianadam** [comment]
I've updated my [fork](https://github.com/cristianadam/ccache) to ccache version 3.7.7, and created [binary artifacts](https://github.com/cristianadam/ccache/releases) using GitHub Actions for Linux, macOS, Windows (MinGW).

My plan would be to use ccache to speed up building C++ projects using GitHub Action's [cache mechanism](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows).

I used a build yml file based on the one from [Using GitHub Actions with C++ and CMake](https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/).

**Comment by AlexanderLanin** [comment]
@cristianadam what are the open points (e.g. CI, docu) before this could be merged back?
I guess using ccache to speed up compilation of ccache is an optional step afterwards ;-)

**Comment by cristianadam** [comment]
@AlexanderLanin  judging from your recent PRs (https://github.com/ccache/ccache/pull/508 and https://github.com/ccache/ccache/pull/509) I assume you are using the CMake port to compile and hack ccache, right?

I haven't used ccache to speed up ccache at GitHub actions. I've document how it's done here: [Speeding up C++ GitHub Actions using ccache](https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/)

I'll let others comment about the missing points.

**Comment by AlexanderLanin** [comment]
I'm actually using the "normal workflow" as in #510, I'm hoping that CMake will improve some use cases  (e.g. native support from VSCode) but have not tried your port so far.

**Comment by jrosdahl** [comment]
@cristianadam wrote:
> I've updated my fork to ccache version 3.7.7, and created binary artifacts using GitHub Actions for Linux, macOS, Windows (MinGW).

Cool.

@AlexanderLanin wrote:
> what are the open points (e.g. CI, docu) before this could be merged back?

Like several other semi-large features/improvements, the CMake build support is simply something that I haven't really had time to think about or drive forward.

@cristianadam: Could you create a PR (against master) of your current work so that we can have something to look at and comment on?

**Comment by sfhacker** [comment]
Ciao.

I have just downloaded master branch and built ccache from source under MinGW on Windows 10.
No issues at all.

![image](https://user-images.githubusercontent.com/25817529/74471491-092d5380-4e7f-11ea-9678-4526047973b9.png)

![image](https://user-images.githubusercontent.com/25817529/74471947-ddf73400-4e7f-11ea-8d1b-c50566e62174.png)


Adding cmake support would be beneficial but perhaps not a priority.
