### ISSUE TITLE
Visual C++ / clang-cl support

### ISSUE THREAD

**Issue by cristianadam** [ccache/ccache#431]
My general understanding is that `ccache` uses the dependencies information provided by `-MD` compiler flags to determine if something changed for the current source file, and if the dependencies have not changed, and the compiler command line is identical then it will serve the object file from the cache.

The Visual C++ compiler has for a while now the [/showIncludes](https://docs.microsoft.com/en-us/cpp/build/reference/showincludes-list-include-files?view=vs-2019) parameter which is similar to `-MD` gcc/clang parameter.

This article from 2008 [How to Get Dependencies from /showIncludes](http://www.conifersystems.com/2008/10/09/dependencies-from-showincludes/) tells us that the Visual C++ compiler uses the stderr instead of stdout to display the includes, and it provides a python script which does the command line parsing.

A simple C hello world program like this:
```
#include <stdio.h>

int main()
{
    printf("Hello World\n");

    return 0;
} 
```
will output something like this:
```
$ cl /showIncludes hello.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

hello.c
Note: including file: C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
Note: including file:  C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt.h
Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vcruntime.h
Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\sal.h
Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\concurrencysal.h
Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vadefs.h
Note: including file:  C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wstdio.h
Note: including file:   C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
Microsoft (R) Incremental Linker Version 14.16.27027.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:hello.exe
hello.obj
```

Ninja build tool knows about this and they have their own parser for the output. CMake took the  ninja parser and built a tool `cmcldeps` which  ships with CMake on Windows since 2012 or so.

By running `cmcldeps` like this:

```
cmcldeps C hello.c hello.d hello.obj "Note: including file:" cl cl hello.c
```

I got the `hello.d` file:
```
hello.obj: \
C:\\Program\ Files\ (x86)\\Microsoft\ Visual\ Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\\concurrencysal.h \
C:\\Program\ Files\ (x86)\\Microsoft\ Visual\ Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\\sal.h \
C:\\Program\ Files\ (x86)\\Microsoft\ Visual\ Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\\vadefs.h \
C:\\Program\ Files\ (x86)\\Microsoft\ Visual\ Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\\vcruntime.h \
C:\\Program\ Files\ (x86)\\Windows\ Kits\\10\\include\\10.0.17763.0\\ucrt\\corecrt.h \
C:\\Program\ Files\ (x86)\\Windows\ Kits\\10\\include\\10.0.17763.0\\ucrt\\corecrt_stdio_config.h \
C:\\Program\ Files\ (x86)\\Windows\ Kits\\10\\include\\10.0.17763.0\\ucrt\\corecrt_wstdio.h \
C:\\Program\ Files\ (x86)\\Windows\ Kits\\10\\include\\10.0.17763.0\\ucrt\\stdio.h \
 ```

Testing with clang-cl I got the following result:

```
$ set PATH=%PATH%;c:\Program Files\LLVM\bin

c:\Temp
$ clang-cl /showIncludes hello.c
Note: including file: C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
Note: including file:  C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt.h
Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vcruntime.h
Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\sal.h
Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\concurrencysal.h
Note: including file:    c:\Program Files\LLVM\lib\clang\7.0.1\include\vadefs.h
Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vadefs.h
Note: including file:  C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wstdio.h
Note: including file:   C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
```

which when called with 
```
cmcldeps C hello.c hello.d hello.obj "Note: including file:" clang-cl clang-cl hello.c
```
resulted in:

```
hello.obj: \
C:\\Program\ Files\ (x86)\\Microsoft\ Visual\ Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\\concurrencysal.h \
C:\\Program\ Files\ (x86)\\Microsoft\ Visual\ Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\\sal.h \
C:\\Program\ Files\ (x86)\\Microsoft\ Visual\ Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\\vadefs.h \
C:\\Program\ Files\ (x86)\\Microsoft\ Visual\ Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\\vcruntime.h \
C:\\Program\ Files\ (x86)\\Windows\ Kits\\10\\include\\10.0.17763.0\\ucrt\\corecrt.h \
C:\\Program\ Files\ (x86)\\Windows\ Kits\\10\\include\\10.0.17763.0\\ucrt\\corecrt_stdio_config.h \
C:\\Program\ Files\ (x86)\\Windows\ Kits\\10\\include\\10.0.17763.0\\ucrt\\corecrt_wstdio.h \
C:\\Program\ Files\ (x86)\\Windows\ Kits\\10\\include\\10.0.17763.0\\ucrt\\stdio.h \
c:\\Program\ Files\\LLVM\\lib\\clang\\7.0.1\\include\\vadefs.h \
 ```

I have seen the work done with https://github.com/ccache/ccache/pull/162 and it's unfortunate that we didn't get Visual C++ support in ccache.

The hard part is to take into consideration all the Visual C++ / Clang-cl flags.

**Comment by jrosdahl** [comment]
Hi Cristian!

> My general understanding is that ccache uses the dependencies information provided by -MD compiler flags to determine if something changed for the current source file, and if the dependencies have not changed, and the compiler command line is identical then it will serve the object file from the cache.

Well, yes, but only in the [_depend mode_](https://ccache.dev/manual/latest.html#_the_depend_mode), which isn't enabled by default. The default method is to run the preprocessor and check its output, including which include files was read.

> I have seen the work done with #162 and it's unfortunate that we didn't get Visual C++ support in ccache.

I can totally understand that you and others think that it's unfortunate. But for me, it's liberating not having to spend my limited time on things I'm not interested in. Since you have seen #162, I guess you have seen [my response](https://github.com/ccache/ccache/pull/162#issuecomment-289215585) as well. What I wrote then is still accurate.

It's not only a matter of "getting Visual C++ support", it's about "getting Visual C++ support and then (for many years) maintain and fix bugs in the code and having to deal with the complexity cost brought by the increased design and test space".

As mentioned in my response to #162, a sibling "ccache for windows" project, run by others, would be great! Would you like to help with such an effort?

> The hard part is to take into consideration all the Visual C++ / Clang-cl flags.

Yes, but also general basic Windows-related things like how filenames, files and processes (and likely sockets in the future) are handled. Even keeping ccache just compiling on Windows is not trivial.

**Comment by cristianadam** [comment]
What Joel tried with #162 is to get ccache to support Visual C++, and at the same time build ccache itself with Visual C++.

I'm just interested in the former. I'm happy to build ccache with MinGW, and have support for Visual C++.

I only want to use the same caching tool cross platform.  I assume all these ccache clones:

 * [clcache](https://github.com/frerich/clcache) - written in Python
 * [cclash](https://github.com/inorton/cclash) - written in C#
 * [sccache](https://github.com/mozilla/sccache) - written in Rust
 * [buildcache](https://github.com/mbitsnbites/buildcache) - written in C++

were created because ccache was written in C, and the build and testing support was complicated to handle Windows / Visual C++.

As it turns out buildcache in written in C++, builds with CMake, and supports Visual C++. It might be wiser for me to just use buildcache, instead of trying to get ccache to do exactly the same thing.

**Comment by jrosdahl** [comment]
> What Joel tried with #162 [...]

Just to avoid confusion here: #162 was jd-gasquel's PR, not mine. The problem with #162 was that it was just too messy and intrusive to even begin considering.

> is to get ccache to support Visual C++, and at the same time build ccache itself with Visual C++. [...] I'm just interested in the former. I'm happy to build ccache with MinGW, and have support for Visual C++.

Thanks for the clarification.

> I assume all these ccache clones [...] were created because ccache was written in C, and the build and testing support was complicated to handle Windows / Visual C++.

Well, build and testing support, and being written in C, could very well be part of the motivation behind the projects you mention, but I doubt that they were the primary trigger. More likely reasons:

1. ccache doesn't have abstractions in place for extending it with other frontends and backends, so it's simply some hard and intrusive work that needs to be done to get it to work with other compilers or backends. Nobody has offered (or even mentioned interest) to work on improving abstractions to make such things possible in a reasonable way. (Note: Backend abstraction is now in the roadmap: #414.)
2. Since ccache has existed for a long time, it will have to move slower (to maintain backward compatibility, etc) than a new project can, given the same amount of developer resources. Most of my time for ccache is eaten up by various maintenance tasks and addressing issues and feature requests (such as this one :wink:) instead of actually having time to improve it myself. This is not a problem for a new project with no legacy.
3. It's fun to start a project yourself.

Regarding reason one: The situation would not be different if ccache had been written in C++ or any other language from start. The reason why there are no suitable abstractions in place is because ccache started out as a very small and straightforward hack in 2004 by Andrew Tridgell, who I assume only had the goal of making something that worked for the compilers and systems that were relevant for Samba at the time. Things like various attempts of Windows support, support for Clang, etc, were added in more or less hacky ways along the road.

Regarding reason two: I welcome more active developers on the team. If we were more, we could certainly take on bigger tasks. But as long as we are very few with limited time to spare, I just have to try to adjust my time resources accordingly. I hope that this makes sense to you.

If you or anybody else steps forward and want to work on abstracting the frontend code, _and to maintain Visual C++ parts of ccache_, then I'm all for it.

> As it turns out buildcache in written in C++, builds with CMake, and supports Visual C++. It might be wiser for me to just use buildcache, instead of trying to get ccache to do exactly the same thing.

I had not heard about buildcache before, but it looks like a nice project.

**Comment by afbjorklund** [comment]
So I guess we can close this now ? Seems like different platforms have some very different issues...

Says `clcache`:

> Included is a SQLite based version of the file cache, it is currently quite a bit slower than the normal file based cache but may be useful if your system is forced to use aggressive antivirus scanning.

My suggestion is to drop all Windows support (not MSYS2!) in ccache, and let it be handled properly.

**Comment by jrosdahl** [comment]
> My suggestion is to drop all Windows support (not MSYS2!) in ccache, and let it be handled properly.

Sounds OK from my perspective (but then again I'm not a Windows user and don't know details about the different Windows eco systems).

@cristianadam: What's your view on this? Would an MSYS2 version of ccache suffice, or is there a value in the MinGW version?

**Comment by afbjorklund** [comment]
We could drop MSYS2 support as well, if we don't want to handle things like missing symlinks.

**Comment by cristianadam** [comment]
@jrosdahl  At the moment I like not having to install MSYS2 just to compile ccache. Qt ships with MinGW compiler and it's all we actually need.

But as it turns out I will really need to have Visual C++ support, because of Clang-Cl.

If you decide to remove stuff I'll probably have to add it to my fork. :(

**Comment by afbjorklund** [comment]
> If you decide to remove stuff I'll probably have to add it to my fork. :(

But maybe that's a *good* thing, rather than it have stuck in a PR queue ?

And then you can set up proper support for CI (like Appveyor), instead of hoping.
I was trying to make it work using MinGW and WINE, but that only goes _so_ far...
Most of the remaining bugs can **only** be found/fixed on the actual Windows OS.
Personally I think keeping MSYS2 (Cygwin) is a reasonable/maintainable effort.

Having a MinGW version "would have been nice", but I'm not using Windows myself.

---

Anyway, the code that I had written (now abandoned) only catered for MinGW's [MSYS](http://www.mingw.org/wiki/MSYS).
Even though it did run on Windows, it still had a decent shell and a normal gcc compiler.
Thus it could still use autotools, and didn't have to handle all strange paths and params.
But even that is a lot of code and work, so it is much easier to stick to POSIX and [MSYS2](https://www.msys2.org/).

Note:
MSYS = Win32 = Windows
MSYS2 = Cygwin = POSIX

The Mingw-w64 env has support for both environments (three if you count 32-bit vs 64-bit),
which makes things rather confusing. It is also a full compiler toolchain, and not a shell.
So we use the two `w64-mingw32` cross-compilers to target the different Windows targets.
And that runs fine also on Linux, the main problem is doing proper testing - without Windows.

Thus:
MSYS != MSYS2
MinGW != Mingw-w64

**Comment by jrosdahl** [comment]
@cristianadam wrote:
> At the moment I like not having to install MSYS2 just to compile ccache. Qt ships with MinGW compiler and it's all we actually need.

Why is installing MSYS2 a problem? (Excuse me if the question is strange, I don't know much about the ecosystem you're in.)

I agree with @afbjorklund: Maybe it's a good thing if you would take over the Windows native parts since you're interested in them? Or maybe you want to help out maintaining Windows-related code in ccache?

**Comment by afbjorklund** [comment]
Basically MSYS2 is a nice POSIX emulator, if you **don't** like the Windows environment. Like [Cygwin](https://www.cygwin.com/).

**Comment by jrosdahl** [comment]
See also #447.
