### ISSUE TITLE
configurable path stripping

### ISSUE THREAD

**Issue by zmike** [ccache/ccache#439]
### Description ###

I've recently run into an issue when using the meson build system, though I imagine the scenario is not necessarily unique. When creating distribution tarballs, meson will:

1. Create a tmpdir (e.g., /tmp/tmp123456)
2. Unpack the source into this tmpdir
3. Create another tmpdir
4. Use this second tmpdir as the build dir

The result is that ccache is unable to work because the base path of the build directory is always different, resulting in differing `.d` files and a guaranteed cache miss. Since this is a fully encapsulated build, it's impossible to get the base path to use in the ccache config, and it's also not possible to predict it ahead of time.

Unless I'm mistaken, there is no no way to handle this at present?

My idea for solving the issue is to have a config option where I can do something like:
* set CCACHE_BASEDIR=/tmp
* set something like CCACHE_BASEDIR_STRIP=1, and then ccache will ignore one additional path after /tmp (e.g., with /tmp/path/build, /tmp/path will be treated as though it was set as CCACHE_BASEDIR)

What do you think about this idea? Or is there already another way to solve this kind of thing?

**Comment by jrosdahl** [comment]
Does the below script describe the scenario accurately enough?

```sh
#!/bin/sh

set -eu

src_dir=$(mktemp -d)
build_dir=$(mktemp -d)
trap "rm -rf $src_dir $build_dir" EXIT

touch $src_dir/test.h
echo '#include "test.h"' >$src_dir/test.c

export CCACHE_BASEDIR=/tmp
export CCACHE_SLOPPINESS="include_file_mtime,include_file_ctime"

cd $build_dir
CCACHE_LOGFILE=/dev/stdout ccache gcc -MD -c $src_dir/test.c | grep Result
cat test.d
```

There will be a cache miss every time the script is run since the path to test.h is different each time (`../tmp.$RANDOM/test.h`).

> The result is that ccache is unable to work because the base path of the build directory is always different,

Should "build directory" be "source directory" above or have I misinterpreted the scenario?

> Since this is a fully encapsulated build, it's impossible to get the base path to use in the ccache config, and it's also not possible to predict it ahead of time.

(Assuming you mean base_dir with "base path".) Just a note about base_dir: You only need to know a parent directory of the directories in question, and you already know that it's `/tmp` so I don't think that there's a problem here.

> What do you think about this idea?

I don't see how stripping paths like you suggest would fix the problem. The problem is that the *result* produced by ccache (the .d file in this case) has to be different each time, right? That won't be fixed by letting ccache ignore parts of the paths. Or is your suggestion to optionally let ccache produce incorrect .d files?

To fix the problem as I understand it, ccache would have to know how to produce a correct .d file from a previously cached .d file containing different source directory paths. That might be possible, at least in some simple situations. Needs more thinking. :slightly_smiling_face:

> Or is there already another way to solve this kind of thing?

Well, maybe Meson could be changed to use something like

```
/tmp/tmp.$RANDOM/sources/<sources>
/tmp/tmp.$RANDOM/build.$RANDOM/<build>
```

instead of

```
/tmp/tmp.$RANDOM1/<sources>
/tmp/tmp.$RANDOM2/<build>
```

? Then relative paths from the build directory to include files in the source directory will be stable.

**Comment by zmike** [comment]
Hey thanks for getting back to me. I wrote this ticket in a more Friday mode than usual, so there were some mistakes in the terminology used, but it seems like you understood the gist of it anyway!

The problem is indeed the .d files, and the script you wrote is roughly what is occurring; I was proposing stripping/changing the path for the .d files in a way that would prevent cache misses, though you'd know best about what exactly would be the most useful solution here.

I considered submitting the change that you suggested to meson, but it seems like this is an intentional feature for them and (in my head at the time) it would have been easier to make adjustments on this end.

I'll try making a ticket over there to see what they think.

**Comment by zmike** [comment]
It turns out that meson was much less opposed to changing this than I thought, so I'm going to close this since I don't have a direct need for the feature anymore. Thanks for the consult!

**Comment by jrosdahl** [comment]
OK, thanks! For reference, here's the Meson issue: https://github.com/mesonbuild/meson/issues/5583
