### ISSUE TITLE
ccache crashing when log_file set with 3.7.x (maybe earlier)

### ISSUE THREAD

**Issue by Shionigami** [ccache/ccache#454]
Hello.
I am trying to run ccache with GreenHills compiler, but, for some reason, it worked some weeks ago and I got now ccache internal issues.
Then I would like to generate a ccache log, but it makes the build crash on version 3.7.2 (which improved GHS compatibility). 
I did tests with the version 3.3.4, the log generation is working on that version. 

### How to reproduce ###

1. Setup log_file in the configuration
- Example: ccache -o log_file=ccache.log
2. Run any command
- Example: ccache -p

### Actual behavior ###

ccache crashes without any information...

### Expected behavior ###

Generate ccache log.

### Environment ###

ccache version 3.7.2 running on Windows 10 (tested with Windows Server 2012, same issue)

**Comment by cristianadam** [comment]
I had the same problem with my MinGW64 ccache build on Windows. The problem is that cacche can't access the config file, and it crashes.

With this commit https://github.com/cristianadam/ccache/commit/979f8bf3c82822462e2fa3f69afdf30dfc56249c I was able to get the config value up and running.

I haven't updated my ccache [fork](https://github.com/cristianadam/ccache/) to version 3.7.2, I will try to update it these days.

**Comment by jrosdahl** [comment]
> With this commit cristianadam@979f8bf I was able to get the config value up and running.

How about creating a pull request?

**Comment by Shionigami** [comment]
I will make some tests with 3.7.3 I get I set up the build environment and make some tests.

**Comment by Shionigami** [comment]
I have tested the fix and it works. 

@cristianadam could you please create the pull request? It would be really great to have this update in the next release =)

**Comment by cristianadam** [comment]
@Shionigami  I'll do a pull request. I'm just updating my CMake code to the lastest changes. I mostly have to remove stuff (e.g. gperf) 😄
