### ISSUE TITLE
Photos framework compilation errors when using ccache in Xcode 11

### ISSUE THREAD

**Issue by jingcaich** [ccache/ccache#463]
If import <Photos/Photos.h>, it Will generate a compilation error

Error info: "/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk/System/Library/Frameworks/Photos.framework/Headers/PhotosTypes.h:177:1: '#pragma clang attribute pop' with no matching '#pragma clang attribute push'"

Runing normally in xcode 10.

 So I deleted "CC" in user-define, everything is right.

**Comment by jingcaich** [comment]
1. ccache version 3.6
2. Apple LLVM version 10.0.0 (clang-1000.11.45.5)
3. Xcode 11

If import <Photos/Photos.h>, it Will generate a compilation error

Error info: "/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk/System/Library/Frameworks/Photos.framework/Headers/PhotosTypes.h:177:1: '#pragma clang attribute pop' with no matching '#pragma clang attribute push'"

Runing normally in xcode 10.

So I deleted "CC" in user-define, everything is right.

 I think it's Apple's bug

**Comment by jrosdahl** [comment]
> So I deleted "CC" in user-define, everything is right.

I didn't understand that part. What is "user-define", what happens when "CC" is deleted and what does "CC" stand for?

> I think it's Apple's bug

Sounds possible. It's also possible that Clang 10 or some other component of the Xcode 11 environment uses some feature that is incompatible with ccache.

There's nothing more I can do without more information, unfortunately.

**Comment by jingcaich** [comment]
Thank you.
