### ISSUE TITLE
Assembler directive .incbin not detected when CCACHE_UNIFY is set

### ISSUE THREAD

**Issue by jforissier** [ccache/ccache#497]
### How to reproduce ###

```
$ cat >test.S <<__EOF__
.incbin "/dev/null"
__EOF__
$ unset CCACHE_UNIFY
$ CCACHE_DEBUG=1 ccache gcc -c test.S
$ grep incbin test.o.ccache-log
[2019-12-10T17:47:52.312302 29710] Found unsupported .incbin directive in source code
```
This is expected behavior. Now:

```
$ CCACHE_UNIFY=1 CCACHE_DEBUG=1 ccache gcc -c test.S
$ grep incbin test.o.ccache-log
$
```

The absence of `incbin` in the log file is unexpected. It means that ccache could use a cached version of `test.o` although it shouldn't.

This behavior has caused me some distress :open_mouth: [1], and I see no reason to justify it. Any idea how to fix this?

[1] https://lore.kernel.org/linux-arm-kernel/f58c2c0e-ec82-6675-84e6-ad63fd93c8ff@forissier.org/

### Environment ###

ccache version 3.7.6

**Comment by jrosdahl** [comment]
Thanks for the bug report and sorry about the distress. The unify mode is kind of a niche option which I unfortunately have paid little attention to.

I've now tried to evaluate the state of the unify mode and it's not very good:

1. The direct mode doesn't work if the unify mode is enabled. #99 (ccache 3.4) was supposed to make it work but it doesn't.
2. The `.incbin` directive detection added for #136 (ccache 3.3.3) has no effect when using the unify mode, which you regrettably found out the hard way.
3. The unifier doesn't understand [C++11 raw string literals](https://en.cppreference.com/w/cpp/language/string_literal) (form number 6), so there's a (small) risk of false positive cache hits. For instance, `char x[] = R"foo("bar")foo";` and `char x[] = R"foo("bar ")foo";` (note the space after "bar")) will be considered identical. I wouldn't be surprised if there are more issues for new C++ syntax.
4. The unifier ignores comments, but comments may have semantic meaning to modern compilers, e.g. ["fall through" comments](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough_003d) so comments shouldn't be ignored.

The fix of problem 3 is to improve the unifier's tokenization algorithm, but since it's a bit tricky I think that it likely won't be worth the effort, especially not as a bug fix. Disabling the unify mode for C++ therefore seems appetizing.

Problems 1 and 2 both have to do with different code paths for the unify case and the normal case. Both hash the preprocessor output but only the latter does things like making notes of included header files (for the direct mode) and workarounds like the `.incbin` detection. To do this properly the two code paths need to be unified (pun intended), which is doable but not as a bug fix in the stable 3.7.x series, I'd say. Therefore I'll likely just disable or remove the unify mode in the next bug fix release.

I'm also tempted to _not_ try to fix and reintroduce the unify mode in the next major version since its usefulness seems quite limited to me:

* It's only applicable when not using `-g`.
* It won't be enabled for C++ unless somebody fixes problem 3.
* It can make line numbers in warning messages and `__LINE__` expansions incorrect.
* Since comments should not be ignored, the unify mode can only make a difference for some types of whitespace changes, like adding or removing blank lines or changing `a+b` to `a + b`. (`a ` ` + b` is already normalized to `a + b` by the preprocessor.)

@jforissier: Since you're a current user of the unify mode, what's your take on this?

**Comment by jforissier** [comment]
@jrosdahl thanks for the detailed state of affairs! It's not very good indeed.

> Thanks for the bug report and sorry about the distress. 

No worries :wink: `ccache` has certainly saved me a lot of time over the years I've been using it, even considering the time I spent troubleshooting this bug!

> The unify mode is kind of a niche option which I unfortunately have paid little attention to.
> [...]
> Since you're a current user of the unify mode, what's your take on this?

In fact, I've been using this option for general work (including kernel build...) when I shouldn't have used it. However, for me, there is one circumstance which really benefits from unify mode, it is continuous integration builds. In this scenario, for me, the `.incbin` bug is not a problem (I am not building any file with an `.incbin` directive, at least for now).

I maintain the [OP-TEE OS project](https://github.com/OP-TEE/optee_os) and like many other projects I have set up a CI loop to check the pull requests. One step consists in building for various platforms and configurations. For example, [here](https://app.shippable.com/github/OP-TEE/optee_os/runs/4063/1/console) you can see the log of a Shippable run. Check the `build_ci` step: it has 116 lines which only differ in the makefile macros that are set on the command line. From a compiler perspective, all it does is change the content of a generated header file called `out/include/generated/conf.h`.

For instance, one `conf.h` might look like this:
```C
#define PLATFORM_vexpress 1
#define PLATFORM_FLAVOR_qemu_virt 1
/* ... other defines ... */
```
...and another one might be:
```C
#define PLATFORM_hikey 1
#define PLATFORM_FLAVOR_hikey960 1
/* ... other defines ... */
```

By using `ccache` in unify mode, I can benefit from "cross-platform" caching: if a source file does not depend on the `PLATFORM_*` macros, then it can be shared between builds for all platforms. Without unify more, the pre-processed output will differ and a cache hit will not occur. Same goes for other compile-time settings (`CFG_xxx` macros).

It is a long time since I experimented with this, but if I recall correctly, unify mode significantly improves the build time in my case. Also, disabling it would probably require to increase the cache size which can be problematic because the build system will take more time to retrieve the cache contents into the container environment, partially negating the benefit of caching.

**Comment by jrosdahl** [comment]
Thanks.

> [...] From a compiler perspective, all it does is change the content of a generated header file called `out/include/generated/conf.h`.
> 
> For instance, one `conf.h` might look like this:
> 
> ```c
> #define PLATFORM_vexpress 1
> #define PLATFORM_FLAVOR_qemu_virt 1
> /* ... other defines ... */
> ```
> 
> ...and another one might be:
> 
> ```c
> #define PLATFORM_hikey 1
> #define PLATFORM_FLAVOR_hikey960 1
> /* ... other defines ... */
> ```
> 
> By using `ccache` in unify mode, I can benefit from "cross-platform" caching: if a source file does not depend on the `PLATFORM_*` macros, then it can be shared between builds for all platforms. Without unify more, the pre-processed output will differ and a cache hit will not occur. Same goes for other compile-time settings (`CFG_xxx` macros).

I don't quite understand the scenario. Differences in `#define` directive values don't affect the hash of the preprocessed output, so there will (assuming the `#define`s don't affect other code) be preprocessed hits for your example snippets regardless of whether the unify mode is enabled. Perhaps you could give a more concrete example?

**Comment by jforissier** [comment]
My mistake. When I enabled the unify mode (and thought it allowed better caching in the example I showed above), I also made another change which was to remove the `-g3` compiler flag... It turns out unify mode has no impact, it is in fact `-g3` that prevents proper re-use of cached files, because with `-g3` the `#define`s in header files do remain in the pre-processed output (`-g` is fine though):

```
$ echo '#define FOO 1' | gcc -x c -E - | grep '#define FOO 1'
$ echo '#define FOO 1' | gcc -x c -g3 -E - | grep '#define FOO 1'
#define FOO 1
$
```

All in all, I have no use for the unify mode, and now I tend to agree with you about the limited usefulness of this mode.
