### ISSUE TITLE
ignore -gsplit-dwarf with LTO

### ISSUE THREAD

**Issue by Trass3r** [ccache/ccache#623]
Neither gcc nor clang generate a .dwo if LTO is active (`-flto[=thin]`) which invalidates the cache.

**Comment by jrosdahl** [comment]
> which invalidates the cache.

I'm not 100% sure what you mean by this. I guess it's likely that you talk about how some 3.7.x version behaves, and yes, if the `.dwo` file cannot be found then the latest released ccache will fall back to just run the compiler and not put the result in the cache. This is not invalidation of the cache, it's that ccache gives up. :slightly_smiling_face:

This has been improved on the master branch and ccache should handle a missing `.dwo` file correctly without giving up. I don't think it's a good idea to ignore `-gsplit-dwarf` if `-flto` is given since any other behavioral change implied by `-gsplit-dwarf` (now or in a future compiler version) then won't be detected.

**Comment by Trass3r** [comment]
Sure, wrong wording then. Sounds good. Looking forward to the next release.
