### ISSUE TITLE
Let CCACHE_UMASK apply only to files/directories in the cache directory

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [ccache/ccache#628]
Hi,

It happens that in our organization, we have been following the advices to use a shared ccache folder, and configure CCACHE_UMASK environment variable so all users in our group have write right on files generated by other people in that group. It also happens that we do call "g++" both for compiling objects, and for linking them into an executable/library, and in both cases the "g++" binary found is the ccache wrapper. As a result, I have just noticed that our final executables/libraries do also have been chmod according to the umask allowing group modifications. I find a bit strange that my final .so file can be modified by others, while this file will never be shared.

Reading a bit the code, it seems you parse options, and usually when you know it will be too hard to handle, you mark them as TOO_HARD. Eventually, in `process_args` this causes an early return, with a non zero error code, which triggers a call to `failed`. In `failed`, you either exit immediately, or fallback to using the real compiler and do no caching at all. I do expect that when we link, this is the actual code path that is being executed. Do you think you could save the `orig_umask` in `set_up_config` (instead of ignoring the return of `umask`), and use again this `orig_umask` to restore correct umask in `cache_compilation` ? This way I hope our executable/binaries would have expect chmods.

Cheers,
Romain

**Comment by AlexanderLanin** [comment]
I personally think the most interesting part here is how to set up a test for that to even reproduce the problem.
Obviously not manually ;-)
Probably via a prepared docker image which has several users?
Or run a detection of "testuser_1" and "testuser_2" and only execute the test if both are there.
Or create a script that would create those users?
...

**Comment by jrosdahl** [comment]
> As a result, I have just noticed that our final executables/libraries do also have been chmod according to the umask allowing group modifications.

Right, `CCACHE_UMASK` applies to all files created by ccache. This includes object files created from your compilations, [as documented](https://github.com/ccache/ccache/blob/10573efc80bc4df5052c9331244041cf4385d9b2/doc/MANUAL.adoc#user-content-config_umask), and also other output files.

> it seems you parse [...]

It has been this way since ccache v2.3 (75dd382407a36b3ebab36bb1027eb43a07498bec) many years before I got involved so I'm not sure about the reasoning, but my guess is that it was the simplest way to do it. In other words, this is not only related to `TOO_HARD` but to all files produced by ccache. I agree that it would be good if `CCACHE_UMASK` would only apply to files in the cache and not to the ones written outside the cache directory. Changing the issue title accordingly.

**Comment by jrosdahl** [comment]
When investigating this, I found two related bugs:

1. `CCACHE_UMASK` is not used when creating the initial configuration file.
2. `CCACHE_UMASK` is used when creating the log file.

**Comment by jrosdahl** [comment]
> I personally think the most interesting part here is how to set up a test for that to even reproduce the problem.

I'll test it by simply verifying the created file and directory permissions. Sounds OK?

**Comment by AlexanderLanin** [comment]
> Sounds OK?

Sure. I thought it was a more interesting bug ;-)
