### ISSUE TITLE
Ccache ignores max_size

### ISSUE THREAD

**Issue by s-rath-mxn** [ccache/ccache#634]
Hi,

I am using ccache on two macOS machines with the following configuration `/Users/foo/.ccache/ccache.conf `

```
max_size = 25G
```

It resolves to (Please ignore the low cache hit rate for the moment)

```
cache directory                     /Users/foo/.ccache
primary config                      /Users/foo/.ccache/ccache.conf
secondary config      (readonly)    /usr/local/Cellar/ccache/3.7.9/etc/ccache.conf
stats updated                       Tue Aug 11 15:37:38 2020
cache hit (direct)                  3427
cache hit (preprocessed)               5
cache miss                       1253454
cache hit rate                      0.27 %
compile failed                         5
preprocessor error                     3
cache file missing                     7
cleanups performed                 96281
files in cache                      2071
cache size                           5.3 GB
max cache size                      25.0 GB
```

It says the cache size is 5.3 GB, but this is the actual size of  the cache:

![image](https://user-images.githubusercontent.com/65028513/89904170-99dab700-dbb6-11ea-8ebd-33785fd58932.png)

There are no configurations overwritten/set through command line, so I am wondering why the cache limit seems to be ignored. I deleted the entire cache and rebuilt it, still it goes back to over 250GB. Is this a known bug, or actually a misconfiguration?

Thank you!

**Comment by jrosdahl** [comment]
> I deleted the entire cache and rebuilt it, still it goes back to over 250GB.

Does a rebuild of your software produce around 250 GB object files? Or is 5 GB a more reasonable figure? Would it be possible for you to check the contents of the cache to see what it looks like, maybe using something like `find /Users/foo/.ccache -ls`?

> Is this a known bug, or actually a misconfiguration?

Neither.

The automatic cleanup mechanism kicks in when _cache size_ reaches _max cache size_ (or actually at approximately 90% of _max cache size_). Since ccache thinks that it has placed 5.3 GB in the cache (much smaller than 25.0 GB) no cleanups will be triggered. On the other hand:

> cleanups performed                 96281

This number looks very large, so there are several strange things:

* Why have so many cleanups been performed? This either indicates that you have had the cache for a very long time with a much too small cache size, or that ccache's bookkeeping is completely messed up.
* Why does ccache think that there are 2071 files totalling 5.3 GB in size if there actually is around 101802 files totalling 218.47 GB? That also indicates that the bookkeeping is messed up.

What happens if you run `ccache -c` to force a cleanup? Then ccache will recount the number of files and their sizes in the cache and update the counters accordingly, potentially also deleting files until the size is under _max cache size_.
