### ISSUE TITLE
Skipped test cases lead to false negatives

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#638]
It seems skipping tests is dangerous as it's not always clear why some test is skipped and whether that is correct. All skipped tests are reported as passed. At least for CI that's a risk: Due to missing dependencies tests could be skipped unintentionally and noone would ever notice.

Ideas so far:
* Add a allow list for tests that are allowed to be skipped.
* Add a list for tests that are expected to be performed, e.g. the CUDA job expects the CUDA tests to be performed.
* Do not skip on CI at all.

**Comment by jrosdahl** [comment]
Agreed, it's a risk, especially since the reason for skipping a test suite now is hidden (because of running via CTest). I don't think it's a very high risk, though. A similar issue was that the "Build documentation" and "Build manpage" jobs didn't do what was intended (see 3c1b39779691). As I see it one must always be suspicious and prepared for tests not actually doing what they are supposed to – it's difficult or at least tedious to write tests of the tests. That said, adding some allow list mechanism sounds OK.

> Do not skip on CI at all.

Not sure how this could be an option?

**Comment by AlexanderLanin** [comment]
Ok I'm not talking about those jobs as they have no tests ;-)

But a good example is the CUDA job when ccache first moved to GitHub Actions. It was not installing CUDA. The CUDA tests were skipped because CUDA is not installed. Skipped tests are ok.
So while CI had tests in place they simply did not execute and did not catch the bug.

**Comment by jrosdahl** [comment]
> Ok I'm not talking about those jobs as they have no tests ;-)

(You didn't quote anything so I'm not sure what you're referring to, but I'm gussing the "Build documentation" and "Build manpage" jobs I mentioned?)

I know. But I wanted to highlight that I think that "build tests" also should be considered tests, so I don't quite buy that those are not part of the discussion.

> But a good example is the CUDA job [...] did not execute and did not catch the bug.

That was clear from your initial description.

**Comment by jrosdahl** [comment]
@AlexanderLanin: Do you think that there is something actionable here?

**Comment by AlexanderLanin** [comment]
I don't see any easy fix here and it's not a high problem area. I'm closing this.
