### ISSUE TITLE
Corrupted dependency file

### ISSUE THREAD

**Issue by dyadav7** [ccache/ccache#671]
### Actual behavior ###

The dependency files is corrupted. It contains the binary characters.
 I am using ccache over NFS. I am using different object file names with -MD/-MMD. (#592) 
I guess two ccahce process running on 2 different hosts are writing to same dependency file (NFS) at same time. This may be causing file to be corrupted.  Is there some lock mechanism to avoid this issue ?

make command shows these error after .d files is corrupted. The .d file contains binary characters.
```
file1.d:33: warning: NUL character seen; rest of line ignored
file2.d:34: warning: NUL character seen; rest of line ignored
file3.d:35: *** missing separator.  Stop.
```

### Expected behavior ###

.d file should contain text characters only.

### Environment ###

ccache version master.b25ee490

gcc 5.4 and Centos 6.8.

**Comment by jrosdahl** [comment]
Thanks for the bug report.

I notice that you removed the _"How to reproduce"_ part of the bug report template. Is this because you can't reproduce the issue?

Here's what happens on a cache miss:

1. The compiler creates an object file and dependency file.
2. ccache reads the content of those files and writes the content to a single temporary file (with a unique name) in the cache. The file has an appended checksum of the content.
3. ccache renames the temporary file into the final "result" file in the cache. No lock mechanism is used since it's not needed because [renaming is atomic](https://en.wikipedia.org/wiki/Rename_(computing)). Thus, if two ccache processes want to write to the same result file at the same time, only one will remain and it will not be corrupted.
4. (ccache updates statistics in a "stats" file. Locking is used here to avoid losing any counter updates.)

In step 1, the dependency file could become corrupted if several compilers write to the dependency file location at the same time, but that would happen even if ccache isn't used.

The dependency file could also become corrupted if there is some bug when ccache reads the dependency file content and stores it in the result file. From code inspection I actually found one issue, fixed in d53af3e59e1 (see commit message for details). I don't think it's likely that this was the root cause of your problem, but I guess it cannot be ruled out.

If the dependency file in step 1 is not corrupted then it could become corrupted if the temporary filename in step 2 is not unique when several ccache processes run at the same time. ccache uses [`mkstemp`](https://man7.org/linux/man-pages/man3/mkstemp.3.html) to create a unique filename, so if the libc (not likely) or the NFS setup is broken it could happen. But: if this happens then the checksum will be incorrect and ccache won't use the result.

Here's what happens on a cache hit:

1. ccache reads the result file.
2. While doing so, the checksum is verified. If the checksum is incorrect the result won't be used.
3. ccache potentially adjusts the dependency file content as you know from #592.
4. ccache writes to the destination dependency file. This is done just like the compiler would: just plain writing to the file. No locks are used.
5. (ccache updates statistics in a "stats" file. Locking is used here to avoid losing any counter updates.)

For corruption to appear on a cache hit, either the dependency file was corrupted when creating the result file (on a previous cache miss) or there is a bug when ccache reads content from the result file and writes to the destination file. If two ccache processes write to the same destination file at the same time the file could become corrupted, but that would happen if running without ccache as well.

To narrow down what happens we need to check if the content in the result file is good or bad. Here's how you can do that:

1. Identify which result file is used. This is done by reading the log file, either from `CCACHE_DEBUG` or `CCACHE_LOGFILE`. Look for _"Stored in cache"_ (on cache miss) or _"Reading result"_ (on cache hit).
2. Unpack the result file with `ccache --extract-result ...`.
3. Investigate the dependency file (`ccache-result.d`).

**Comment by dyadav7** [comment]
Thanks for sharing so much detail.

I will debug the issue if it happens again. I forcibly updated the ccache by using CCACHE_RECACHE to fix the issue.
I will update the ccache version and then report if any issues found.

**Comment by dyadav7** [comment]
Hi

This issue did not happen for me after ccache updates at that time.
I did not have steps to re-create as issue is so random

Thanks
Deepak
