### ISSUE TITLE
ccache ccache gcc ... no longer works

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#686]
### How to reproduce ###

1. `touch empty.c`
2. `ccache ccache gcc -c empty.c`

### Actual behavior ###

```
ccache: error: Recursive invocation (the name of the ccache binary must be "ccache")
```

### Expected behavior ###

No error, even though the command line is silly. This is because it worked before ccache version 4.0.

### Environment ###

ccache version 4.0

**Comment by AlexanderLanin** [comment]
In the old behavior ccache(1) was actually calling ccache(2). If we care about this use case this should also be fixed. I'll try.

While the command line is silly I actually can imagine it happening due to wrappers over wrappers which handle compilation (e.g. something custom + via cmake). At least me personally, I'm just happy when it works and I don't clean it up properly.
