### ISSUE TITLE
-fcolor-diagnostics not passed to GCC, causing false positive compiler probing

### ISSUE THREAD

**Issue by trofi** [ccache/ccache#711]
It's a forward of downstream https://bugs.gentoo.org/751463 report by Mihai Moldovan where `-fcolor-diagnostics` was detected by `ccache gcc -c` as supported (compile only) but failed at `ccache gcc` (link).

Minimal example of a deviation:

```
$ touch a.c
$ ccache /usr/bin/gcc-11.0.0 -c -fcolor-diagnostics a.c
$ /usr/bin/gcc-11.0.0 -c -fcolor-diagnostics a.c
gcc-11.0.0: error: unrecognized command-line option '-fcolor-diagnostics'
```

Larger example with a linker:

```
$ echo 'int main(){}' > b.c
$ ccache /usr/bin/gcc-11.0.0 -c -fcolor-diagnostics b.c
$ ccache /usr/bin/gcc-11.0.0 -fcolor-diagnostics b.o -o b
gcc-11.0.0: error: unrecognized command-line option '-fcolor-diagnostics'
```

Would be nice if `-fcolor-diagnostics` was passed through in both cases or filtered out in both cases.

**Comment by Ionic** [comment]
> Would be nice if `-fcolor-diagnostics` was passed through in both cases or filtered out in both cases.

Filtering flags or mangling them is very dangerous and can lead to subtle breakage in other applications (e.g., applications that test if compilers support specific flags or not).

Currently, ccache is transforming `-fcolor-diagnostics` into `-fdiagnostics-color` for GCC in compile-only mode (and leaves it alone otherwise) - and exactly that mangling is causing problems down the road.

IMHO, ccache should strive to be as transparent as possible and not mangle any command line arguments. ccache itself is almost exclusively controlled via environment variables, which is totally safe.

Also note that the whole `-fcolor-diagnostics` thing was one specific instance of the problem. I believe that there are other flags that are being mangled as well, but I didn't look through the source code or tried to debug this very hard. It seems to be a regression in 4.0, while earlier versions didn't show such behavior, so probably a falldown from a new feature.

**Comment by jrosdahl** [comment]
Thanks for the bug report.

@Ionic wrote:
> Currently, ccache is transforming `-fcolor-diagnostics` into `-fdiagnostics-color` for GCC in compile-only mode (and leaves it alone otherwise) - and exactly that mangling is causing problems down the road.

Just to clarify: When you say "mangling" it sounds like the behavior is deliberate, but it's not – it's just a bug.

> IMHO, ccache should strive to be as transparent as possible

I don't think anybody has a different opinion. The keyword here is "possible"; ccache's behavior is a balancing act of being as transparent as possible while still providing value. In some cases 100% transparency is impossible.

> and not mangle any command line arguments.

If you by "mangle" (and "filtering" earlier) mean "not exactly replicate the command line", then that it simply not possible. There are edge cases and special modes where ccache has to pass other, fewer or more arguments in order to function properly.

**Comment by whitslack** [comment]
@jrosdahl: The solution you implemented here has a problem. If a cached result exists for the source file and command line (omitting color arguments), then a passed `-fcolor-diagnostics` argument is not rejected.

Example:
```
$ cat >a.c <<EOF
int main() { return 0; }
EOF

$ /usr/lib/ccache/bin/x86_64-pc-linux-gnu-gcc -c a.c

$ /usr/lib/ccache/bin/x86_64-pc-linux-gnu-gcc -fcolor-diagnostics -c a.c
```
The `-fcolor-diagnostics` option is not rejected as it should be since the cache already contains an entry for that source file and command line with the option omitted.

This causes problems for CMake, which tests the validity of numerous compiler options by attempting to compile the same trivial source file. When it attempts to check the validity of the `-fcolor-diagnostics` option, the command line matches one that it has already tested, so the test succeeds even though it ought to fail.

**Comment by jrosdahl** [comment]
@whitslack: Thanks for noticing this and for the example.
