### ISSUE TITLE
Refactor suggestion: split up Context class

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#715]
I'm writing this as a point of discussion before investing effort into attempting to improve the situation. At least I believe I'm talking about an improvement here. Why? Readability currently suffers regarding Context.
It's usually unclear whether `Context&` goes in to a function or comes out, to be more precise it's usually different for the different parts of Context. Any change to the code always involves carefully looking throw where some Context member is actually being written and where it is being read. This can be made obvious by function signatures.
It feels like it would be much easier if ccache didn't have one huge 'Context' object. Maybe it will remain there - but smaller. Some parts of Context do not need to be there and can be extracted. Maybe as separate variables maybe as new structs. I have not yet attempted to do so, so I do not have a clear vision on it.
Passing a single parameter and hiding everything in there saves some characters in code, but less code does not imply better readability.

Would you agree?
Is Context just what happened to previously global variables and I'm simply talking about the natural next step of improvement?

**Comment by jrosdahl** [comment]
> Is Context just what happened to previously global variables and I'm simply talking about the natural next step of improvement?

Yes. Quoting myself from a discussion with @totph when he wanted to introduce a `Context` or `State` class to get rid of as much global state as possible: _"I remember having plans to refactor away global state shortly after I took over ccache maintainership, but then it simply didn't happen. I haven't thought much about global state lately, but I would spontaneously say that collecting all currently global variables into one structure would not be the end goal since not all global state need to have the same life time and visibility."_ When he asked about what substructures there should be, the only one that was obvious to me at the time was what ended up in `ArgsInfo` (those variables were also file-level globals in ccache.cpp before). There was no time to consider what could be done in more detail since it would have stalled other development for a very long time.

**Comment by jrosdahl** [comment]
@AlexanderLanin: Are you happy with my answer? Anything more to add before closing the issue?

**Comment by AlexanderLanin** [comment]
Yes. In case I ever find time for this, I'll work on it. Because I truly believe in the benefits of testable / understandable code.
