### ISSUE TITLE
Test suite is running only CC

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#716]
### How to reproduce ###

1. Via `test/run`
2. Or via `CC=clang test/run`
3. Or via CI

### Actual behavior ###
Only CC compiler is used (fallback to gcc. why not to cc?)

### Expected behavior ###
Use TEST_COMPILER or something, do not use CC only.
In CI it may even be a good approach to test gcc, g++, clang, clang++ in every environment (as available) in addition to TEST_CC/CC.

### Environment ###
current master

### Note ###
`CC=g++ ../test/run` and `CC=clang++ ../test/run base` currently fail.

**Comment by jrosdahl** [comment]
I don't quite understand why you think that this is a _bug_. The test suite is written to test ccache using a C compiler, so why should it _not_ use `CC`? The "C or C++-ness" of the compiler is not what is important here, it's which parts of ccache you can exercise with the chosen compiler.

> fallback to gcc. why not to cc?

Because the test suite doesn't work with any `cc`, for instance the Intel and Solaris compilers. At least that was the reason in back then (258bee6250839ff83dfa10f9ed7293fde5447688).

**Comment by jrosdahl** [comment]
@AlexanderLanin: Does my reasoning sound fair or is there some aspect to this that I don't see? Can the issue be closed?

**Comment by AlexanderLanin** [comment]
> The "C or C++-ness" of the compiler is not what is important here, it's which parts of ccache you can exercise with the chosen compiler.
Agreed. Are we sure the C++ compilers behave the same way? Basically there is no test verifying the C++ compilers even work with ccache. But if they behave exactly the same as the C versions that's fine.

Although if they do behave the same, tests should not fail when I run them as described above ?!

Are there no features that are C++ specific? e.g. C++20 modules.

**Comment by jrosdahl** [comment]
> Are we sure the C++ compilers behave the same way?

They don't behave the same way, which is why the tests fail. :wink:  The color_diagostics suite fails because `-Wmissing-prototypes` (used by the test suite) is rejected by the C++ compilers. The direct suite fails because C++ compilers don't like to convert a string constant to a non-const pointer. The pch suite fails since it uses `-x c-header`, which (it seems) makes the C++ compilers not want to use the precompiled header. Some tests in the base and nocpp2 suites fail with clang++ since it warns about deprecated behavior when used as a C compiler which messes up stderr from the preprocessor. The two first are easy to fix, though.

> Basically there is no test verifying the C++ compilers even work with ccache.

Right, I don't mean to imply that we never should use a C++ compiler for testing. If we want to exercise C++-specific features or behavior then the test suite can take an _additional_ `CXX` variable with the C++ compiler so that both are available. This is similar to the CUDA compiler which is an additional compiler used by the test suite.

My gut feeling, which may be wrong, is that the gain of running the full test suite for both C and C++ compilers would be limited. Targeted tests are fine.

**Comment by jrosdahl** [comment]
@AlexanderLanin: Are you happy with my answer? Anything more to add before closing the issue?

**Comment by AlexanderLanin** [comment]
Yes, I think you analyzed this in detail already. I agree with the answer.
