### ISSUE TITLE
Make colored warnings work for GCC when invoked as "c++" rather than "g++"

### ISSUE THREAD

**Issue by pfee** [ccache/ccache#718]
### How to reproduce ###

1. Create a C++ source file with warnings/errors.
2. Compile with "ccache c++ bad.cpp"
3. Compile with "ccache g++ bad.cpp"

### Actual behavior ###
When the compiler is invoked as "g++", error messages have colors as expected.  When the compiler is invoked as "c++", errors lack color.

### Expected behavior ###
/usr/bin/c++ and /usr/bin/g++ are often symlinks to a specific version of GCC, e.g. g++-10

These two names should both produce the same colored output.

### Environment ###
OpenSUSE Leap 15.1
ccache version 4.0

ccache version 4.0 was manually built from source in order to benefit from the fix to issue #224

Testing with ccache 3.4.2, output lacked color for both "c++" and "g++".  Upgrading to ccache 4.0, colored output is produced when using "g++", but not "c++".

This is not an issue with "cc" and "gcc" when compiling C code.  Both of these produce colored output.

**Comment by jrosdahl** [comment]
Right, this is a known limitation. Compiler detection (or rather: guessing) is currently done by inspecting the compiler filename. We can't assume that `cc` or `c++` means GCC. However, we could speculatively pass `-fdiagnostics-color` to the compiler and fall back to not using it, just like we do for pre-4.8 GCCs. I'll think some more about this.

> This is not an issue with "cc" and "gcc" when compiling C code. Both of these produce colored output.

Are you sure about `cc`? `cc` doesn't produce colored output for me when run via ccache.

**Comment by pfee** [comment]
Ok, ignore the part about cc/gcc, I'm getting inconsistent results when comparing various scenarios.

For the main issue (identifying c++ as g++), would it be feasible to examine the compiler executable, detect and follow the symlink?  For example if the compiler is specified as /usr/bin/c++ and that's a symlink to g++-10, then that provides more data that would help ccache determine if GCC is being used.

If the compiler is specified as just "c++", then the path would need followed first in a fashion similar to "which c++" shell command.

Another option, invoke the compiler with --version and look for output that would help identify it as GCC.
```
$ c++ --version
c++ (SUSE Linux) 10.2.1 20200825 [revision c0746a1beb1ba073c7981eb09f55b3d993b32e5c]
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ clang --version
clang version 10.0.1 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
Would the "Copyright.*Free Software Foundation" portion be sufficient to identify GCC?

Symlink following and "--version" output may help collect information to guide compiler detection.  Would these help solve this bug?

**Comment by jrosdahl** [comment]
> For the main issue (identifying c++ as g++), would it be feasible to examine the compiler executable, detect and follow the symlink? For example if the compiler is specified as /usr/bin/c++ and that's a symlink to g++-10, then that provides more data that would help ccache determine if GCC is being used.

Yes, following symlinks will help if c++ actually is a symlink (chain) to something with a more specific name. I would however prefer to make it work even if the compiler name does not resolve to something more specific, for instance if it's a generically named wrapper script that happens to run g++. This is why I mentioned reusing the already existing solution. But since following symlinks would improve compiler guessing for other purposes I'll look into that as well.

> Another option, invoke the compiler with --version and look for output that would help identify it as GCC.

Introducing compiler version probing comes up now and then, but I would like to avoid that if possible. The main reason is that probing calls are a bit costly and also comes with some complexity.

**Comment by jrosdahl** [comment]
Update after having slept on this: While sending the `-fdiagnostics-color` probe for any (non-Clang) compiler likely will work, I don't feel 100% confident that it won't mess up a use case for some compiler I don't know about, so I'll go with the follow symlinks method suggested by @pfee. I'll also add a way to set the compiler type explicitly so that it will be possible for a wrapper script to override the default compiler guess.

**Comment by pfee** [comment]
Thank you Joel.  I downloaded and built the code from master 755359d9.  It fixes the issue I reported.
