### ISSUE TITLE
ccache 4.0 issues building from /tmp on macOS

### ISSUE THREAD

**Issue by ohierro-verimatrix** [ccache/ccache#724]
After upgrading ccache from 3.7.9 to 4.0 on our macOS Jenkins nodes, some Xcode based builds started failing due to an error like the following:

`error: unable to open output file '../../../../../tmp/workspace/project_master/DerivedData/project/Build/Intermediates.noindex/project.build/Debug-iphonesimulator/target.build/Objects-normal/x86_64/object.o': 'No such file or directory'`

The `../../../../../` bit immediately caught my attention. We set `CCACHE_BASEDIR` dynamically to the project's current root folder (eg: `/tmp/workspace/project_master` when building with Jenkins) so that the cache can be shared across builds of different branches of the project. Therefore all the file paths passed by Xcode are rewritten by ccache to be relative to the project's root.

Upon further investigation, the issue seems to be related to `/tmp` actually being a symlink to `/private/tmp` on macOS. From the debug logs it seems that ccache 4.0 always sets its CWD to `/private/tmp/[...]` while our basedir is being set to `/tmp/[...]`. To fix the compiler error above we can resolve the symlink and set the basedir to `/private/tmp/[...]`, but then none of the absolute file paths passed by Xcode will be rewritten because they will no longer begin with the basedir, and so the cache sharing does not work. Note that as far as I can tell Xcode always uses uses `/tmp/[...]` for the absolute file paths passed to the compiler, even if you `cd` to e.g. `/private/tmp/workspace/project_master` and open the Xcode project from there.

ccache 3.7.9 definitely did not have this issue. I presume that it didn't resolve the symlink in the current working dir and then everything matched and worked nicely.

Note: this issue is not reproducible when building the same project in the same way on our dev machines, e.g. with the project located under `/Users/user/dev/project`.

**Comment by AlexanderLanin** [comment]
Is it exactly the same problem when you create a symlink e.g. from /Users/user/project to /Users/user/dev/project?
Sounds easy enough for us to set up a failing test following those instructions.

**Comment by jrosdahl** [comment]
Thanks for the bug report. The problem is most likely related to e8444a3893cb339d97e25fd70496e448b3da18bb.

A ccache log of the failure (set `log_file` in the config or the `CCACHE_LOGFILE` environment variable and locate the failing compilation) would be very valuable.

An even more valuable thing would be a minimal (or small enough) self-contained example that reproduces the failure. Is this something you could construct?

> ccache 3.7.9 definitely did not have this issue.  I presume that it didn't resolve the symlink in the current working dir and then everything matched and worked nicely.

It's actually the other way around: Ccache 3.7.9 always resolves symlinks by using realpath(3) both for CWD and absolute paths on the command line. Ccache 4.0 tries to keep symbolic paths to make the basedir mechanism work in more cases (see #491).

**Comment by ohierro-verimatrix** [comment]
Here's a basic Xcode project with ccache configured. If should build successfully from e.g. some path within your `$HOME` folder, but move the project to somewhere under `/tmp` and the compiler will error out with `error: unable to open output file`  

Log file attached also for convenience.

[ccache-issue-724.zip](https://github.com/ccache/ccache/files/5574021/ccache-issue-724.zip)
[ccache.log](https://github.com/ccache/ccache/files/5574030/ccache.log)

**Comment by jrosdahl** [comment]
Thanks! I don't have access to a Mac so I'm afraid the Xcode project won't help me much.

The log file is unfortunately a bit garbled due to parallel invocation of four different compilations so I can't see the full "Command line" part. Would it be possible to build serially to get a consistent log file?

**Comment by ohierro-verimatrix** [comment]
Here is the build log for just one of the source files [ccache.log](https://github.com/ccache/ccache/files/5578612/ccache.log)

**Comment by jrosdahl** [comment]
Thanks.

For clarity, I think there are two separate issues here: (a) ccache rewrites the command line so that the compilation fails (very bad), and (b) setting `base_dir` to `/tmp/...` fails to match the working directory `/private/tmp/...` (unfortunate but not catastrophic). The first thing I want to understand is (a).

Observations:

1. The "actual working directory" (as returned by the libc call `getcwd`) is `/private/tmp/ccache-issue-724`, and the "apparent working directory" (taken from the `PWD` environment variable) is the same.
2. The object file path (_OFP_) is `/tmp/ccache-issue-724/DerivedData/ccache-issue-724/Build/Intermediates.noindex/ccache-issue-724.build/Debug-iphoneos/ccache-issue-724.build/Objects-normal/arm64/ViewController.o`. 
3. In order to get from `/private/tmp/ccache-issue-724` to _OFP_, ccache rewrites the path to `../../../tmp/ccache-issue-724/DerivedData/ccache-issue-724/Build/Intermediates.noindex/ccache-issue-724.build/Debug-iphoneos/ccache-issue-724.build/Objects-normal/arm64/ViewController.o`. This seems correct to me (given the knowledge ccache has).
4. The compiler apparently can't create a file in `../../../tmp/ccache-issue-724/DerivedData/ccache-issue-724/Build/Intermediates.noindex/ccache-issue-724.build/Debug-iphoneos/ccache-issue-724.build/Objects-normal/arm64`, which indicates that the directory doesn't exist. But if it doesn't exist then it shouldn't be possible to create a file in `/tmp/ccache-issue-724/DerivedData/ccache-issue-724/Build/Intermediates.noindex/ccache-issue-724.build/Debug-iphoneos/ccache-issue-724.build/Objects-normal/arm64` either. I don't understand.

If you run `cd /private/tmp/ccache-issue-724; ls -lid . ../../../tmp/ccache-issue-724`, what do you get? What does `ls -lid /private/tmp /tmp` return?

Also, would it be possible for you to catch a log file with ccache 3.7.x as well?

**Comment by ohierro-verimatrix** [comment]
Yeah I'm a bit confused too because the rewritten paths appear to be valid indeed.

> If you run `cd /private/tmp/ccache-issue-724; ls -lid . ../../../tmp/ccache-issue-724`, what do you get? What does `ls -lid /private/tmp /tmp` return?

```
➜  cd /private/tmp/ccache-issue-724; ls -lid . ../../../tmp/ccache-issue-724
21670319 drwxr-xr-x  9 ohierro  wheel  288 Nov 22 00:03 .
21670319 drwxr-xr-x  9 ohierro  wheel  288 Nov 22 00:03 ../../../tmp/ccache-issue-724
➜  /private/tmp/ccache-issue-724 ls -lid /private/tmp /tmp
           10631214 drwxrwxrwt  70 root  wheel  2240 Nov 23 08:34 /private/tmp
1152921500312400699 lrwxr-xr-x@  1 root  admin    11 May 28 03:56 /tmp -> private/tmp
```

Here's a log file generated by ccache 3.7.9 for the same source file: [ccache.log](https://github.com/ccache/ccache/files/5581888/ccache.log)

**Comment by ohierro-verimatrix** [comment]
I've done a bit more testing and came to the conclusion that clang just doesn't like the ccache rewritten paths for the object file path and for the diagnostic file path (`--serialize-diagnostics`), though for the latter it'll only issue a warning and not an error. Even if these paths relative to the CWD are technically valid, clang seems to be unable to write the object file for some reason. For all other paths it's not an issue, e.g. header search paths or even the source file path. 

I can reproduce the same issue, though with slightly different error message, with a simple test file in `/tmp/test.c`:

```
➜  /private/tmp clang -o ../../tmp/test.o ../../tmp/test.c
ld: can't open output file for writing '../../tmp/test.o.ld_ZbE1pN', errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

but the following works:
```
➜  /private/tmp clang -o ../../private/tmp/test.o ../../tmp/test.c
➜  /private/tmp
```

And also works if I `cd` to `/tmp` first:
```
➜ /tmp clang -o ../tmp/test.o ../tmp/test.c
➜ /tmp
```

Anyway, it seems that if ccache would have a config option to continue resolving symlinks in the paths like it did in 3.x then this issue would be solved. Is that a possibility?

**Comment by erijo** [comment]
I tried this on my mac and while I could reproduce the problem once, I can't any more. Not even after a reboot. clang is now perfectly happy to compile my test file: `/private/tmp % clang -o ../../tmp/test.o ../../tmp/test.c`.

**Comment by ohierro-verimatrix** [comment]
> I tried this on my mac and while I could reproduce the problem once, I can't any more. Not even after a reboot. clang is now perfectly happy to compile my test file: `/private/tmp % clang -o ../../tmp/test.o ../../tmp/test.c`.

Interesting. Is that also the case with the Xcode project I attached earlier?

**Comment by erijo** [comment]
> Is that also the case with the Xcode project I attached earlier?

Yes, it builds find under /tmp for me.

**Comment by jrosdahl** [comment]
> `1152921500312400699 lrwxr-xr-x@  1 root  admin    11 May 28 03:56 /tmp -> private/tmp`

I've never seen an `@` sign after the file permission bits before. I wonder what it means. On Linux you can get a `.` in that position if the file has an SELinux context. Is the `/tmp` symlink handled in some special way by the macOS kernel for security reasons?

> I've done a bit more testing and came to the conclusion that clang just doesn't like the ccache rewritten paths for the object file path

Right. And it's not only clang but also ccache, as can be seen in your logs when ccache 4.0 tries to write a file next to the object file:

`[2020-11-22T00:03:49.478314 49980] Failed to open ../../../tmp/ccache-issue-724/DerivedData/ccache-issue-724/Build/Intermediates.noindex/ccache-issue-724.build/Debug-iphoneos/ccache-issue-724.build/Objects-normal/arm64/ViewController.o.ccache-input-text: No such file or directory`

By the way, when ccache rewrites an absolute path into relative it verifies that the absolute and relative paths actually refer to the same i-node. If the file doesn't exist, like in this case, ccache checks the first ancestor directory that does exist instead. In other words, and if there isn't a lurking bug, ccache has verified that the directories `/tmp/ccache-issue-724/DerivedData/ccache-issue-724/Build/Intermediates.noindex/ccache-issue-724.build/Debug-iphoneos/ccache-issue-724.build/Objects-normal/arm64` and `../../../tmp/ccache-issue-724/DerivedData/ccache-issue-724/Build/Intermediates.noindex/ccache-issue-724.build/Debug-iphoneos/ccache-issue-724.build/Objects-normal/arm64` both exist and are the same.

This is all very strange.

> Anyway, it seems that if ccache would have a config option to continue resolving symlinks in the paths like it did in 3.x then this issue would be solved. Is that a possibility?

It would be possible as a workaround, but I wouldn't say that it solves the issue since the default behavior still will be buggy. I would prefer to instead make the 3.x behavior the default on macOS unless we can understand the root cause and find a proper fix.

**Comment by ryandesign** [comment]
> I've never seen an `@` sign after the file permission bits before. I wonder what it means. On Linux you can get a `.` in that position if the file has an SELinux context. Is the `/tmp` symlink handled in some special way by the macOS kernel for security reasons?

`@` means the item has extended attributes. On my macOS 10.13.6 system, using the `-@` flag to `ls`, the extended attribute is `com.apple.rootless`:
```
$ ls -l@ /tmp
lrwxr-xr-x@ 1 root  wheel  11 Jul 16  2018 /tmp -> private/tmp
	com.apple.rootless	 0
```
According to [this](https://eclecticlight.co/2018/01/05/a-short-trip-with-rootless-what-you-can-and-cannot-do/), that should mean that this item is protected by System Integrity Protection, a security feature Apple added several years ago in OS X 10.11 which prevents important system items from being modified, even by root. This prevents the /tmp symlink from being deleted, since that would be bad:
```
$ sudo rm /tmp
rm: /tmp: Operation not permitted
```

**Comment by jrosdahl** [comment]
@ohierro-verimatrix: Could you try if #760 fixes (actually: works around) this issue?

**Comment by ohierro-verimatrix** [comment]
Thank you, I'll give it a spin later today or sometime this week.

**Comment by ohierro-verimatrix** [comment]
My test project builds successfully with the changes in #760. The paths seem to be correctly resolved now relative to the basedir. 

[ccache.log](https://github.com/ccache/ccache/files/5763820/ccache.log)

**Comment by erijo** [comment]
Can you still reproduce the error without the patch? To make sure it hasn't self-healed like it did for me...

**Comment by ohierro-verimatrix** [comment]
> 
> Can you still reproduce the error without the patch? To make sure it hasn't self-healed like it did for me...

Yes, at least with the current master branch it's still reproducible on my mac.
