### ISSUE TITLE
The -X option description should mention the range of allowed compression levels 

### ISSUE THREAD

**Issue by thedrow** [ccache/ccache#728]
### Description ###

Right now it isn't clear what compression levels are available to anyone who doesn't know which compression algorithm ccache uses.
The description for the -X should specify the allowed compression levels range.

**Comment by jrosdahl** [comment]
The compression levels are described in the documention of the [`compression_level`](https://ccache.dev/manual/4.1.html#config_compression_level) configuration option (referenced from `-X/--compress` under [_Common options_](https://ccache.dev/manual/4.1.html#_common_options)), and there is more information in the [_Cache compression`](https://ccache.dev/manual/4.1.html#_cache_compression) section. I would say that it's quite well documented.

Or are you're talking about the terse text printed by `ccache -h`? There isn't room to describe details there, but I can add a short text referring to the manual. Does that sound OK?

**Comment by thedrow** [comment]
> Or are you're talking about the terse text printed by `ccache -h`? 

Yes I am.

I prefer that you'll simply print the range of possible options. E.g. `-10 - 28`.
The range should be available in libzstd, shouldn't it?

**Comment by jrosdahl** [comment]
Yes, the libzstd range is available, but it's more complicated than that.

* All libzstd versions have a query function for the maximum level.
* libzstd 1.4.5 (currently latest) accepts levels -131072 to 22.
* libzstd 1.3.6 and newer have a query function for the minimum level.
* libzstd 1.3.4-1.3.5 accept negative levels but lack a query function.
* Ccache currently accepts levels -128 to 127 and clamps the value to what libzstd accepts. (It looks at the libzstd version to handle the problematic 1.3.4-1.3.5 versions.)
* I would say that it makes little sense to use lower libzstd levels than -5 or so in practice..
* Ccache has internal abstractions in place to support several different compression algorithms. If and when another algorithm is added, it's not possible to tell the available range without also specifying which algorithm to use. This is of course more of a theoretical thing; it's possible that there will never be another supported algorithm.
* Because of the previous point, and because of forward compatibility, I don't want to reject values that are outside of the allowed libzstd range. That is, if a user configures compression level X, I don't want ccache to stop working when using an older libzstd version that doesn't support level X.
* I see a value in letting the `-X` option have the same semantics as the configuration option for compression level.

**Comment by jrosdahl** [comment]
I have now made some related improvements in fa21e9653b4ff07be2694365b88afa2b813d76a7.

**Comment by thedrow** [comment]
Maybe we should reconsider once we can allow ourselves to support only 1.3.6+.

**Comment by thedrow** [comment]
> I have now made some related improvements in [fa21e96](https://github.com/ccache/ccache/commit/fa21e9653b4ff07be2694365b88afa2b813d76a7).

LGTM.
