### ISSUE TITLE
Document how to set settings from CMake

### ISSUE THREAD

**Issue by AlexanderLanin** [ccache/ccache#747]
### Description ###
In google there are lots of instructions like this one:

```
    set(ENV{CCACHE_COMPRESS} "true")
    set(ENV{CCACHE_BASEDIR} "/home")
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ${CCACHE_PROGRAM})
```

However this does not work. Document how to set cmake variables from cmake.

**Comment by AlexanderLanin** [comment]
The best I can figure out at the moment is to create a ccache-set-defaults.sh file like this one:
```
#!/bin/bash
#
# Sets reasonable ccache defaults for our project.


# Compress cache by default (default is false in old ccache 3.x)
ccache --show-config | grep "^(default) compression = false$" >/dev/null && ccache --set-config=compression=true

# Attempt to share cache for source directories within /home dir
# 'ccache --set-config=base_dir=/home' does not work in old ccache 3.x
# So instead locate the config file and write to it:
ccache --show-config | grep "^(default) base_dir = $" >/dev/null && echo "base_dir = /home" >> "$(ccache -s | grep 'primary config' | tr ' ' '\n' | tail -n1)"
```

And in cmake:
```
find_ccache(ENABLE_CCACHE)
if(ENABLE_CCACHE)
    execute_process(COMMAND bash -c "${CMAKE_CURRENT_SOURCE_DIR}/tools/ccache-set-defaults.sh")
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ${CCACHE_PROGRAM})
endif()
```
`find_ccache` is a little wrapper for `find_program` which checks ccache version ranges.

However that seems a little crazy?

Note: the goal is here is to provide reasonable defaults. I do not want to overwrite user settings in case something is configured. Usually users know best what they need.

**Comment by AlexanderLanin** [comment]
Another option is to use this one by @craigscott-crascit.
In contrast to the above it overrides local user settings.

> Permission is given to use any of the code samples in this work without restriction. Attribution is not required.

https://github.com/CppCon/CppCon2020/blob/7a1b35024b833f55697ed420d68045d294eafe3e/Presentations/quickly_testing_qt_desktop_applications_with_approval_tests/approvals_live_demo-2020-09-cppcon/CMake/UseCompilerCache.cmake

In addition to the problem above it shows some other problems and how to solve them.
It sums up to a crazy amount of code. But that is a different issue.

**Comment by craigscott-crascit** [comment]
That sample is taken from my book [Professional CMake: A Practical Guide](https://crascit.com/professional-cmake/), but for those who don't have it, most of the details are covered in the following blog article (the material in the book is essentially an updated, cleaned up version of the blog article):

https://crascit.com/2016/04/09/using-ccache-with-cmake/

**Comment by AlexanderLanin** [comment]
I wonder whether ccache should provide a mechanism like e.g. `.clang-tidy` or `.clang-format` for those (ENV) settings: look in directory of source file, look in it's parent, look in it's parent, etc.

Usually the most narrow scope is valid at the end (first set). However I personally would like an ability to reverse that as shown in the comment above. Only set if not set somewhere else, that is override the defaults of the binary but not of any other config.

On the one hand it's 100% user dependent whether to compress, enable sloppiness etc.
On the other hand I've never seen a project to not provide defaults for those settings to facilitate out of the box experience (and because we usually assume that users like fast compile times / caches, but don't understand any of it / don't care).

**Comment by AlexanderLanin** [comment]
Yet another option is to prefix CMAKE_CXX_COMPILER_LAUNCHER. I guess this works for linux and mac os.

`cmake -DCMAKE_CXX_COMPILER_LAUNCHER="CCACHE_DEBUG=true;ccache" ..`
`set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "CCACHE_DEBUG=true;${CCACHE_PROGRAM}")`

Both options result in something like this one and work just fine:
`CCACHE_DEBUG=true ccache gcc ...`

Interestingly by that we insert settings in the middle of the settings chain:
config file > settings as described above > environment > ccache defaults

**Comment by BenPortner** [comment]
I agree with @AlexanderLanin. Configuring ccache for CMake is impossible right now. @craigscott-crascit's hack is brilliant but there should be an easier way. Please provide a solution.

**Comment by jrosdahl** [comment]
BenPortner wrote (my translation):

> Thanks for ccache! I too have trouble finding a good way to configure ccache for CMake. Has anybody figured out a better solution than the hack mentioned above? Maybe I can help out in some way, for instance by describing what my use case is and what I would like to accomplish?

Thanks for the kind words! Actually, since ccache 4.8 there _is_ a better solution: you can specify ccache configuration options on the command line like so: `ccache [key=value ...] compiler [compiler options]`). This works well with CMake's compiler launcher variables. I've now created a wiki page with more detailed CMake usage tips: https://github.com/ccache/ccache/wiki/CMake

**Comment by BenPortner** [comment]
@jrosdahl 

First off, sorry if my comment sounded inappropriate. I am very thankful for ccache and I think you developers do a great job!

Secondly, thanks for providing an alternative solution and documenting it in the wiki. I believe this will be of great help for other users encountering the same problem.

Thirdly, please find my use case described (by another ccache user) [here](https://stackoverflow.com/questions/77198686/ccache-same-project-in-different-directories). Please also check [my answer](https://stackoverflow.com/a/77821062/12267732) to the described problem, which compares @craigscott-crascit solution to the official one described in your wiki. As you can see, both solutions are very similar in terms of complexity and readability. To be honest, I find neither one very elegant. If I had a wish, I would wish for a project-specific config file, that I could add to my project and that ccache would pick up. The options in the file would be read and will *complement* the user-wide config file at $HOME/.config/ccache/ccache.conf (or another OS-specific path). If an option is given in both files, the project-specific option would be given precedence. Basically the same way how git has user-specific and repo-specific options. I wonder: Is anything like this being worked on?

**Comment by srohmen** [comment]
@BenPortner, I have not read all the linked reports, but what your desire is an additional build folder specific configuration file right? I implemented that feature some time ago: https://github.com/srohmen/ccache/tree/extra-config

I am using that patched ccache version for almost a year now in production without any problem caused by my patch. To make use of that feature, I essentially generat an extra ccache config file via CMake and place it in the build folder. I wanted to upstream the patch at some point but found no time to prepare a PR.

**Comment by jrosdahl** [comment]
Some quick comments:

- Regarding setting `base_dir` from the project build system (from https://github.com/ccache/ccache/pull/906#issuecomment-886653127): "I don't think that the decision to use a base directory is for the project to decide – forcing a base directory on all users [...] is too intrusive, for instance since it makes CMake's Unix generator not work well (hence the [absolute_paths_in_stderr](https://ccache.dev/manual/4.9.html#config_absolute_paths_in_stderr) hack)."
- Similarly for `hash_dir`: setting it to true means that debug info in object files will not be reproduced correctly. To me, this feels more like something to opt in as a user setting, not a project setting.
- Some sloppiness values might make more sense to have as a project setting.

That said, there are ccache settings that do make sense as project settings, and I understand if users want the convenience of setting all configuration via their build system. I wouldn't be against adding a directory/project-specific configuration file; I've actually tried to come up with a good design before but didn't quite reach a conclusion on how I think it should work.

Since this issue is about documenting how to set settings from CMake, I think that there is nothing more to do here. Discussion on if and how to implement a project/directory-specific configuration file is not related to CMake, so I suggest opening a separate issue for that idea.

**Comment by jrosdahl** [comment]
> Discussion on if and how to implement a project/directory-specific configuration file is not related to CMake, so I suggest opening a separate issue for that idea.

I opened #1393 for this.
