### ISSUE TITLE
Support for "cuda" language

### ISSUE THREAD

**Issue by rgreenblatt** [ccache/ccache#772]
At the moment, ccache doesn't work when building cuda code with [clang directly](https://llvm.org/docs/CompileCudaWithLLVM.html).

The documentation seems to imply that this should be supported, but it isn't.

I would appreciate this feature.

**Comment by jrosdahl** [comment]
> At the moment, ccache doesn't work when building cuda code with clang directly.

Could you please give more details, preferably in the form of a simple example that doesn't work like you expect?

> The documentation seems to imply that this should be supported, but it isn't.

Which documentation do you refer to?

**Comment by rgreenblatt** [comment]
Save the following to file.cu and then build twice with `ccache clang++ file.cu --cuda-gpu-arch=sm_52`. This will requires cuda installed and you may need to to add the argument `--cuda-path=<PATH TO CUDA>`.
```cpp
template<typename T, unsigned n>
struct SlowToBuild {
  SlowToBuild<T*, n - 1> first;
  SlowToBuild<SlowToBuild<T, n-1>*, n - 1> second;
};

template<typename T>
struct SlowToBuild<T, 0u> {
  T v;
};

int main() {
  SlowToBuild<int, 15>();
}
```
I made the build slow just so that it is obvious the build isn't being cached.
 I would expect that ccache would cache the build.
`ccache -s` shows that ccache was "called for link", but it doesn't show a cache hit or a miss.

The [supported platforms list](https://ccache.dev/platform-compiler-language-support.html) includes clang and the cuda language, so I thought that building cuda with clang would be supported

**Comment by jrosdahl** [comment]
> `ccache -s` shows that ccache was "called for link", but it doesn't show a cache hit or a miss.

That's because you're doing both compilation and linking at the same time. Ccache only supports compilation with `-c` (and this is true for all compilers and languages, not only CUDA).

In other words, do this instead:

    ccache clang++ -c file.cu --cuda-gpu-arch=sm_52
    clang++ file.o -o file

**Comment by rgreenblatt** [comment]
Sorry about that - the issue actually occurs only when using `-x cuda` (which cmake passes by default).
No caching occurs when running `ccache clang++ -x cuda -c file.cu --cuda-gpu-arch=sm_52`.
`ccache -s` shows "unsupported source language". 

So a workaround is to avoid passing -x cuda when the file has a .cu extension becuase clang can infer the language type.
It would still be nice if this was fixed.

**Comment by jrosdahl** [comment]
This rings a bell. It's quite complicated and I'm not sure I fully remember the details. Let's see:

1. b2d6d53d7cbb303573ccce79ddfe74acad08c03f (ccache 3.3) added support for language `cuda`.
2. a5e5b6dc8eae (ccache 3.7.9), part of #381, added support for language `cu`.
3. c4fffda031034f930df2cf188878b8f9160027df (ccache 3.7.9), which I added to #381, removed support for language `cuda` since NVCC doesn't understand `cuda`.
4. 95b0dc5a76bff88ba420a62b7bf2e74e8ea7e300 (ccache 4.0) re-added support for `cuda` since _"Clang apparently recognizes it"_. Related comment: https://github.com/ccache/ccache/pull/381#issuecomment-517798732.
5. 2728c68bba9f8b4bb5c8812cd1b50402b81ebfd9 (ccache 4.0) reverted the above commit, saying _'NVCC maps the “.cu” extension to “cu” but Clang maps it to “cuda”, so it’s ambiguous. Let’s ignore the Clang case for now.'_ Related comment: https://github.com/ccache/ccache/pull/381#issuecomment-517803372.

As you might guess I'm reluctant to just add support for `cuda` again without further analysis.

If I interpret myself correctly, the issue mentioned in 2728c68bba9f8b4bb5c8812cd1b50402b81ebfd9 is that `k_ext_lang_table` should map `.cu` to `cu` in the NVCC case but `cuda` in the Clang case. The current usage of the language query functions may work if `.cu` is mapped to `cu` regardless of compiler type, but I'm not 100% sure. For general sanity, it would be better if the ambiguity was resolved.

**Comment by rgreenblatt** [comment]
Yeah, this doesn't seem worth it. If [allowing non-standard languages](https://github.com/ccache/ccache/issues/308) happens more generally it would resolve this.

Here is a gross workaround for cmake:
```cmake
# remove _CMAKE_COMPILE_AS_CUDA_FLAG to support ccache
if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  set(CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
    "<CMAKE_CUDA_COMPILER> ${_CMAKE_CUDA_EXTRA_FLAGS} <DEFINES> <INCLUDES> <FLAGS> -c <SOURCE> -o <OBJECT>")
endif()
```

**Comment by jrosdahl** [comment]
I would like to keep this feature request open since I think it's a reasonable feature. It's just that the implementation will be slightly more than adding an entry to `k_lang_p_lang_table`.

**Comment by romintomasetti** [comment]
I would like to reopen this issue, because it seems that `ccache` (release `4.10`) is still not able to make caching work with `clang` compiling `CUDA` code.

Looking at the logs:
> [2024-07-26T09:31:10.264304 25321] Running preprocessor
[2024-07-26T09:31:10.264345 25321] Executing /usr/bin/clang++ --cuda-gpu-arch=sm_86 -x cuda -E -o /workspaces/.../.ccache//tmp/cpp_stdout.tmp.hYklc0.i test.cpp
[2024-07-26T09:31:10.284040 25321] Preprocessor gave exit status 1

Indeed, running the command myself leads to `clang++` complaining that:
> clang++: error: cannot specify -o when generating multiple output files

I'm not sure how to make `clang++` happy...

Here is a sample script, that can be run in one of the `nvidia`'s Docker images (you'll also need a recent `clang` installed).

```bash
set -ex

TEST_SOURCE_FILE=test.cpp
TEST_OBJECT_FILE=test.o
TEST_EXECUT_FILE=test.out

# Simple test file with some CUDA code.
rm -r ${TEST_SOURCE_FILE}
cat <<EOF > ${TEST_SOURCE_FILE}
#include "cuda.h"

__device__ double kernel(const double value) {
    return value * 2.;
}

__global__ void entry(const double value) {
    printf("%f transformed to %f.\n", value, kernel(value));
}

int main()
{
    const double value = 7.85;
    entry<<<1,1>>>(value);
    cudaDeviceSynchronize();
    return 0;
}
EOF

# Set ccache debugging.
export CCACHE_DEBUG=true
export CCACHE_DEBUGLEVEL=2
export CCACHE_LOGFILE=$PWD/ccache.log

# Remove previous ccache log file.
rm -f ${CCACHE_LOGFILE}

# Zero ccache statistics.
ccache --zero-stats

# Compile command: use clang with CUDA language enabled.
function compile()
{
    ccache clang++ -x cuda --cuda-gpu-arch=sm_86 -c ${TEST_SOURCE_FILE} -o ${TEST_OBJECT_FILE}
}

# Compile twice.
compile
compile

# Check ccache stats.
ccache -s -x -v

# Remove previous executable.
rm -f ${TEST_EXECUT_FILE}

# Link and run the executable.
clang++ -L /usr/local/cuda/lib64 -lcudart ${TEST_OBJECT_FILE} -o ${TEST_EXECUT_FILE}
./${TEST_EXECUT_FILE}
```

**Comment by jrosdahl** [comment]
@romintomasetti: Thanks for the reproduction recipe. Since this issue was closed over 3 years ago, please open a [new issue](https://github.com/ccache/ccache/issues/new/choose) instead of leaving a comment here.
