### ISSUE TITLE
Fast linker selection doesn't work

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#794]
### How to reproduce ###

1. Configure ccache with `ld.lld` or `ld.gold` installed.
2. Build ccache with verbosity to see the executed linker commands.

### Actual behavior ###

Neither `ld.lld` nor `gold` is used as the linker.

### Expected behavior ###

`ld.lld` or `gold` is used as the linker.

### Environment ###

ccache version master.bc6f070e

----

See comments in https://github.com/ccache/ccache/pull/788#issuecomment-766618320.

**Comment by nickhutchinson** [comment]
I think the current implementation of UseFastestLinker.cmake is problematic. Ccache's build shouldn't assume that finding ld.gold or ld.lld on PATH means this linker is actually useable by the active compiler. Some concrete examples where this goes wrong:

- macOS: clang when ld.lld is on your PATH: `clang: error: invalid linker name in argument '-fuse-ld=lld'`
- Windows: mingw-w64 GCC when ld.lld.exe is on your PATH: `g++.exe: error: unrecognized command line option '-fuse-ld=lld'; did you mean '-fuse-ld=bfd'?`
- Windows: MSVC when ld.lld.exe is on your PATH: `LINK : warning LNK4044: unrecognized option '/fuse-ld=lld'; ignored`. (Seems the MSVC linker ignores unknown arguments, which is why the MSVC CI build didn't break.)

It looks like some older versions of GCC also don't support `-fuse-ld=lld`. See: https://gcc.gnu.org/bugzilla//show_bug.cgi?id=83243

**Comment by jrosdahl** [comment]
Thanks. This is the kind of feedback I was looking for in https://github.com/ccache/ccache/pull/788#issuecomment-775468507 but didn't get and was hoping to kind of provoke with re-adding the implementation. :slightly_smiling_face:
