### ISSUE TITLE
ccache does not recognize c++ being clang++ on macOS (-fcolor-diagnostics gives "unsupported compiler option")

### ISSUE THREAD

**Issue by koliyo** [ccache/ccache#806]
### How to reproduce ###

1. Run ccache via c++ dispatch instead of clang++, and make sure to include `-fcolor-diagnostics` flag, ie `/usr/local/opt/ccache/libexec/c++ -fcolor-diagnostics ...`
2. Watch `unsupported compiler option` increase in ccache stats

### Actual behavior ###
Ccache does not seem to realize that `c++` is actually `clang++` on MacOS

If I change the dispatch to using `/usr/local/opt/ccache/libexec/clang++`, I get no error, and caching works properly

### Expected behavior ###
Caching should work

Also, additional problem is that `CCACHE_DEBUG` setting does not work for tracing `unsupported compiler option`, it does not even write a `*.ccache-log` file!

### Environment ###
```
$ /usr/bin/c++ --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


$ ccache --version
ccache version 4.2
```

**Comment by koliyo** [comment]
This is problematic especially because `c++` is the default compiler detected in my environment.

My current workaround is explicitly defining compiler env variables

```
export CXX=clang++
export CC=clang
```

**Comment by jrosdahl** [comment]
> Ccache does not seem to realize that `c++` is actually `clang++` on MacOS

That's expected if `/usr/bin/c++` is not a symlink to the real compiler but an actual binary. I don't think there is anything ccache can do about this given how compiler detection currently works.

The [documented way to fix this](https://ccache.dev/manual/4.2.html#config_compiler_type) is to set compiler type to `clang` explicitly (e.g. `export CCACHE_COMPILERTYPE=clang`). Please try it out.

> Also, additional problem is that `CCACHE_DEBUG` setting does not work for tracing unsupported compiler option, it does not even write a *.ccache-log file!

Fixed in 9f19f94ba7c795ce86c5aec5e274548745a3b809.

**Comment by koliyo** [comment]
Thanks for response!

I understand this is a bit problematic for the compiler detection. And I have been able to resolve it using the `CXX/CC` flags. And also thanks for noting the `CCACHE_COMPILERTYPE` setting.

But I still think it would be helpful if ccache could solve this automatically. My reasoning for this is that I do not have a special/customized environment. I have a standard MacOS install + homebrew, which is a very common environment. So making sure this works well by default with ccache is maybe worth some extra effort.

A potential solution seems like not only finding the `/usr/bin/c++` binary, but also calling it using `/usr/bin/c++ --version`, which would reveal that it is clang and not g++.

**Comment by jrosdahl** [comment]
> But I still think it would be helpful if ccache could solve this automatically.

Certainly.

> My reasoning for this is that I do not have a special/customized environment. I have a standard MacOS install + homebrew, which is a very common environment. So making sure this works well by default with ccache is maybe worth some extra effort.

I don't have data to back this up, but my guess is that the number of ccache users on macOS is _much_ smaller than ccache users on Linux-based systems, which makes macOS an uncommon environment for ccache. The current behavior of compiler detection (or rather: guessing) is modelled after the de facto setup used on Linux systems.

That said, after thinking more about it I realized that there is a very simple way to solve your issue. Fix coming up.

> A potential solution seems like not only finding the `/usr/bin/c++` binary, but also calling it using `/usr/bin/c++ --version`, which would reveal that it is clang and not g++.

Right, the idea of doing that kind of compiler probing has come up several times in the past in different scenarios. I'm not against it in principle, but for practical reasons only doing compiler guessing from name has been enough so far and I would like to avoid compiler probing unless necessary. My position has been that if we start doing compiler probing then it would be nice to consider doing compiler feature detection instead of trying to deduce behavior from compiler type/version.
