### ISSUE TITLE
Fails to run under fakeroot on Debian Bullseye

### ISSUE THREAD

**Issue by phippodoplis** [ccache/ccache#984]
### How to reproduce ###
Running under fakeroot:
fakeroot ccache g++ blah.cpp

### Actual behavior ###
ccache: error: Failed to create directory /run/user/0/ccache-tmp: Permission denied

### Expected behavior ###
It should compile blah.cpp

### Environment ###
ccache version 4.2

It's down to this commit https://github.com/ccache/ccache/commit/213d9883a0c3944749f8512eeb784d8572ad8d91

In particular this bit at about line 862 of src/Config.cpp:

#ifdef HAVE_GETEUID
  if (Stat::stat(fmt::format("/run/user/{}", geteuid())).is_directory()) {
    return fmt::format("/run/user/{}/ccache-tmp", geteuid());
  }
#endif
  return cache_dir + "/tmp";

That test should also check that the /run/user/X directory is writeable.

**Comment by ottok** [comment]
@jrosdahl 

Now ccache 4.6 fails if the path is not writable. E.g. my MariaDB builds are now broken with:
```
/usr/lib/ccache/cc   -g -O2 -ffile-prefix-map=/tmp/build/source=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2  -o CMakeFiles/cmTC_5f45a.dir/testCCompiler.c.o -c /tmp/build/source/builddir/CMakeFiles/CMakeTmp/testCCompiler.c
ccache: error: Failed to create temporary file for /run/user/0/ccache-tmp/tmp.cpp_stdout.x83PCf: Permission denied
```

Previously it felled back to using `/tmp/ccache` and builds passed and ccache worked. I am running builds inside a container that does not have this path writable. If the path is not writable, it should not fail the whole build.

**Comment by ottok** [comment]
This issue should be re-opened for further fine tuning fallback to use `/tmp/ccache` or some other `CCACHE_DIR` if that user `run/` path is not writeable.

**Comment by jrosdahl** [comment]
> Previously it felled back to using `/tmp/ccache` and builds passed and ccache worked.

I can reproduce a problem with running ccache 4.0-4.6 with fakeroot if `/run/user/0/ccache-tmp` exists (presumably because the actual root user has run ccache at least once). That is, I can't reproduce any regression in 4.6 (with 213d9883a0c3944749f8512eeb784d8572ad8d91) in this area like you seem to imply with "Now ccache 4.6 fails if the path is not writable". Or did you by "Previously" mean ccache before version 4.0?

> This issue should be re-opened

No, it shouldn't. This is another case since 213d9883a0c3944749f8512eeb784d8572ad8d91 fixes the reported problem in this issue (although the _How to reproduce_ steps were lacking details). Ccache 4.6 correctly handles the case when `/run/user/0` exists, but ccache 4.5.1 does not.

Next time, it would be great if you could take the time to create a new issue with proper background information and steps on how to reproduce instead of piggy-backing on a closed issue. Thanks!

**Comment by jrosdahl** [comment]
I created #1044 to track the `/run/user/0/ccache-tmp` issue.
