### ISSUE TITLE
Allow CCACHE_UNIFY and CCACHE_DIRECT to be used together

### ISSUE THREAD

**Issue by jrosdahl** [ccache/ccache#99]
From https://bugzilla.samba.org/show_bug.cgi?id=11712:

```
The current documentation says this:

 unify (CCACHE_UNIFY) [boolean]
... Also note that enabling the unifier implies turning off the direct mode.

It seems like these could be used together.  For instance, if the direct hash lookup misses, run the preprocessor and unifier, and lookup that hash.

Alternatively, if ccache already behaves this way, please update the documentation.
```

**Comment by afbjorklund** [comment]
I couldn't even remember what the "unifier" was supposed to do...

> Also note that enabling the unifier implies turning off the direct mode.

I suppose that is the main reason why I have never even looked at it.

And this feature is probably even less used now, when whitespace and
other preprocessor fluff _does_ change the compiler output (thus CPP2)...

> // C/C++ unifier
> //
> // The idea is that changes that don't affect the resulting C code should not
> // change the hash. This is achieved by folding white-space and other
> // non-semantic fluff in the input into a single unified format.

The feature seems to be inherited from the original [compilercache](http://www.erikyyy.de/compilercache/) ?

> The preprocessor output is fed through a program called "unifier".
> The output of the unifier is then taken for the md5sum. The unifier
> works like a C/C++/ObjC lexer. All it does is write each token on a
> single line. it takes # lines (like #pragma) like one big token [...]

But it also says:

> the unifier is the real power of the compilercache.

So maybe this *should* be investigated more, and fixed/documented better ?

If we are not *using* the preprocessed code anymore, line numbers are OK.

> Enabling the unifier may result in incorrect line number information in compiler warning messages and expansions of the __LINE__ macro.

**Comment by mblythe86** [comment]
> 
> > Also note that enabling the unifier implies turning off the direct mode.
> 
> I suppose that is the main reason why I have never even looked at it.

As I said in the original bug, I don't think this has to be the case.

Currently, if the direct hash lookup misses, then ccache runs the preprocessor, hashes that, and does a lookup again.  I think this could be changed to simply run the preprocessor and unifier, and lookup again.

> And this feature is probably even less used now, when whitespace and
> other preprocessor fluff does change the compiler output (thus CPP2)...

Do you have an example of this?  I didn't think whitespace was significant in C++?  I agree that whitespace and preprocessor directives will change the preprocessor output, but I don't think I've seen a case where a whitespace change causes a change in the final object file. (Aside from the trivial case of whitespace in strings.)

> the unifier is the real power of the compilercache.

I agree that this would be powerful.  I've noticed several identical object files in my ccache, and many times I've traced it back to a simple whitespace change...removing/adding a blank line, fixing indentation, adding spaces to align variable declarations or function arguments, adding/removing preprocessor directives that have no effect, etc..  Even adding or removing comments has the same effect!  (The preprocessor removes comments, but if they were added on a new line, it looks like a blankline was added.) If I could still hit in my ccache after changes like this, it would be a great improvement.

**Comment by afbjorklund** [comment]
I was (as usual) bantering, but using cpp2 means that we "cannot" trust the precompiled code. Probably because `clang -Weverything` will not return the same results, or somesuch...
But I think that maybe we should do what you say, and maybe ignore matches with cpp2 - unless we can prove that it's only whitespace ?

**Comment by afbjorklund** [comment]
The main "problem" is that we don't cache only object files - but also the warnings/errors...

**Comment by mblythe86** [comment]
Ah, I think I follow now.  Yes, I agree that compiler error/warning messages can change if the unifier is used.  For example, if a bunch of blank lines are added or removed, then any cached error message would point to a line way off from the current source file.  And that could happen regardless of whether CPP2 is set or not.  Actually, that would happen regardless of DIRECT, too...it;s just an inherent limitation of using the unifier.

> Enabling the unifier may result in incorrect line number information in compiler warning messages and expansions of the __LINE__ macro.

I didn't notice where you were quoting this from before...it's the documentation of the "unify" option. Since the documentation for "unify" already calls out these risks, it should be up to the user whether that's acceptable to them or not.

Actually, using CPP2 somewhat mitigates this, as well.  Instead of line number information and ``__LINE__`` being *really* wrong (due to unify putting every token on a separate line), they are just a little wrong sometimes.

I still don't see anything here that's fundamentally incompatible between UNIFY and DIRECT modes.  In fact, I wonder if it would "just work" by removing the following from ccache.c:
```C++
	if (conf->unify) {
		cc_log("Direct mode disabled because unify mode is enabled");
		conf->direct_mode = false;
	}
```

I'll have to give that a shot locally...

**Comment by afbjorklund** [comment]
Added some code to try this out, in a9cab3a540ff598bb00968d5da3c6b660d56d9c7.

Basically it's the difference between `test1.i`:
```
# 1 "test1.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "test1.c"
int foo10(int x) { return x; }
```

and `test1.u` (or something, "unified"):
```
int
foo10
(
int
x
)
{
return
x
;
}

```

**Comment by jrosdahl** [comment]
> Added some code to try this out, in a9cab3a.

Applied on master, thanks!
